### ISSUE TITLE
'High Contrast Black' theme Avatar (Borders) border color 

### ISSUE THREAD

**Issue by prsdthkr** [SAP/fundamental-styles#1000]
**Describe the bug**
Borders variant in the Avatar component has no visible border.

> What version of the Fundamental Library Styles are you using?
v0.9.1-rc.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
React

**To Reproduce**
1. Go to https://deploy-preview-928--fundamental-styles.netlify.app/components/avatar.html
2. Check Borders variant

**Expected behavior**
Borders variant in the Avatar component should have a visible border (`#fff`)  in Fiori 3 HCB theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/43764832/81732354-3ae59480-9445-11ea-80f1-dd307930961c.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Comment by Mike-Diaz** [comment]
Fixed as of https://github.com/SAP/fundamental-styles/pull/1789.
![image](https://user-images.githubusercontent.com/21978807/96761897-1a275080-138e-11eb-84bc-dc8be3c50398.png)
