### ISSUE TITLE
Generic Tile - missing theme parameters

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#1048]
Generic Tiles specs have some calculations that cannot be used in Fundamental-styles. We need to update the values once sap-theming releases the calculated values. 

Examples:
Box-shadow: 0 0 0 1px fade (@sapUiContentShadowColor, 30);
§font-color: contrast(§background-color, @sapUiTileTitleTextColor, @sapUiContentContrastTextColor, @sapUiContentContrastTextThreshold);
text-shadow: 0 0 0.125rem contrast(§font-color, @sapUiContentShadowColor, @sapUiContentContrastShadowColor, @sapUiContentContrastTextThreshold);
font-color: contrast(§background-layer-color, @sapUiTileTextColor, @sapUiContentContrastTextColor, @sapUiContentContrastTextThreshold);
text-shadow: 0 0 0.125rem contrast(§font-color, @sapUiContentShadowColor, @sapUiContentContrastShadowColor, @sapUiContentContrastTextThreshold);
box-shadow for dots: 0 0 0.25rem fade(@sapUiContentShadowColor, 25)

**Comment by droshev** [comment]
addressed as part of delta theming
