### ISSUE TITLE
HCB bug report

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#1049]
- [x] Action bar
I know action bar is not a fiori 3 component but according to the specs on shellbar, it will make sense to apply the white underline on the action bar to make it more accessible 

- [x] Avatar ( I created separate issue for this #1192)
Accent color parameters incorrect 

- [x] Bar
The select mode 
<img width="211" alt="Screen Shot 2020-05-21 at 12 16 27 PM" src="https://user-images.githubusercontent.com/54589269/82580467-213b0000-9b5d-11ea-9ad9-f7c6f773b6aa.png">

- [x] Button
Pressed color is incorrect
<img width="384" alt="Screen Shot 2020-05-21 at 12 32 01 PM" src="https://user-images.githubusercontent.com/54589269/82581788-16816a80-9b5f-11ea-8e93-8436cdc61065.png">

- [x] Inline help 
Although inline help is not a fiori 3 component, it should apply the popover's parameter 
<img width="475" alt="Screen Shot 2020-05-21 at 12 27 40 PM" src="https://user-images.githubusercontent.com/54589269/82581364-7b889080-9b5e-11ea-9c49-079fb3d8bcfe.png">

- [x] Shellbar
There should be a white underline in shellbar
<img width="797" alt="Screen Shot 2020-05-21 at 12 35 07 PM" src="https://user-images.githubusercontent.com/54589269/82582117-8f80c200-9b5f-11ea-91f8-10140ffa838b.png">

- [x] Status indicator (component has been deprecated)
The color is incorrect
<img width="222" alt="Screen Shot 2020-05-21 at 12 37 57 PM" src="https://user-images.githubusercontent.com/54589269/82582385-f8683a00-9b5f-11ea-8fc2-a4cb83d72c24.png">

- [x] Switch (works in styles)
Switch with text is missing text 
<img width="260" alt="Screen Shot 2020-05-21 at 12 39 02 PM" src="https://user-images.githubusercontent.com/54589269/82582519-32d1d700-9b60-11ea-87c8-0dce57e04192.png">

**Comment by rengare** [comment]
Hi @estelaxu3 I have question about Switch. Did you mean that switch doesn't have a text inside like in the screenshot?
![image](https://user-images.githubusercontent.com/10849982/86020732-92a58280-ba28-11ea-962a-6a43982aa9b5.png)
If so then this was intended. Otherwise, all texts are visible and have white colour
