### ISSUE TITLE
button focus goes outside on IE11

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-styles#1051]
**Describe the bug**
focus goes outside of the button
> Is this issue related to a specific component?
button
> What version of the Fundamental Library Styles are you using?
latest
> What front-end framework are you implementing in, e.g., Angular, React, etc.?
all

**To Reproduce**
1. Click button

**Expected behavior**
Focus should be on the inside of the button
**Screenshots**
![Screen Shot 2020-05-21 at 3 53 04 PM](https://user-images.githubusercontent.com/50607147/82599985-2b6bf700-9b7b-11ea-9f12-b367f1e90f78.png)

**Comment by rengare** [comment]
a common issue in IE 11 which can't be fixed

**Comment by droshev** [comment]
another button issue #1055
