### ISSUE TITLE
button on press down doesn't show the focus dots(Safari, Firefox)

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1055]
**Description**
          On click on buttons dotted border focusing is not happening for Firefox, Safari.

> Is this issue related to a specific component?
          :  Button

> What version of the Fundamental Library Styles are you using?
            0.9

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
            Angular

**To Reproduce**

1. In Mac Machine open Browser: Safari, firefox
2. Enter the fundamental-styles url
3. Click on Button
4. It is not focused on the dotted border.

**Expected behavior**
        Mouse click on button focusing with dotted border should  happen even in Firefox and Safari

<img width="290" alt="Screen Shot 2020-05-23 at 2 21 26 PM" src="https://user-images.githubusercontent.com/53487468/82726329-073a2280-9d01-11ea-933e-d70b6ef68e84.png">

**Comment by droshev** [comment]
a button related issue #1051

**Comment by InnaAtanasova** [comment]
As discussed with @rengare this fix would require `before` or `after` attributes which are already used for the icons. Currently we don't have a solution for this issue.

**Comment by droshev** [comment]
We discussed the issue and agreed to do a breaking change and introduce a `i` element for the icon so we can address the focus and press down issue
