### ISSUE TITLE
Paddings in panel component

### ISSUE THREAD

**Issue by marynaKhromova** [SAP/fundamental-styles#1057]
**Describe the bug**
When the panel has `[bleed]="true"` and the table is used as panel content, the paddings for first and last cells are not the same as paddings in panel header. So the content is not aligned vertically.

> Is this issue related to a specific component?
[Panel](https://sap.github.io/fundamental-styles/layouts/panel.html)

> What version of the Fundamental Library Styles are you using?
0.8.1

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

Expected behavior**
Paddings have the same value.

**Screenshots**
<img width="917" alt="panel-bleed" src="https://user-images.githubusercontent.com/46446373/82922761-4e7f1800-9f7a-11ea-9994-02788f779920.png">

**Comment by droshev** [comment]
@marynaKhromova the panel is under refactoring. You can follow the PR #1024

**Comment by marynaKhromova** [comment]
> @marynaKhromova the panel is under refactoring. You can follow the PR #1024

Great, thank you for sharing 👍
