### ISSUE TITLE
Defect Hunting - May 27-28

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1060]
- [x] doc site - Gracjan - #1063
![Screen Shot 2020-05-27 at 5 18 23 PM](https://user-images.githubusercontent.com/4380815/83073294-3375dc00-a03e-11ea-94a9-6f89caa5b5a6.png)
- [ ] styling looks odd https://fundamental-styles.netlify.app/layouts/shell-layout.html - It's completely outdated, should be marked as deprecated
- [ ] double message border - Jedrzej - TBD
![Screen Shot 2020-05-27 at 5 26 14 PM](https://user-images.githubusercontent.com/4380815/83073951-50f77580-a03f-11ea-8a53-6dbc08c7aab6.png)
- [x] link `Show All` not properly used - Mike
![Screen Shot 2020-05-27 at 5 29 48 PM](https://user-images.githubusercontent.com/4380815/83074168-b9465700-a03f-11ea-824c-cd0542e38b78.png)

**Comment by JKMarkowski** [comment]
Header in IE11
![image](https://user-images.githubusercontent.com/26483208/83141875-96c04680-a0f0-11ea-8af6-bac46dd4e96e.png)
