### ISSUE TITLE
Readonly state for Select is not working

### ISSUE THREAD

**Issue by cham2017** [SAP/fundamental-styles#1061]
Dear developer,
I followed the instructions as below:

> To make the Select component read-only, the readonly attribute needs to be added to the fd-select__control element. This can also be done by adding the .is-readonly class or the aria-readonly="true" attribute.

My code is like below. However the Select that rendered is still same as the usual one.

```
const { toolTip, enabled = true, visible = true, readOnly = false } = props;
const readOnlyProperty = readOnly ? "true" : "false";
import "fundamental-styles/dist/select.css";
import { Select } from "fundamental-react";
  const dropDownListBoxClass = classnames(
    "fd-select--compact",
    readOnly ? "is-readonly" : ""
  );
<Select className={dropDownListBoxClass} title={toolTip} disabled={!enabled} aria-readonly={readOnly}></Select>
```

**Comment by salarenko** [comment]
Hey @cham2017, I think this is rather components library issue than styles issue.
The repository you are probably looking for is https://github.com/SAP/fundamental-react
