### ISSUE TITLE
Table - either incorrect header height or condensed checkbox in header not vertically aligned

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-styles#1103]
I am pretty sure the header should have a height of 1.5 rem in condensed mode judging from the specs but they are kind of confusing.  Maybe the checkbox just needs to be vertically centered.  See screenshot

<img width="387" alt="Screen Shot 2020-06-03 at 2 30 04 PM" src="https://user-images.githubusercontent.com/2471874/83686681-e0ed7000-a5a7-11ea-8b1b-990ab8a1895b.png">

**Comment by stefanoScalzo** [comment]
Issue has been fixed
