### ISSUE TITLE
Drag and Drop styles are required for List as per Fiori3 standards.

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1109]
In List several items can be repositioned within or moved to other UI elements using drag and drop operations.
While being dragged, the items are shown as ghost elements on the mouse cursor.
On a drop target, the mouse cursor changes to either a “copy”, “link”, “move”, or “none” cursor

> Is this issue related to a specific component?
List and upload document
> What browser are you working in?

> What version of Fundamental Library Styles are you using?
0.10

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

<img width="297" alt="Screen Shot 2020-06-08 at 9 47 53 AM" src="https://user-images.githubusercontent.com/53487468/83992437-ed8a1380-a96d-11ea-921b-fb7405ae39d9.png">

**Comment by droshev** [comment]
will be tackled as part of [#2063](https://github.com/SAP/fundamental-styles/issues/2063)
