### ISSUE TITLE
No Data Styles as per Fiori3 required in List

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1110]
List (Fiori 3) - For "No Data" styles are required as per Fiori3 standards in List.

> What version of Fundamental Library Styles are you using?
0.10

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular
<img width="729" alt="Screen Shot 2020-06-08 at 2 16 51 PM" src="https://user-images.githubusercontent.com/53487468/84010984-11138500-a993-11ea-96f9-1e9dc142dcf7.png">

**Comment by droshev** [comment]
will be tackled as part of [#2063](https://github.com/SAP/fundamental-styles/issues/2063)
