### ISSUE TITLE
Highlight Indicator in front of list item - styles required

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1112]
To show that an item needs attention, a highlight indicator can be shown in front of the item. The highlight indicator can be used to indicate as per Fiori3 guidelines.

For example:
-   red or orange for an error or warning. 
-   blue to highlight newly added items.
-   Industry-specific or process-specific states, such as “out of stock” or “excess of inventory”. In this case, use indication colors.

> Is this issue related to a specific component?
List-item

> What version of Fundamental Library Styles are you using?
0.10

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

<img width="271" alt="Screen Shot 2020-06-08 at 2 32 19 PM" src="https://user-images.githubusercontent.com/53487468/84012235-ddd1f580-a994-11ea-9373-884ea77a5e02.png">

**Comment by stefanoScalzo** [comment]
We need a UI5 spec for this

**Comment by droshev** [comment]
will be tackled as part of [#2063](https://github.com/SAP/fundamental-styles/issues/2063)
