### ISSUE TITLE
Make close icon in token optional

### ISSUE THREAD

**Issue by ChristianKienle** [SAP/fundamental-styles#113]
This issue is about the token component as described here:

https://sap.github.io/fundamental/components/token.html

Not sure what the spec says to be honest but have you considered making the `x` in tokens optional? At the moment the `x` is added via CSS and not by using some other means that could be simply left out.

Related issue: #952

I am unable to access the content behind the link mentioned in #952 so this issue could very well be a duplicate.

**Comment by salarenko** [comment]
This issue has been resolved with #500
(https://sap.github.io/fundamental-styles/components/token.html)
