### ISSUE TITLE
Token is not compliant with latest Fiori3 updates

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-styles#1172]
**Describe the bug**
Some updates were made to paddings and other variables values in April. These need to be changed for the current Token/Tokenizer styles.

> Is this issue related to a specific component?
Token/Tokenizer

> What version of the Fundamental Library Styles are you using?
0.10

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**To Reproduce**
1. Go to 'https://sap.github.io/fundamental-styles/components/token.html'
2. Styles are not as per latest Fiori3 design

**Expected behavior**
Styles should be aligned with Fiori3

**Comment by mikerodonnell89** [comment]
Could you be more specific?  What is missing?

**Comment by droshev** [comment]
> **Describe the bug**
> Some updates were made to paddings and other variables values in April. These need to be changed for the current Token/Tokenizer styles.
> 
> > Is this issue related to a specific component?
> > Token/Tokenizer
> 
> > What version of the Fundamental Library Styles are you using?
> > 0.10
> 
> > What front-end framework are you implementing in, e.g., Angular, React, etc.?
> > Angular
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'https://sap.github.io/fundamental-styles/components/token.html'
> 2. Styles are not as per latest Fiori3 design
> 
> **Expected behavior**
> Styles should be aligned with Fiori3

@kavya-b can you share more details?

**Comment by kavya-b** [comment]
1. **padding values have changed for token in both cozy and compact mode:**
current: only padding left value given
new: vertical padding in addition to padding left also given 

2. **padding for close icon and readonly class:**
current: only horizontal padding
new: has both vertical and horizontal paddings

3. **min-width added for cozy and compact modes**

4. **padding for tokenizer input**
current: left padding of 0.3125rem provided with assumption that tokens are present
new: left padding of 0.625rem when no tokens are present

before/after images are added in the PR #1176 description.
