### ISSUE TITLE
Localization Editor styling is broken

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#119]
**Describe the bug**
- the styling in compact mode is broken(see the attachment)
- the menu in cozy mode doesn't open on click

![Screen Shot 2019-06-21 at 10 00 59 AM](https://user-images.githubusercontent.com/4380815/59927949-a24cbd00-940b-11e9-8d8d-a0c788b6ae61.png)

**Comment by jbadan** [comment]
related to https://github.com/SAP/fundamental-styles/issues/34

fix is to remove height here: https://github.com/SAP/fundamental-styles/blob/master/scss/components/localization-editor.scss#L33

should be completed at the same time as https://github.com/SAP/fundamental-styles/issues/36 to solve all issues (including hover and focus states).
