### ISSUE TITLE
Input Group Button Hover Border

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-styles#1195]
There is additional border on button hover inside input group
![image](https://user-images.githubusercontent.com/26483208/86119745-4c592d80-bad3-11ea-80fd-5d4ec5f3fc86.png)

**Comment by mikerodonnell89** [comment]
I think this issue is no longer relevant - I am seeing on chrome some default browser stylesheet added to the "click me" buttons, this PR could fix it: https://github.com/SAP/fundamental-styles/pull/1330 but i think this is probably not necessary
