### ISSUE TITLE
Button is broken

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1237]
- [x] Menu button #1252
<img width="272" alt="Screen Shot 2020-07-10 at 7 16 07 PM" src="https://user-images.githubusercontent.com/4380815/87209958-d8443400-c2e1-11ea-88a6-b5a7bd6a08a0.png">

 - [x] Split Menu Button #1252
<img width="169" alt="Screen Shot 2020-07-10 at 7 16 30 PM" src="https://user-images.githubusercontent.com/4380815/87209970-e2fec900-c2e1-11ea-9983-6322a714f75e.png">

- [ ] Segmented Button in Popover 
<img width="215" alt="Screen Shot 2020-07-11 at 5 09 18 PM" src="https://user-images.githubusercontent.com/4380815/87233866-5e6f8180-c399-11ea-8daa-6f568c8bfcf5.png">

**Comment by rengare** [comment]
@droshev Segmented button in popover looks that it works
![image](https://user-images.githubusercontent.com/10849982/87409187-e71e3580-c5c4-11ea-960b-6397415176be.png)
