### ISSUE TITLE
website new design

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#125]
The idea is to create a new (shared) design for 4 libraries:
- `fundamental-styles`
- `fundamental-ngx`
- `fundamental-react`
- `fundamental-vue`
An option for the 4th doc websites is to share the same design but have slightly different colors. 
A nice touch could be an pption to reflect the branding color of each library. `So Angular is red, React is blue, Vue is green.`

Here are some requirements:
- Landing page (listing all the 4 libraries)
- artifacts will be grouped in different section (similar to the current ones)
- left navigation
- main content
- (right page navigation)
- each component doc page will /might have 
  - description, overview, general documentation
  - option to show components in LTR and RTL mode
  - API/properties (e.g. https://sap.github.io/fundamental-ngx/alert/api\)
![Screen Shot 2019-06-23 at 7 54 17 AM](https://user-images.githubusercontent.com/4380815/59975928-20d06880-958c-11e9-82e4-4821742b9958.png)
  - examples(code snippet and how the code will be interpreted by the browser). The snippets could be multiple files. For instance, there could be a typescript file which is combined with an html file and a css file. These should all be separated. We can offer `Copy` functionality so the user can copy the code in their clipboard. Maybe options for collapse/expand of the code
  - playground

It would be great to go over all the documentation websites and see what features there are.
- https://sap.github.io/fundamental-styles/
- https://sap.github.io/fundamental-ngx/home
- https://sap.github.io/fundamental-react/home
- https://sap.github.io/fundamental-vue/

**Comment by MattL75** [comment]
Code examples need a nice way of displaying multiple files.

We had also talked about branding each documentation with a specific color for each library. So Angular is red, React is blue, Vue is green. We can raise the specific hex codes.

**Comment by saad-mo** [comment]
For code snippet 
 - copy code button
 - toggle background, RTL
 - expand/collapse for code when it is too long.

**Comment by MattL75** [comment]
@saad-mo In my opinion the code should always be collapsed initially, with a button expanding it (and then showcasing the different files, allowing users to switch between them). Similar to Material's approach would be nice.

**Comment by LeoT7508** [comment]
@droshev 

This needs to be assigned to you, we are still waiting on content from you for the home page.

**Comment by droshev** [comment]
@LeoT7508  Perfect, what kind of content do you need exactly?

**Comment by ChristianKienle** [comment]
<img width="575" alt="Screenshot 2019-07-24 at 21 44 52" src="https://user-images.githubusercontent.com/153225/62106223-fe292200-b2a4-11e9-91da-063ab7d7f85e.png">

Fundamental Vue has a `Run`-button that, when pressed, will launch the corresponding example is a code sandbox which allows you to run and edit the example.

**Comment by ChristianKienle** [comment]
In Fundamental Vue the components are documented using Markdown (API documentation is generated automatically). If you write – for example:

```
The `fd-calendar` component is usually …
```
the documentation system will automatically replace 

```
`fd-calendar`
```

with a link to the corresponding API documentation.

![Screenshot 2019-07-30 at 08 36 53](https://user-images.githubusercontent.com/153225/62106295-3466a180-b2a5-11e9-8eab-7b3ff9962b90.png)

This means that there should also be some kind of way to view/link to the API documentation of individual components.

**Comment by ChristianKienle** [comment]
![Screenshot 2019-07-30 at 08 40 47](https://user-images.githubusercontent.com/153225/62106536-bfe03280-b2a5-11e9-9eb8-12afacfd4f61.png)

![Screenshot 2019-07-30 at 08 41 03](https://user-images.githubusercontent.com/153225/62106548-c9699a80-b2a5-11e9-98cf-2993c51ee2a1.png)

You can also run each Example in Full Screen by clicking on the Full Screen button. This is highly useful to quickly see the generated HTML and is also nice for debugging.

Some components only really make sense when being displayed full screen: `fd-shell` is such a component. For those kind of components Fundamental Vue does not show the rendered example but just a big Full Screen button.

Btw: `fd-shell` is still buggy. :D

**Comment by droshev** [comment]
@LeoT7508 do you need more input?

**Comment by LeoT7508** [comment]
@droshev 

We still need information for these 2 areas. They were action items for you on our call last week. 

<img width="1345" alt="Screen Shot 2019-07-30 at 10 28 19 AM" src="https://user-images.githubusercontent.com/28761982/62142988-df328c00-b2b4-11e9-948b-1027ac94ab43.png">
<img width="1026" alt="Screen Shot 2019-07-30 at 10 28 26 AM" src="https://user-images.githubusercontent.com/28761982/62142995-e2c61300-b2b4-11e9-9c91-330590cd1a7c.png">

**Comment by droshev** [comment]
@LeoT7508 how is this blocking the design?
1. What is new will change very often 
2. we will collect some testimonials and we can keep adding new ones

**Comment by LeoT7508** [comment]
@droshev 

We had a call about this, if we don't have information you will have a blank page. If we don't have this information you will have half a home page. We can leave it blank for now, that will be your call, we can leave it as an open task for you to complete when you have time. The design templates for all the pages are completed based off our call last week.

**Comment by droshev** [comment]
@LeoT7508 the content of those sections will be dynamic
but if you want to add something(for what is new) then you can look in each library release notes (e.g. https://github.com/SAP/fundamental-ngx/releases)
