### ISSUE TITLE
Update how-to-use-scss.md

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#126]
`how-to-use-scss.md` is outdated and need to be updated.
Example the section `ANGULAR COMPONENTS` points to wrong paths.

**Comment by sunnyyadav100** [comment]
As `https://sap.github.io/fundamental/` is marked for deprecation. `fundamental-styles` should provide SCSS files to import and override the existing styles to Fiori.

**Comment by droshev** [comment]
@sunnyyadav100 `fundamental-styles` is under serious refactoring. We decided not to publish the files that will go under a serious refactoring and breaking changes. There are some features such as colors won't be supported the same way as `fundamental` as `fundamental-styles` is not an owner.
We are thinking what part of `SCSS` to expose and we will share an update soon.
I will close the issue but you can keep an eye.
