### ISSUE TITLE
Investigate if we can improve our doc site performance

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#1262]
Storybook is super slow vs. old documentation. We need to investigate if performance could be improved.

Ideas

- Check imports of style files
- Check if there is other way to render everything
- Enable lazy loading, it seems like everything is loaded in first entry.
- Maybe replace iframes by static files
- compare with https://sap.github.io/ui5-webcomponents-react

**Comment by droshev** [comment]
It is very slow on IE11

**Comment by widra** [comment]
Missing function: copy to clipboard the html examples.

**Comment by droshev** [comment]
The performance was addressed with #1327
