### ISSUE TITLE
Visual Defect Hunting - July 15, 2020

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1263]
- [x] Input - https://github.com/SAP/fundamental-styles/pull/1265
<img width="1102" alt="Screen Shot 2020-07-15 at 5 26 20 PM" src="https://user-images.githubusercontent.com/4380815/87597757-575db180-c6c0-11ea-8c74-a1e64e9ec5dc.png">

- [x] Page - most probably the same as the Input - https://github.com/SAP/fundamental-styles/pull/1265
Before: 
<img width="1792" alt="Screen Shot 2020-07-15 at 5 22 44 PM" src="https://user-images.githubusercontent.com/4380815/87597579-0a79db00-c6c0-11ea-9d11-d711a14767d6.png">

After: 
<img width="1636" alt="Screen Shot 2020-07-15 at 5 22 57 PM" src="https://user-images.githubusercontent.com/4380815/87597594-106fbc00-c6c0-11ea-8613-93d1808e85af.png">

- [x] Checkbox - https://github.com/SAP/fundamental-styles/pull/1264
<img width="426" alt="Screen Shot 2020-07-15 at 5 28 52 PM" src="https://user-images.githubusercontent.com/4380815/87597939-aefc1d00-c6c0-11ea-8496-1b01430a2772.png">

- [x] Shellbar buttons - https://github.com/SAP/fundamental-styles/pull/1266
before:
<img width="178" alt="Screen Shot 2020-07-15 at 7 48 53 PM" src="https://user-images.githubusercontent.com/4380815/87610783-4dde4480-c6d4-11ea-9b66-7446f5089e4c.png">
<img width="242" alt="Screen Shot 2020-07-15 at 7 48 49 PM" src="https://user-images.githubusercontent.com/4380815/87610785-4dde4480-c6d4-11ea-9bd2-23a9d23c55c6.png">
After
<img width="173" alt="Screen Shot 2020-07-15 at 7 50 04 PM" src="https://user-images.githubusercontent.com/4380815/87610819-664e5f00-c6d4-11ea-8581-2bdd11ee3392.png">
<img width="170" alt="Screen Shot 2020-07-15 at 7 50 01 PM" src="https://user-images.githubusercontent.com/4380815/87610821-664e5f00-c6d4-11ea-82eb-b6886b8b0060.png">

Before:
<img width="79" alt="Screen Shot 2020-07-15 at 7 51 37 PM" src="https://user-images.githubusercontent.com/4380815/87610904-a877a080-c6d4-11ea-8041-217e14b9f09b.png">
After:
<img width="93" alt="Screen Shot 2020-07-15 at 7 51 43 PM" src="https://user-images.githubusercontent.com/4380815/87610913-ad3c5480-c6d4-11ea-938c-078a08cc2534.png">

**Comment by InnaAtanasova** [comment]
> * Input
> 
> <img alt="Screen Shot 2020-07-15 at 5 26 20 PM" width="1102" src="https://user-images.githubusercontent.com/4380815/87597757-575db180-c6c0-11ea-8c74-a1e64e9ec5dc.png">
> 

This is the `align-self: flex-start;` fix we added. Was too good to be true :(

**Comment by droshev** [comment]
New issues:

- [ ] Time picker
Before(headers are centered)
<img width="221" alt="Screen Shot 2020-07-16 at 8 38 47 PM" src="https://user-images.githubusercontent.com/4380815/87735772-759cdd80-c7a4-11ea-9c04-b3bd91739ce4.png">
