### ISSUE TITLE
Update Calendar styling

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-styles#1277]
**Describe the bug**
This is as enhancement.

Calendar has been recently updated by the designers. On of the changes is the layout in mobile landscape view:
From:
![image](https://user-images.githubusercontent.com/17496353/87928727-8fc90b00-ca85-11ea-84a8-785f8e73c47d.png)

To:
![image](https://user-images.githubusercontent.com/17496353/87928779-a2dbdb00-ca85-11ea-9ab2-4af9708e6ae8.png)

But there might be more.

**Comment by droshev** [comment]
@salarenko can you document all the changes you found?
