### ISSUE TITLE
LayoutColumn  (col)didn't support the screen which smaller than 600px

### ISSUE THREAD

**Issue by Vita-Meow** [SAP/fundamental-styles#1280]
**Describe the bug**

> Is this issue related to a specific component?
Yes, LayoutColumn
> What version of the Fundamental Library Styles are you using?
Latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
ASAP , with many thanks.

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
React

**To Reproduce**
1. Go to the page used LayoutColumn;
2. Resize screen that smaller than 600px
3. then didn't has any style about columns that apply to this condition

**Expected behavior**
except has the breakpoint to handling the screen size that smaller than 600px

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Vita-Meow** [comment]
For example :

xs | screen < 576px and also default setting, could be a span value or an object containing above props | number \| object | - |  
-- | -- | -- | -- | --
sm | screen ≥ 576px, could be a span value or an object containing above props | number \| object | - |  
md | screen ≥ 768px, could be a span value or an object containing above props | number \| object | - |  
lg | screen ≥ 992px, could be a span value or an object containing above props | number \| object | - |  
xl | screen ≥ 1200px, could be a span value or an object containing above props | number \| object | - |  
xxl | screen ≥ 1600px, could be a span value or an object containing above props |   |   |

**Comment by droshev** [comment]
@Vita-Meow we are in process of refactoring the grid - look at PR #889

**Comment by Vita-Meow** [comment]
> #889
@droshev 
Thank you, I have checked this PR, I think it is good enough for me now, since it has the default `col -n` css rules . Even if it hasn't match any media query case, it will has the proper logic

**Comment by droshev** [comment]
@Vita-Meow We are on the final phase of merging #889 .

Can you share more information what you are building?

**Comment by droshev** [comment]
@Vita-Meow can you check whether the latest version of the library is good for you. If not could you open a new issue?
