### ISSUE TITLE
Support rendering custom elements in dropdown for Select

### ISSUE THREAD

**Issue by Vita-Meow** [SAP/fundamental-styles#1281]
**Is your feature request related to a problem? Please describe.**

> Is this issue related to a specific component?

Select

> What browser are you working in?

all

> What version of Fundamental Library Styles are you using?

latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
React

**Describe the solution you'd like**
https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Fant.design%2Fcomponents%2Fselect%2F

**Describe alternatives you've considered**

**Additional context**

**Comment by Vita-Meow** [comment]
For example: https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Fant.design%2Fcomponents%2Fselect%2F

**Comment by droshev** [comment]
@Vita-Meow The links are empty for me

**Comment by Vita-Meow** [comment]
Ah~ sorry , Can you check this https://ant.design/components/select/, and there is a custom dropdown here, thank you ~

**Comment by droshev** [comment]
Hi @Vita-Meow, thank you for answering the questions.
If you use fundamental-styles then you have all the freedom to use custom items in the select:
![Screen Shot 2020-07-22 at 9 45 12 AM](https://user-images.githubusercontent.com/4380815/88184025-376a4880-cc00-11ea-8f11-d9bfb079b04f.png)

If you are using Fundamental React then can you open an issue there? https://github.com/SAP/fundamental-react/issues

**Comment by Vita-Meow** [comment]
> https://github.com/SAP/fundamental-react/issues

yes,  we are using fundamental react now, will  do, thank you~

**Comment by droshev** [comment]
@Vita-Meow Can you try with the latest version? Could you report a new ticket if you face more issues?
