### ISSUE TITLE
Resizable Dialogs on Touch Devices

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1314]
Currently, dialogs are only resizeable on desktop. There is no possibility to resize them on touch devices.
This task is about evaluating this option and also about how should this work - just enlarge the resize handler?
<img width="396" alt="Screen Shot 2020-07-31 at 7 43 38 PM" src="https://user-images.githubusercontent.com/4380815/89088414-263edb80-d366-11ea-9e16-854e5bed2a07.png">

**Comment by InnaAtanasova** [comment]
Should a Dialog be resizable in mobile mode? The UX guidelines specify: "We recommend displaying dialogs in S size in full screen mode to help users focus on the content of the dialog". I think we need to reach first the designers and the UX people before grooming this issue.
