### ISSUE TITLE
Visual issue: Table Semantic Rows 

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#1328]
When the row is selected, the background color should turn from white to active color: 
https://wiki.wdf.sap.corp/wiki/display/visualcore/Table+%28Fiori+3%29+-+Highlight+Row
<img width="989" alt="Screen Shot 2020-08-04 at 10 02 50 PM" src="https://user-images.githubusercontent.com/54589269/89373867-a33bbf00-d69e-11ea-9a6d-c4b478b91c07.png">

The background didn't change in Styles:
<img width="1007" alt="Screen Shot 2020-08-04 at 10 06 08 PM" src="https://user-images.githubusercontent.com/54589269/89373895-b77fbc00-d69e-11ea-835e-a76729522c66.png">

**Comment by droshev** [comment]
@estelaxu3 you are right. We show only static examples. We don't have a combination of semantic row and selection but I assume we are good. Here is an example with a selected [row](https://fundamental-styles.netlify.app/?path=/docs/components-table--primary#with-checkbox)
