### ISSUE TITLE
List :Item Counter styles are required as per fiori3

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1333]
**Is your feature request related to a problem? Please describe.**
Item counter styles have to be created as per Fiori3 standards.

> Is this issue related to a specific component?
List

> What version of Fundamental Library Styles are you using?
0.11

**Comment by droshev** [comment]
@sKudum could you share a screenshot?

**Comment by sKudum** [comment]
<img width="676" alt="Screenshot 2020-12-11 at 12 08 50 PM" src="https://user-images.githubusercontent.com/53487468/101871482-a47b7c00-3ba9-11eb-9ad5-0422dfdbaa64.png">

**Comment by droshev** [comment]
will be tackled as part of [#2063](https://github.com/SAP/fundamental-styles/issues/2063)
