### ISSUE TITLE
List - Interactive States -Active/down state is not present for  non actionable item

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1334]
**Describe the bug**
Active/down state styles are not getting displayed on List styles on nonactionable items.

Nonactionable List

![Nonactionablelist (1)](https://user-images.githubusercontent.com/53487468/89535801-8a551a00-d814-11ea-90a4-3bdf3e6cbace.gif)

Actionable List

![Actionable List (1)](https://user-images.githubusercontent.com/53487468/89535693-6560a700-d814-11ea-8878-d05da2999025.gif)

> Is this issue related to a specific component?
List

> What version of the Fundamental Library Styles are you using?
0.11

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**Expected behavior**
Interactive states should match fiori3
<img width="262" alt="Screen Shot 2020-08-06 at 3 15 40 PM" src="https://user-images.githubusercontent.com/53487468/89517705-ba41f480-d7f7-11ea-86a6-6964b3a725b6.png">

**Comment by droshev** [comment]
@sKudum is this still valid issue?

**Comment by sKudum** [comment]
Hi @droshev , Yes please

![2020-12-11_12-06-02 (1)](https://user-images.githubusercontent.com/53487468/101871315-5cf4f000-3ba9-11eb-89b3-69917bece0a3.gif)

**Comment by droshev** [comment]
will be tackled as part of [#2063](https://github.com/SAP/fundamental-styles/issues/2063)
