### ISSUE TITLE
Test-update command generates Button-snap.png file

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-styles#1339]
**Describe the bug**
Running `npm run test:update` generates Button-snap.png

**Generated file**
![Button-snap](https://user-images.githubusercontent.com/3263744/89632771-714b7800-d8ab-11ea-86ac-7f91f0868e76.png)

> Is this issue related to a specific component?
No
> What version of the Fundamental Library Styles are you using?
  "version": "0.11.3-rc.14",

**To Reproduce**
1. Go to project root
2. run `npm run test:update`
4. See that new `Button-snap.png` has been generated.

**Expected behavior**
`npm run test:update` should generate snapshots only for newly created components not for existed one.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by droshev** [comment]
we fixed that
