### ISSUE TITLE
Remove is-disabled class from the components

### ISSUE THREAD

**Issue by SaiShan** [SAP/fundamental-styles#135]
Unify the usage of disabled/required/read-only elements:
use classes:
- `is-disabled`
- `is-required`
- `is-read-only`
- `selected`

What would not be classes but use pseudo-selectors:
- `:focus`
- `:active`
- `:hover`
- `:visited`

**Comment by droshev** [comment]
it is not needed at the moment. Let's open a new issue if this request emerges
