### ISSUE TITLE
Better selector definitions for block-level classes

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-styles#138]
There are some components that use the following syntax to define base styles for its component:
```scss
$block: #{$fd-namespace}-identifier;

@at-root {
    [class*="#{$block}"] {
        // style definitions go here
    }
}
```

Selectors like this can be considered a performance issue.  See https://github.com/csslint/csslint/wiki/disallow-selectors-that-look-like-regular-expressions for more information.

Instead, these base styles should be tied to a base class selector.  Using the example above, it should look like this:
```scss
$block: #{$fd-namespace}-identifier;

.#{$block} {
    // style definitions go here
}
```

This will require the markup specs to change.  Currently, elements for these components don't specify a base class -- they only specify the extensions of it and then rely on the attribute regex selector to apply the base styles.

**Comment by droshev** [comment]
it is only for columns for now - let's close and see whether there will be new components in the future
