### ISSUE TITLE
Rating indicator: It's needed to find a way to support different style rules based on a theme.

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-styles#1394]
Rating indicator has different style rules based on a theme.

Differences:
- Interactive
  - Selected icon opacity on hover for `Light` vs `Dark`.
  - Selected icon colour for `HCB` vs `HCW`.
- Display Only
  - Selected icon colour for `Light/Dark` vs `HCB/HCW` themes.
- Disabled
  - apply opacity only for `Light/Dark`,  
  - apply colour only for `HCB/HCW`.

**Comment by droshev** [comment]
@katekozlowska could you handle this as part of the delta theming?

**Comment by droshev** [comment]
it will be addressed as part of #1357
