### ISSUE TITLE
Link component needs to change underline styling

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-styles#142]
Currently, the link component (`.fd-link`) is not using `text-decoration` for the underline, but rather a bottom border.  The biggest problem with that is this will change the dimensions of links, which makes them difficult to put inline in a block of text or in other components.

**Comment by salarenko** [comment]
Issue has been fixed. `Link` component uses `text-underline`:

![image](https://user-images.githubusercontent.com/17496353/73943160-922d1380-48f0-11ea-8132-bfc5ff4bb96b.png)

https://sap.github.io/fundamental-styles/components/link.html
