### ISSUE TITLE
Defect Hunting 0.12.0

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1433]
- [x] Button not inverted on RTL - Wrong Icon - https://github.com/SAP/fundamental-styles/pull/1694
![image](https://user-images.githubusercontent.com/26483208/92732713-1bb92e00-f377-11ea-84c4-20a44d74ffde.png)

- [x] Breadcrump iframe Height with opened popover - https://github.com/SAP/fundamental-styles/pull/1694
![image](https://user-images.githubusercontent.com/26483208/92733036-7f435b80-f377-11ea-8e92-633266cc3829.png)

- [x] empty checkbox focus double outline (example form cards with table) - https://github.com/SAP/fundamental-styles/pull/1662
![image](https://user-images.githubusercontent.com/26483208/92733213-b7e33500-f377-11ea-83fb-e601e40c72b0.png)

- [x] Form Grid - Inputs/Labels got redundant ID/for attributes - Jedrzej

- [x] Form Messages - Popovers don't open - https://github.com/SAP/fundamental-styles/pull/1694

- [x] Feed Input - button - https://github.com/SAP/fundamental-styles/pull/1694
![image](https://user-images.githubusercontent.com/26483208/92918653-ea506900-f42f-11ea-950b-99b59412d550.png)

- [ ] Feed input - RTL button
![image](https://user-images.githubusercontent.com/26483208/92918718-f9371b80-f42f-11ea-9697-e69c82408a2f.png)

- [x] File Uploader - Doesn't react on click, brings console error - https://github.com/SAP/fundamental-styles/pull/1694

- [x] Generic Tile - actions - https://github.com/SAP/fundamental-styles/pull/1698
![image](https://user-images.githubusercontent.com/26483208/92918955-2b487d80-f430-11ea-91a4-82b4214a79bb.png)

- [x] List - checkboxes - Repeated ID/For attributes on RTL [#1693](https://github.com/SAP/fundamental-styles/pull/1693)

- [x] Side Navigation - nested list button with multiple focus outlines [#1691](https://github.com/SAP/fundamental-styles/pull/1691)
![image](https://user-images.githubusercontent.com/26483208/93889300-51e89d00-fce9-11ea-8a8c-78d345a37340.png)

**Comment by salarenko** [comment]
- [ ] Avatar in object card example
![image](https://user-images.githubusercontent.com/17496353/94011940-6770cc00-fda8-11ea-95a2-2c78ea33254b.png)

**Comment by stefanoScalzo** [comment]
- [ ] Cozy Side Navigation Icon Active Underline
![Screen Shot 2020-09-23 at 10 45 19 AM](https://user-images.githubusercontent.com/50607147/94030061-63828100-fd8b-11ea-9ed8-9553cc50c8bc.png)

- [ ] Complex Cozy Side Nav focus 
![Screen Shot 2020-09-23 at 10 57 50 AM](https://user-images.githubusercontent.com/50607147/94030334-b0665780-fd8b-11ea-89b0-e580cff32672.png)

**Comment by JKMarkowski** [comment]
- [ ] Form Message - IE11
![image](https://user-images.githubusercontent.com/26483208/94126135-85e1d080-fe57-11ea-8303-0b63cb79610f.png)

**Comment by droshev** [comment]
@stefanoScalzo Can you convert the issues we didn't solve in separate issues?
