### ISSUE TITLE
Implement Card Group Container in ngx-core

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-styles#1460]

**Comment by manjunathanagaraj** [comment]
Moving to sprint 46.
Expected date of PR merge: September 25.

**Comment by manjunathanagaraj** [comment]
https://github.com/SAP/fundamental-ngx/pull/3341 - pr review in progress. Moving to Sprint 47

**Comment by DeepakSap14** [comment]
ngx-core implementation is merged with PR #3341
