### ISSUE TITLE
Docs: example containers too small: Select, ContextualMenu

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-styles#1461]
![Screen Shot 2020-08-26 at 9 50 06 AM](https://user-images.githubusercontent.com/29607818/91332821-98e28180-e781-11ea-94ed-0e33a328d601.png)

**Comment by jbadan** [comment]
![Screen Shot 2020-08-26 at 9 55 47 AM](https://user-images.githubusercontent.com/29607818/91333353-5b322880-e782-11ea-91f2-2f7182b9499d.png)

**Comment by droshev** [comment]
it looks like it has been addressed/resolved
