### ISSUE TITLE
Docs: ActionBar: first RTL example has button arrow icon facing wrong direction

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-styles#1463]
![Screen Shot 2020-08-26 at 9 57 08 AM](https://user-images.githubusercontent.com/29607818/91333622-ab10ef80-e782-11ea-8363-81e233616b26.png)

versus:

![Screen Shot 2020-08-26 at 9 57 14 AM](https://user-images.githubusercontent.com/29607818/91333678-bc59fc00-e782-11ea-91cb-2ff53ff2f880.png)

**Comment by stefanoScalzo** [comment]
This is more of a markup thing that should be triggered on the ngx/react side because it's the actual class that's changing. We have the same issue with tree. What do you think ? @droshev

**Comment by droshev** [comment]
we removed the RTL examples so the application needs to reverse the icon
