### ISSUE TITLE
Thumbnail Image - define technical specs for ngx-platform

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-styles#1484]

**Comment by droshev** [comment]
@manjunathanagaraj i am not sure whether there is such a component in Fiori 3. I think we agreed not to create it in fundamental and keep it internal?

**Comment by manjunathanagaraj** [comment]
Technical spec will be presented 14Sep. 
Moving it to Sprint 46.

**Comment by manjunathanagaraj** [comment]
Tech spec was presented, will be a component in platform.
