### ISSUE TITLE
List Report with Side Filter Panel - define tech spec for styles

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-styles#1500]

**Comment by manjunathanagaraj** [comment]
This task will be considered based on further analysis. For now its tbd.

**Comment by KevinOkamoto** [comment]
Tech doc created for List Report Page is here:
https://app.gitbook.com/@fundamental-styles/s/docs/new-component-list-report-page

It is ready to be reviewed.

**Comment by KevinOkamoto** [comment]
The "Side Filter Panel" is referred to in Fiori as "Dynamic Side Content". I will write a tech spec for "Dynamic Side Content" and link it to this issue.

**Comment by KevinOkamoto** [comment]
Tech doc for "Dynamic Side Content" is here:
https://app.gitbook.com/@fundamental-styles/s/docs/new-component-dynamic-side-content

**Comment by manjunathanagaraj** [comment]
Closing it as per above comments.
