### ISSUE TITLE
Checkbox: visual indication on finger down

### ISSUE THREAD

**Issue by boghyon** [SAP/fundamental-styles#151]
Neither Fiori 2 nor 3 specifies how the checkbox should behave when user puts their finger down on the checkbox. See HTML "native" checkbox vs. Fiori 3 checkbox: https://output.jsbin.com/gitetak

It would be nice if there is some visual feedback on _finger down_ too.

## Motivation

Many checkboxes in different platforms provide instant feedback on finger down. For example, on Windows:

|  | Before / hover | Finger down | Finger up |
| -------------:|:-------------:|:-------------:|:-------------:|
| Chromium<br>browsers | ![Checkbox unchecked hover](https://user-images.githubusercontent.com/12143247/135450502-fd23ed44-e2d6-4fcf-ac92-65d3debaafd6.png) | ![Checkbox unchecked fingerdown](https://user-images.githubusercontent.com/12143247/135450729-2a10a9f1-5b5f-42bd-8ff5-b252272a40da.png) | ![Checkbox checked hover](https://user-images.githubusercontent.com/12143247/135450631-011af325-a38f-4297-857d-feb8c3170191.png) |
| Legacy Edge<br><sup>(EdgeHTML)</sup> | ![IE,Edge-checkbox-initial](https://user-images.githubusercontent.com/12143247/60586266-02d7e480-9d92-11e9-850e-9d57d974a737.gif) | ![IE,Edge-checkbox-finger-down](https://user-images.githubusercontent.com/12143247/60586265-02d7e480-9d92-11e9-90af-e876f6ba85f7.gif) | ![IE,Edge-checkbox-checked](https://user-images.githubusercontent.com/12143247/60586264-02d7e480-9d92-11e9-9c35-c9ec02c567f1.gif) |
| Firefox | ![FF - Checkbox unchecked hover](https://user-images.githubusercontent.com/12143247/135452344-15165cd7-8b0f-4a1b-b92b-9ee46ac484ae.png) | ![FF - Checkbox unchecked fingerdown](https://user-images.githubusercontent.com/12143247/135452379-5110525f-601d-4cd4-ab79-9d6ea5c1b806.png) | ![FF - Checkbox checked hover](https://user-images.githubusercontent.com/12143247/135452404-7af686cd-c3d1-48e3-b304-038198782ac1.png) |
| Material<br><sup>[demo](https://material-components.github.io/material-web/demos/checkbox/)</sup>| ![material-components-checkbox-initial](https://user-images.githubusercontent.com/12143247/60586690-da041f00-9d92-11e9-8628-07eee451cec8.gif) | ![material-components-checkbox-finger-down](https://user-images.githubusercontent.com/12143247/60586689-da041f00-9d92-11e9-804f-21c6b7361a7a.gif) | ![material-components-checkbox-checked](https://user-images.githubusercontent.com/12143247/60586688-da041f00-9d92-11e9-9941-9d4065152c3b.gif) |

Fiori apps, however, currently don't:

|  | Before / hover | Finger down | Finger up |
| -------------:|:-------------:|:-------------:|:-------------:|
| Fiori 3 | ![Fiori-checkbox-initial](https://user-images.githubusercontent.com/12143247/60587756-8941f580-9d95-11e9-81a2-7381ddda0321.gif) | ![Fiori-checkbox-initial](https://user-images.githubusercontent.com/12143247/60587756-8941f580-9d95-11e9-81a2-7381ddda0321.gif) | ![Fiori-checkbox-checked](https://user-images.githubusercontent.com/12143247/60587757-8941f580-9d95-11e9-9029-4ca3ba067a3f.gif) |

This leads to:

 * users experiencing unexpected behavior compared to other applications
 * users becoming insecure:
   + when keeping the finger down / long-press --> "Am I actually clicking this element? Or is the system not responding?" (no snappy experience)
   + when keeping the finger down but moving away from the element to cancel the action, then coming back **not** to cancel --> "wait, which one of the checkboxes was I looking at?" (no indication, makes them to think)
 * but most importantly, **perceived lag:**
 According to the measurements (using the devtools and my laptop with a touchpad), time between `mousedown` and the paint event after `mouseup` takes around 160 ms or more.
Users usually perceive lag starting at 100 ms.[^1] Since "nothing is happening" within 100 ms, the checkbox _feels_ slow.

I use and develop UI5 applications. The lack of snappy visual response in various controls (e.g. in checkbox as described above) makes the control feel slow (which is the real performance users care about) in **addition** to already poor control performance due to heavy use of JS in the UI- / main-thread of the browser.
 
What do you think? Would you agree that this "feature" request could improve the actual perceived performance?

[^1]: According to the _Platform Success Model_ by Blink devs. See [[doc]](https://docs.google.com/document/d/1bYMyE6NdiAupuwl7pWQfB-vOZBPSsXCv57hljLDMV8E/edit?usp=sharing) or [[vid]](https://youtu.be/Ku3znd7JNIk?t=1315)

**Comment by boghyon** [comment]
PS: As I don't work for SAP, I don't have access to the latest Fiori 3 spec or any internal discussions, This is a general feedback on the checkbox component.

Is this the right place to give feedback on Fiori 3 at all? And what's the difference between [_fundamental_](https://github.com/SAP/fundamental) and this _[fundamental-style](https://github.com/SAP/fundamental-styles)_ repo?

**Comment by boghyon** [comment]
Discussion linking to this issue: https://experience.sap.com/topic/checkbox-not-responding-on-finger-down/

**Comment by boghyon** [comment]
Btw. the same applies to other controls such as **radio button**. I wish more controls could visually indicate immediately on finger down (click or tap) in order to improve consistency across the web platform and to reduce the perceived lag due to the missing feedback

**Comment by boghyon** [comment]
Hi @InnaAtanasova, was there any progress?

**Comment by boghyon** [comment]
Generalized title since checkbox is not the only affected control.

**Comment by i556484** [comment]
JIRA: FIORITECHE1-8371
