### ISSUE TITLE
shellbar margin support per screen size 

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1542]
The shell bar design spacing has been changed. We need to incorporate those changes
![Screen Shot 2020-08-31 at 5 53 53 PM](https://user-images.githubusercontent.com/4380815/91772524-042db880-ebb3-11ea-9aa7-4772ba330fbe.png)

**Comment by JKMarkowski** [comment]
Shellbar should be refactored 
![image](https://user-images.githubusercontent.com/26483208/92244346-0e0d2f80-eec3-11ea-90c3-9e683065924b.png)
Current in fundamental-styles code view of shellbar depends on media queries, this should be changed to `--s/m/l/xl` modifiers
