### ISSUE TITLE
FormInput disabled cursor

### ISSUE THREAD

**Issue by markoromandic** [SAP/fundamental-styles#1560]
### Description
When FormInput is disabled, and you hover over it. Cursor is changed to pointer. Tried to change it, but not successfully. 

### Versions
**fundamental-react:**
v0.8.1
---

_**NOTE:** Where applicable, please include uncropped screen captures._
![image](https://user-images.githubusercontent.com/15128279/79892645-23e1f280-8403-11ea-9410-afeace8ea361.png)

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by droshev** [comment]
I think it is fixed already. Feel free to open a new issue if you still face the same issue
