### ISSUE TITLE
Selection list with simple list item

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-styles#1588]
**Describe the bug**
Currently there is no way to create a simple list with selection feature (marking list items as selected).
This is because of `is-selected` styling works only when used inside `fd-list--selection`, which automatically creates spacers for checkbox and radio-button.

**Expected behavior**
Following markup resulting in:
```
<ul class="fd-list">
  <li class="fd-list__item">
      <span class="fd-list__title">List item 1</span>
  </li>
  <li class="fd-list__item is-selected">
      <span class="fd-list__title">List item 2</span>
  </li>
  <li class="fd-list__item">
      <span class="fd-list__title">List item 3</span>
  </li>
</ul>
```
![image](https://user-images.githubusercontent.com/17496353/92396038-a0603e00-f124-11ea-8e60-9a3597f6202e.png)

Currently the result is:
![image](https://user-images.githubusercontent.com/17496353/92396184-e61d0680-f124-11ea-95f7-86f1f7256e79.png)

**Comment by droshev** [comment]
will be tackled as part of [#2063](https://github.com/SAP/fundamental-styles/issues/2063)
