### ISSUE TITLE
Delete icon position is not middle in standardlist with byline

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1590]
In standard list with byline and the position of button, it is not vertically aligned in middle.

**To Reproduce**
1).add action buttons such as delete , edit to standard list with a byline, and check the position of the button, it is not vertically aligned in middle.

**Expected behavior**
Action buttons should be vertically aligned in middle as per fiori guidelines.

**Screenshots**
<img width="1125" alt="2020-09-09_17-57-51" src="https://user-images.githubusercontent.com/53487468/92598587-a130d580-f2c6-11ea-800c-0e845d9c2846.png">

Sample code used to place button.
<img width="664" alt="2020-09-09_17-58-12" src="https://user-images.githubusercontent.com/53487468/92598644-b6a5ff80-f2c6-11ea-824d-71fd4b117537.png">

**Comment by droshev** [comment]
@sKudum is this still valid?

**Comment by sKudum** [comment]
Hi @droshev , Yes please, it still exsists.

**Comment by droshev** [comment]
will be tackled as part of [#2063](https://github.com/SAP/fundamental-styles/issues/2063)
