### ISSUE TITLE
Object Status Clickable not working in IE and Firefox

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-styles#1593]
**Describe the bug**

this Issues has been raised as part of fundamental ngx issued ID https://github.com/SAP/fundamental-ngx/issues/3086

Object Status Clickable not working in IE and Firefox

> Is this issue related to a specific component?

Object status

Replication steps:
open Fundamental ngx and select Object marker from the Object status, On Hovering the clickable could see that there is underling for icon too.
Issue:
<img width="1443" alt="Screenshot 2020-09-11 at 4 07 04 PM" src="https://user-images.githubusercontent.com/53534379/92914293-217f4400-f449-11ea-90d1-948bca40b395.png">

**Comment by InnaAtanasova** [comment]
Could you provide more information about these deviations from Fiori 3 specs?

**Comment by salarenko** [comment]
@Lokanathan-k Please properly document the issue. Describe how to reproduce the issue ad attach proper gif/img.
I've checked it on Firefox and IE11 and everything works fine.
