### ISSUE TITLE
list Byline is changing its height when bottom border is added

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1596]
**Describe the bug**
Standard list with byline, no border and selection styles applied creates a border-bottom width as shown in the images below. by which we can see slight fluctuations on the screen when the user selects and unselects a borderless standard list with a byline.

> Is this issue related to a specific component?
Standard list byline

> What version of the Fundamental Library Styles are you using?
0.11

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**To Reproduce**
1).Create a list and apply byline and noborder classes.
2).append check box as shown below and check the boder-bottom value , which is causing reflection in screen.

```
<ul class="fd-list fd-list--selection fd-list--no-border fd-list--byline">  
<li role="option" tabindex="0" class="fd-list__item no is-selected">
      <div class="fd-form-item fd-list__form-item">
          <input type="checkbox" class="fd-checkbox" id="Ai4ez6111Z" checked="">
          <label tabindex="-1" class="fd-checkbox__label" for="Ai4ez6111Z"></label>
      </div>
      <span class="sap-icon--activate fd-list__thumbnail"></span>
  </li>
  <li role="option" tabindex="0" class="fd-list__item">
    <div class="fd-form-item fd-list__form-item">
          <input type="checkbox" class="fd-checkbox" id="Ai4ez6112X">
          <label tabindex="-1" class="fd-checkbox__label" for="Ai4ez6112X"></label>
      </div>
    <span class="fd-image--s fd-list__thumbnail" aria-label="Image label" style="background-image: url('https://placeimg.com/400/400/nature');"></span>
    <div class="fd-list__content">
        <div class="fd-list__title" id="O09lk2">List Item With Two-Column Byline</div>
    </div>
  </li>
</ul>
```

**Expected behavior**
On check and uncheck items positions should not fluctuate.

**Screenshots**

<img width="675" alt="Screen Shot 2020-09-10 at 3 02 24 PM" src="https://user-images.githubusercontent.com/53487468/92713517-b0705b80-f378-11ea-8fe2-62de249c79ed.png">

No border and seleted item
<img width="293" alt="Screen Shot 2020-09-10 at 3 02 18 PM" src="https://user-images.githubusercontent.com/53487468/92713445-9d5d8b80-f378-11ea-90ec-ca83a4857779.png">

No border and not selected item
<img width="300" alt="Screen Shot 2020-09-10 at 3 02 06 PM" src="https://user-images.githubusercontent.com/53487468/92713494-a9e1e400-f378-11ea-93cc-66332ebb71b3.png">

**Comment by salarenko** [comment]
@sKudum what do you mean by "fluctation"?

**Comment by sKudum** [comment]
> @sKudum what do you mean by "fluctation"?

fluctuates- li once we select it looks other items below it moved down. once I unselect items below moves up/ or comes back to original position.

**Comment by salarenko** [comment]
So the problem is that list item is changing its height when bottom border is added 😋?
If that's the problem could you change the description of the issue? The problem is very simple but issue description doesn't help.

The problem is visible only when using `fd-list--no-border`, because of the list item height being changed from fixed `5rem` to `100%`.

**Comment by sKudum** [comment]
> So the problem is that list item is changing its height when bottom border is added 😋?
> If that's the problem could you change the description of the issue? The problem is very simple but issue description doesn't help.
> 
> The problem is visible only when using `fd-list--no-border`, because of the list item height being changed from fixed `5rem` to `100%`.

Updated it , hope it is not confusing now.

**Comment by droshev** [comment]
@sKudum is this still valid?

**Comment by sKudum** [comment]
Hi @droshev , Yes please.
![2020-12-11_12-02-00 (1)](https://user-images.githubusercontent.com/53487468/101871031-d3452280-3ba8-11eb-899f-a493d5b9dfaa.gif)

**Comment by droshev** [comment]
will be tackled as part of [#2063](https://github.com/SAP/fundamental-styles/issues/2063)
