### ISSUE TITLE
Form message not aligning with the Fiori 3 specification.

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-styles#1599]
**Describe the bug**

Form message not aligning with the Fiori 3 specification. even after the box shadow property has been implemented as per the spec.

> Is this issue related to a specific component?
Form Message

> What version of the Fundamental Library Styles are you using?
12.0

**Expected behavior**
<img width="922" alt="Screenshot 2020-09-10 at 8 49 29 PM" src="https://user-images.githubusercontent.com/53534379/92754229-41aaf680-f3a8-11ea-82b6-b6b4f71941a5.png">

**Screenshots**
current implementation.
<img width="548" alt="Screenshot 2020-09-10 at 8 44 34 PM" src="https://user-images.githubusercontent.com/53534379/92754389-68692d00-f3a8-11ea-98b5-6bdd7cc1a3b1.png">
<img width="922" alt="Screenshot 2020-09-10 at 8 49 29 PM" src="https://user-images.githubusercontent.com/53534379/92754399-6bfcb400-f3a8-11ea-9482-45495e232a4c.png">

**Additional context**

**Comment by stefanoScalzo** [comment]
The box shadow is on the form-message not popover class
