### ISSUE TITLE
List with icons

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-styles#1681]
When certain items have icons where others do not, all of the list items still align right (as though they had icons) like this:
![Screen Shot 2020-09-21 at 3 59 56 PM](https://user-images.githubusercontent.com/57453945/93815342-cfe27080-fc23-11ea-8b64-1015fab62d1b.png)
![Screen Shot 2020-09-21 at 4 04 55 PM](https://user-images.githubusercontent.com/57453945/93815585-349dcb00-fc24-11ea-8028-22c89e0d5835.png)

Currently, all the examples show that the items without icons shift back left
![Screen Shot 2020-09-21 at 4 02 57 PM](https://user-images.githubusercontent.com/57453945/93815419-ed173f00-fc23-11ea-96ec-ba4e508b6987.png)

**Comment by InnaAtanasova** [comment]
Refactored in #1677
