### ISSUE TITLE
Rating Indicator/Wizard - modifier class name alignment

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1687]
![Screen Shot 2020-09-22 at 5 21 02 PM](https://user-images.githubusercontent.com/4380815/93938949-0db0c900-fcf8-11ea-8253-52c98163fb11.png)

in grid we were using `-sm` `-md` `-lg` - maybe we should align the names

**Comment by salarenko** [comment]
In this case Grid Component is the one that stands out. Other components with size modifiers also use `--xs/s/m/l/xl`
