### ISSUE TITLE
Styles for Menu Item with Icon and Badge

### ISSUE THREAD

**Issue by prsdthkr** [SAP/fundamental-styles#1690]
When menu items that have icons and badge - the bade is truncated at the top

> Is this issue related to a specific component?

Menu with icon and badge

> What version of the Fundamental Library Styles are you using?

0.12.0-rc.64

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

React

**To Reproduce**
1. Go to https://deploy-preview-1215--fundamental-react.netlify.app/?path=/story/component-api-shellbar--dev
2. Click on overflow indicator
3. See Menu Items that have icons and badge - bade is truncated at the top

**Screenshots**
![image](https://user-images.githubusercontent.com/43764832/93969582-0fdb4d80-fd21-11ea-8b20-7f9d7e99ea75.png)

**Expected behavior**
The badge should not be truncated.
![image](https://user-images.githubusercontent.com/43764832/93970961-f5ef3a00-fd23-11ea-9c9e-deee4f3670f2.png)

**Desktop**
 - OS: MacOS
 - Browser: Chrome
 - Version: 85

**Comment by stefanoScalzo** [comment]
From what I see @droshev the menu with icons in fundamental-react  is not using the proper markup?
