### ISSUE TITLE
Bug: Object Status: Object status icon, they still use the old version

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-styles#1692]
Description: Object status icon, they still use the old version

Expected: Object status icon, they should use the new version 
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2057761379

Attached screenshot: old version
![image](https://user-images.githubusercontent.com/32538291/94031574-a1f45c00-fddc-11ea-8dd7-219e13a12721.png)

New version icons
![image](https://user-images.githubusercontent.com/32538291/93990101-59bb4680-fda8-11ea-920c-c8e74a08b8ce.png)

**Comment by droshev** [comment]
@puru-hk the icons you are referring are already presented here https://fundamental-styles.netlify.app/?path=/docs/components-icon--sizes

**Comment by puru-hk** [comment]
@droshev Icon are not as per the new version this is the issue which i found in https://fundamental-styles.netlify.app/?path=/docs/components-icon--sizes

**Comment by puru-hk** [comment]
If you see this https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2057761379 icons are different

**Comment by droshev** [comment]
@puru-hk those are just examples with some icons
