### ISSUE TITLE
Icon - Implement styles

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-styles#1710]
To be assigned to Oleksii Aleksandrov

**Comment by skocharian** [comment]
https://app.gitbook.com/@fundamental-styles/s/docs/icon

**Comment by manjunathanagaraj** [comment]
PR 1778 merging is paused. Need more discussions to proceed further. Therefore removing the milestone assignment.

**Comment by droshev** [comment]
let's close this for now. If needed we can either reopen or create a new one
