### ISSUE TITLE
On touch of multi-select list item non fiori color is highlighted

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1712]
**Describe the bug**
On touch of multi-select list item non fiori color is highlighted

> Is this issue related to a specific component?
list

> What version of the Fundamental Library Styles are you using?
0.12

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

![2020-09-25_20-42-49 (1)](https://user-images.githubusercontent.com/53487468/94284778-7ace9380-ff70-11ea-8558-8a3add770891.gif)

**Comment by droshev** [comment]
will be tackled as part of [#2063](https://github.com/SAP/fundamental-styles/issues/2063)
