### ISSUE TITLE
Cozy Side Nav focus IE

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-styles#1723]
**Describe the bug**
Side nav item focus is weird in IE

**Is this issue related to a specific component?**
Side Navigation

**What version of the Fundamental Library Styles are you using?**
Latest

**Screenshots**
![Screen Shot 2020-09-23 at 10 57 50 AM](https://user-images.githubusercontent.com/50607147/94030334-b0665780-fd8b-11ea-89b0-e580cff32672.png)

**Comment by droshev** [comment]
the component will be refactored and the issue should be addressed there #2255
