### ISSUE TITLE
Focus is weird in tree IE

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-styles#1724]
**Describe the bug**
Tree item focus is weird in IE

**Is this issue related to a specific component?**
Tree

**What version of the Fundamental Library Styles are you using?**
Latest

**Screenshots**
![Screen Shot 2020-09-23 at 1 18 56 PM](https://user-images.githubusercontent.com/50607147/94047009-7606b580-fd9f-11ea-91e7-bae9de4420e4.png)

**Comment by droshev** [comment]
let's close this now and we will see how it goes
