### ISSUE TITLE
Focus on file uploader IE

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-styles#1725]
**Describe the bug**
File uploader item focus is weird in IE

**Is this issue related to a specific component?**
File uploader

**What version of the Fundamental Library Styles are you using?**
Latest

**Screenshots**
![Screen Shot 2020-09-23 at 1 23 30 PM](https://user-images.githubusercontent.com/50607147/94047422-1230bc80-fda0-11ea-8879-96d4c097cb46.png)

**Comment by droshev** [comment]
let's close it for now
