### ISSUE TITLE
Object Identifier - weak link selector, wrong `__table` class

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-styles#1742]
- Table - Current implementation forces user to put `fd-object-identifier__table` class as a wrapper for `fd-object-identifier` component. It should be changed to modifier, because it's only about the font size.

Table doesn't match example from Fiori3
![image](https://user-images.githubusercontent.com/26483208/94813205-ffe5fc80-03f7-11eb-91c7-7d8294c52edb.png)
![image](https://user-images.githubusercontent.com/26483208/94813226-06747400-03f8-11eb-8b0a-f6cf280f29f8.png)

It seems like the height should be auto + some padding, when object identifier is used. This should be consulted with designers.

- Link - For `@ngx/core` library the `fd-object-identifier__link` element, which in example is used with `fd-link` element has too weak selector to set own values. If it's not meant to be used only with `fd-link`, then it should have `fd-reset()` mixin. 

Also current [object identifier link](https://fundamental-styles.netlify.app/iframe.html?id=components-object-identifier--title-only&viewMode=docs#link) example has 2 ways to build ObjectIdentifier as link. We should keep the one built with `fd-link` in my opinion.

**Comment by InnaAtanasova** [comment]
0.5day
