### ISSUE TITLE
Breadcrumb/Link/Object Status/Pagination: Dark theme styling issue

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-styles#1766]
v0.13.0-rc.1

![Screen Shot 2020-10-09 at 6 32 03 AM](https://user-images.githubusercontent.com/29607818/95589117-2956e780-09f9-11eb-99fe-8fe7b1c4117f.png)

![Screen Shot 2020-10-09 at 6 46 07 AM](https://user-images.githubusercontent.com/29607818/95590633-278e2380-09fb-11eb-9279-cfc84dcfb121.png)

![Screen Shot 2020-10-09 at 6 55 14 AM](https://user-images.githubusercontent.com/29607818/95591655-6f617a80-09fc-11eb-9d47-1e2bdfdad2ff.png)
![Screen Shot 2020-10-09 at 6 55 59 AM](https://user-images.githubusercontent.com/29607818/95591705-8607d180-09fc-11eb-8ca2-582cc024d47a.png)

**Comment by salarenko** [comment]
Cannot reproduce in v0.13.0.
