### ISSUE TITLE
Select: trigger styling/size incorrect

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-styles#1771]
The button is tiny 😆  I think this is probably related to the icon changes

![Screen Shot 2020-10-09 at 6 58 45 AM](https://user-images.githubusercontent.com/29607818/95592027-ef87e000-09fc-11eb-988b-434b4af7e1f7.png)
![Screen Shot 2020-10-09 at 6 58 38 AM](https://user-images.githubusercontent.com/29607818/95592029-f0b90d00-09fc-11eb-9c8a-aea257d70fa9.png)

**Comment by JKMarkowski** [comment]
Addressed in #1793
