### ISSUE TITLE
Style issue: Button icon font not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-styles#1775]
Is this a bug, enhancement, or feature request?
Bug

Briefly describe your proposal.
Please double check Compact and Cozy Buttons: Visual core has icon font at 1rem (16px) vs Inspect mode on NGX is at .875rem (14px)

Which versions of Angular and Fundamental Library for Angular are affected? Vers 0.22.0

Please provide relevant source code if applicable.
Screen Shot 2020-10-01 at 4 12 06 PM

Is there anything else we should know?
Reposting here on Fundamental Styles. It was previously posted on Fundamental NGX (#3524) and was closed by skudum.

**Comment by droshev** [comment]
The icon font-size is 1rem
![Uploading Screen Shot 2020-12-10 at 10.43.46 PM.png…]()
