### ISSUE TITLE
Style issue: Numerical input field style and behavior not consistent on all 3 browsers

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-styles#1776]
**Describe the bug**
> A clear and concise description of what the bug is.
Platform: Numerical input field style and behavior not consistent on all 3 browsers:
Chrome: Up/Down arrow (+/-) visible on hover only; style is different
Forefox:  Up/Down arrow (+/-) visible all the time; different style than Chrome
Safari:     Up/Down arrow (+/-) visible all the time; different style than Chrome

> Is this issue related to a specific component? Input > Input Types

> What version of the Fundamental Library Styles are you using? v0.22.0

**To Reproduce**
1. Go to https://sap.github.io/fundamental-ngx/#/platform/input
2. Click on Input > Input Types
3. Click on Number Input Field

**Expected behavior**
Style, look and behavior should be same

**Screenshots**
<img width="1554" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/71797052/95693739-bb6e1400-0be2-11eb-908b-35f7d14b1070.png">

![image](https://user-images.githubusercontent.com/71797052/95772492-ab514580-0c71-11eb-95a6-d525b326e0a5.png)

**Desktop (please complete the following information):**
 - MacOS
 - Chrome, Firefox, Safari

**Comment by pierrom** [comment]
@puru-hk This bug applies to Input Group on Platform as well. Thanks

**Comment by kenykim** [comment]
@puru-hk

**Comment by droshev** [comment]
hell guys, this is not an issue of fundamental. This is a native browser input type number. What we can do is add styling to hide it.
I wouldn't insist to remove the native way of showing number input as this is the most performant way of handling it.
