### ISSUE TITLE
Style issue: Checkbox group icon font size not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-styles#1781]
**Describe the bug**
Checkbox group icon font on Platform not aligned with Visual Core.
Visual Core: 1 rem or 16px
NGX: 0.875 rem or 14px

> Is this issue related to a specific component? Checkbox group icon font

> What version of the Fundamental Library Styles are you using? v0.22.0

**To Reproduce**
1. Go to https://sap.github.io/fundamental-ngx/#/platform/checkbox-group
2. Scroll down to Reactive Form Examples
3. Click and Inspect "Checkmark icon". See error

**Expected behavior**
Should match specs from Visual Core 1 rem or 16px

**Screenshots**
Visual core:
<img width="781" alt="BusyIndicator (Fiori 3)" src="https://user-images.githubusercontent.com/71797052/95926035-1ed97c80-0d70-11eb-93ec-01e4c8886302.png">

NGX Inspect:
![image](https://user-images.githubusercontent.com/71797052/95926155-6cee8000-0d70-11eb-8918-bb91a9c760d2.png)

**Desktop (please complete the following information):**
 - MacOS: 
 - Affects Chrome, Firefox, and Safari browsers

**Comment by droshev** [comment]
<img width="707" alt="Screen Shot 2020-12-10 at 10 51 22 PM" src="https://user-images.githubusercontent.com/4380815/101859711-3ea3db80-3b3a-11eb-9bbc-6390019a0029.png">
