### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by widra** [SAP/fundamental-styles#1783]
The link for Fonts&Icons is broken it gives 404 error. 

Link: https://sap.github.io/fundamental-styles/?path=/docs/introduction-overview--page

**Comment by prsdthkr** [comment]
@droshev @jbadan Should our README link found under [this section](https://github.com/SAP/fundamental-styles#fonts--icons) be pointing to this wiki: https://github.com/SAP/fundamental-styles/wiki/Fonts-and-Icons:-FAQs?
