### ISSUE TITLE
Style issue: Menu icon font size not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-styles#1788]
**Describe the bug**
Please double check Menu with icon font size: Visual core has icon font at 1rem (16px) vs Inspect mode on NGX is at .875rem (14px)

> Is this issue related to a specific component? Menu component on Core and Platform

> What version of the Fundamental Library Styles are you using? v0.22.0

**To Reproduce**
1. Go to https://sap.github.io/fundamental-ngx/#/core/menu
2. Scroll down to Menu with icon
3. Click on Menu button with icon. See error

**Expected behavior**
Should be aligned with Visual Core:
![image](https://user-images.githubusercontent.com/71797052/96172853-da6aef80-0edb-11eb-9b82-72974c547b48.png)
Inspect on NGX:
![image](https://user-images.githubusercontent.com/71797052/96172928-f53d6400-0edb-11eb-869a-a89663e796c3.png)

**Desktop (please complete the following information):**
 - MacOS
 - Chrome, Firefox, Safari

**Additional context**
Please double check me on this. I'm not 100% sure that I am reading Inspect correctly - as shown on pics above. I have filed related issue #1775, #1777, #1781. Thank you.

**Comment by droshev** [comment]
<img width="594" alt="Screen Shot 2020-12-10 at 10 48 49 PM" src="https://user-images.githubusercontent.com/4380815/101859543-e40a7f80-3b39-11eb-9af5-defe693de756.png">
