### ISSUE TITLE
Icon - create a common class `fd-icon` for common styles

### ISSUE THREAD

**Issue by EvilAlexei** [SAP/fundamental-styles#1794]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
In the current version of the styles library, all icons have unique classes, like this: `.sap-icon--iconName`,
and all generic styles are applied by selector `[class*="#{$block}"]`

I think it will be better to have a common class for icons with common styles.
In this way, we will separate icon glyphs and styles, this will give us the ability to expand icons in the future.
For example to use different sets of styles or different icons with these styles.

As an example, we're able to see similar implementation in font-awesome:
```
<i class="far fa-arrow-right"></i>
<i class="fas fa-arrow-right"></i>
```
There are two sets of common styles `.far` and `.fas`

I suggest:
- Add a generic class for icons, for example, `.fd-icon`
- Replace icon generic styles to `.fd-icon` class and remove selector `[class*="#{$block}"]`
- Use this class in this way: `<i class='fd-icon fd-icon--iconName" />`

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current

**Comment by jbadan** [comment]
I like this idea - it follows the pattern established in other components 💯

**Comment by droshev** [comment]
let's close it for now. we may need to reopen in the future
