### ISSUE TITLE
fd-time has hardcoded width value

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-styles#18]
The fd-time component has a hardcoded width value which is a problem for the NGX and React implementation libraries (at least, not sure about Vue).

However, I can't seem to find a clean fix for the sass. What do you guys think? For the libs, it's sufficient to just remove the hardcoded width, but that breaks the display in the docs.

Example from fd-react: 
![image](https://user-images.githubusercontent.com/24924530/58989535-1bb0a280-87b2-11e9-9eec-965a28b15a54.png)

**Comment by bcullman** [comment]
see: 

https://github.com/SAP/fundamental-styles/blob/master/scss/components/time.scss#L7
