### ISSUE TITLE
Panels in PanelGrid loses padding gap in IE11 and < versions. 

### ISSUE THREAD

**Issue by JaySardhara** [SAP/fundamental-styles#180]
### Description
Panels in PanelGrid loses padding gap in IE11 and < versions. 
Code is using 'react-app-polyfill/ie11' to make website renderable on IE.

![image](https://user-images.githubusercontent.com/6151138/61149807-de1cf480-a496-11e9-9675-e45a658faf74.png)

 
### Versions
**fundamental-react:** 0.6.1
**fundamental-styles:**0.1.0

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by stefanoScalzo** [comment]
Panel grid is removed feel free to open a new issue with another component
