### ISSUE TITLE
Defect Hunting Sprint 49 - Denoland

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#1818]
List below the issues found during the defect hunting that need to be addressed before the release at the end of the sprint.

**Comment by InnaAtanasova** [comment]
- [ ] Improvement: Action Sheet examples should display the menu so that the tests can detect the changes in the popover body
<img width="1295" alt="Screen Shot 2020-11-03 at 4 39 24 PM" src="https://user-images.githubusercontent.com/39598672/98043480-48c41300-1df3-11eb-9636-35ba38984622.png">

- [ ] Improvement: Select examples- thee popover menus should be shown by default so the tests detect the changes

- [ ] Product Switch overflow issue (`...`)
<img width="411" alt="Screen Shot 2020-11-03 at 5 01 29 PM" src="https://user-images.githubusercontent.com/39598672/98045311-5038eb80-1df6-11eb-954c-e9c3f8b85fde.png">
<img width="511" alt="Screen Shot 2020-11-03 at 4 55 38 PM" src="https://user-images.githubusercontent.com/39598672/98045316-50d18200-1df6-11eb-901a-ecf300238e9b.png">


- [ ] Grid table buttons issue:
<img width="1256" alt="Screen Shot 2020-11-03 at 5 00 26 PM" src="https://user-images.githubusercontent.com/39598672/98045228-28498800-1df6-11eb-9c21-6577efc826f8.png">

- [ ] Should the Combobox mobile dialog have rounded corners?
<img width="1236" alt="Screen Shot 2020-11-03 at 5 05 08 PM" src="https://user-images.githubusercontent.com/39598672/98045667-d81ef580-1df6-11eb-92da-7db8c70b292b.png">

- [ ] Numeric content and Object Attribute are visible in the deployed project
<img width="194" alt="Screen Shot 2020-11-03 at 5 08 19 PM" src="https://user-images.githubusercontent.com/39598672/98045930-46fc4e80-1df7-11eb-8ff2-1853924f3c32.png">

**Comment by stefanoScalzo** [comment]
Bar right button spacing 
![Uploading Screen Shot 2020-11-04 at 3.04.09 PM.png…]()

**Comment by stefanoScalzo** [comment]
![Screen Shot 2020-11-04 at 3 11 59 PM](https://user-images.githubusercontent.com/50607147/98162983-1fb58800-1eb0-11eb-93d7-d89ba3654431.png)
No padding on dialog body

**Comment by InnaAtanasova** [comment]
> 
> * [ ]  No padding on dialog body

Inna: the body of the Dialog does not have padding

**Comment by stefanoScalzo** [comment]
![Screen Shot 2020-11-04 at 4 54 38 PM](https://user-images.githubusercontent.com/50607147/98171904-745fff80-1ebe-11eb-9529-ca92fb573668.png)
Focus on select

**Comment by stefanoScalzo** [comment]
![Screen Shot 2020-11-04 at 4 55 25 PM](https://user-images.githubusercontent.com/50607147/98171961-8c378380-1ebe-11eb-85f6-455a0d8b2b72.png)
shellbar button focus

**Comment by stefanoScalzo** [comment]
![Screen Shot 2020-11-04 at 4 55 54 PM](https://user-images.githubusercontent.com/50607147/98171995-9ce7f980-1ebe-11eb-9cb6-d05192b9091e.png)
shellbar butt

**Comment by stefanoScalzo** [comment]
![Screen Shot 2020-11-04 at 4 56 38 PM](https://user-images.githubusercontent.com/50607147/98172082-b721d780-1ebe-11eb-985d-7605154c4f7b.png)
switch text not centered
