### ISSUE TITLE
Style issue: Busy Indicator animated circle sizes

### ISSUE THREAD

**Issue by yukioht** [SAP/fundamental-styles#1833]
**Describe the bug**
The height and width of the currently implemented dots in the Busy Indicator do not match the specified values in the Visual Core specification. 

> Is this issue related to a specific component?
Busy Indicator

> What version of the Fundamental Library Styles are you using?
0.12.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**To Reproduce**
Go to:
https://sap.github.io/fundamental-styles/?path=/docs/components-busy-indicator--standard
https://sap.github.io/fundamental-ngx/#/core/busyIndicator

**Expected behavior**

The height and width of the dots in the Busy Indicator match the values in the Visual Core specification.
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2092401791

Small: 0.25rem; (results in 4px)
Medium: 0.5rem; (results in 8px)
Large: 1rem; (results in 16px)

Figma examples with CSS:
https://www.figma.com/file/PrHXo4hVWfOdNgeo4WTHRi/Ariba-Component-Library-v0.5?node-id=188%3A124

**Screenshots**
Current:
<img width="348" alt="Screen Shot 2020-10-28 at 4 20 58 PM" src="https://user-images.githubusercontent.com/71727800/97508360-a6141c00-193c-11eb-9e0b-0aec9375b2cb.png">
<img width="493" alt="Screen Shot 2020-10-28 at 4 59 48 PM" src="https://user-images.githubusercontent.com/71727800/97509259-0441fe80-193f-11eb-94f9-0bd3d0bd420c.png">

Proposed:
<img width="378" alt="Screen Shot 2020-10-29 at 2 17 54 PM" src="https://user-images.githubusercontent.com/71727800/97633606-97d40780-19f1-11eb-9482-a14972f6e3d7.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 0.15.7 
 - Browser Chrome (Version 86.0.4240.111), Safari (Version 14.0)

**Comment by droshev** [comment]
It looks like there is no issue:
![busy](https://user-images.githubusercontent.com/4380815/101849298-6dfc1d80-3b25-11eb-9814-95428499fc99.gif)

as you can see the circle grows from 16px to 32 px as it is in the spec
