### ISSUE TITLE
Style issue: Breadcrumb hyperlink text color

### ISSUE THREAD

**Issue by yukioht** [SAP/fundamental-styles#1844]
Currently implemented hyperlink text color does not match the ones in the Fiori3 specification.

> Is this issue related to a specific component?
Breadcrumb

> What version of the Fundamental Library Styles are you using?
V0.12.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**To Reproduce**
1. Go to https://sap.github.io/fundamental-styles/?path=/docs/components-breadcrumb--standard
2. Check the hypertext color in the breadcrumb and compare with the spec 

**Expected behavior**
Please use the hyperlink text color specified in the below documents.
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2035280373
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2144577672 (See under Hyperlinks)

**Screenshots**
<img width="633" alt="Screen Shot 2020-11-02 at 11 38 36 AM" src="https://user-images.githubusercontent.com/71727800/97911363-fc4bdb00-1cff-11eb-8f06-638005ee3afa.png">

**Desktop (please complete the following information):**
	•	OS: MacOS Catalina 0.15.7
	•	Browser Chrome (Version 86.0.4240.111), Safari (Version 14.0)

**Comment by droshev** [comment]
looks like it has been fixed
<img width="1189" alt="Screen Shot 2020-12-10 at 8 16 43 PM" src="https://user-images.githubusercontent.com/4380815/101848933-a94a1c80-3b24-11eb-8c04-2ff00918a149.png">
