### ISSUE TITLE
Toolbar overflow markup simplify

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-styles#1850]
Selectors in toolbar's overflow has too much nesting right now. 
Also on NGX after migrating to CDK `popover__body` is not anymore nested inside `fd-popover`, so selector should be simplified.
```
  &__overflow {
    &.#{$fd-namespace}-popover {
      .#{$block}__overflow__body {
```

**Comment by droshev** [comment]
@JKMarkowski what do we do with this? I saw you closed the PR
