### ISSUE TITLE
Pagination: Color issue with left and right arrows and dots between the pages

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-styles#1860]
**Describe the bug**

-If you are on the first or last page, the arrow for left or right should be grey, not ghost blue
-Dots between pages should be blue, not grey
Examples:
![Screen Shot 2020-11-05 at 11 53 59 AM](https://user-images.githubusercontent.com/72403541/98290084-d4839e00-1fb1-11eb-91cb-0558ce3c4fce.png)
![Screen Shot 2020-11-05 at 11 54 07 AM](https://user-images.githubusercontent.com/72403541/98290086-d51c3480-1fb1-11eb-8b3f-48f6a430931a.png)

**Comment by droshev** [comment]
1. The disabled arrows don't have the right color yet
2.

**Comment by itmilos** [comment]
@droshev
