### ISSUE TITLE
Rating Indicator missing read-only state

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-styles#1864]
**Describe the bug**
Rating Indicator component missing `read-only` state (both implementation and documentation).

**Expected behavior**
Rating Indicator supporting read-only state.

**Screenshots**
![image](https://user-images.githubusercontent.com/17496353/98370992-bb273400-203b-11eb-98ff-b86ade2090ab.png)

**Comment by droshev** [comment]
https://fundamental-styles.netlify.app/?path=/docs/components-rating-indicator--sizes#display-mode
