### ISSUE TITLE
Avatar: image fit, background color, zoom icon issues

### ISSUE THREAD

**Issue by wenyang33** [SAP/fundamental-styles#1874]
-->

**Describe the bug**
1. In Fiori 3 guidelines, there are two image fits: "Cover" and "Contain". https://ux.wdf.sap.corp/fiori-design-web/avatar/
<img width="398" alt="Screen Shot 2020-11-09 at 6 33 47 PM" src="https://user-images.githubusercontent.com/72157987/98620412-22521c00-22ba-11eb-8845-d0dec479d37e.png">
For the Avatar: https://sap.github.io/fundamental-ngx/#/core/avatar In the current version, we only have "Cover".

2. In Fiori 3 guidelines, there are two sets of background color: "Accent" and "Random". We lack of "Random" one.https://ux.wdf.sap.corp/fiori-design-web/avatar/
<img width="972" alt="Screen Shot 2020-11-09 at 6 40 22 PM" src="https://user-images.githubusercontent.com/72157987/98620965-2468aa80-22bb-11eb-96c8-e18b3d44deae.png">

3. In Fiori 3 visual core, the "Zoom icon" has the alignment rule: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2108082443
<img width="944" alt="Screen Shot 2020-11-09 at 6 45 23 PM" src="https://user-images.githubusercontent.com/72157987/98621312-d2745480-22bb-11eb-99b8-09b3adc470bc.png">

In our current version, we do not follow this alignment: 
<img width="503" alt="Screen Shot 2020-11-09 at 6 47 16 PM" src="https://user-images.githubusercontent.com/72157987/98621390-02235c80-22bc-11eb-90e6-500875b3af1f.png">

**Comment by droshev** [comment]
@wenyang33 could you open separate issues for #1 and #3
there isn't much we can do in styles for #2

**Comment by wenyang33** [comment]
@droshev Sorry, I just checked this post, I will open separate issues for #1 and #3
