### ISSUE TITLE
Add TriState Checkbox

### ISSUE THREAD

**Issue by yukioht** [SAP/fundamental-styles#1876]
### Component name
Add TriState to Checkbox

Fundamental version: V0.12.0

### Detailed description
Please add TriState to Checkbox and also see the attached PDF for details.

[tristate.pdf](https://github.com/SAP/fundamental-styles/files/5519448/tristate.pdf)

Specification:
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2060052861

**Comment by salarenko** [comment]
@yukioht What exactly is this ticket about?
We have tristate checkbox in Fundamental Styles for a long time, but it looks that the examples are broken/not good enough. We should definitely improve them.

**Comment by yukioht** [comment]
@salarenko 
This issue is about fixing those broken/not good examples. The UX team is using those examples to conduct the testing and QA. We cannot sign-off unless the component is implemented as we've designed.

**Comment by stefanoScalzo** [comment]
@yukioht are you referring to the spacing on top and bottom of the checkboxes?

**Comment by droshev** [comment]
we added examples here https://fundamental-styles.netlify.app/?path=/docs/components-forms-checkbox--desktop
