### ISSUE TITLE
Standard list: object status should be aligned on the right

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1906]
**Describe the bug**

Object status should be aligned on the very right, not in the middle.

> Is this issue related to a specific component?
Standard List with Byline

> What version of the Fundamental Library Styles are you using?
0.13

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**Screenshots**

<img width="1086" alt="2020-11-23_12-01-35" src="https://user-images.githubusercontent.com/53487468/99934414-e4f29180-2d83-11eb-8f8e-db8353626b63.png">

<img width="1315" alt="2020-11-23_12-01-07" src="https://user-images.githubusercontent.com/53487468/99934423-ed4acc80-2d83-11eb-8bdf-83c68b4a399e.png">

**Comment by droshev** [comment]
will be tackled as part of [#2063](https://github.com/SAP/fundamental-styles/issues/2063)
