### ISSUE TITLE
Defect Hunting and Release - Sprint 51

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#1907]
List all bugs found during the Defect Hunting as comments below using the following format:
- [x] short description, browser 
attached image or gif

**Comment by salarenko** [comment]
- [ ] Calendar `Date | Time` button should be a segmented button
![image](https://user-images.githubusercontent.com/17496353/100743917-426a8c00-33dd-11eb-9a86-31d599bf6c73.png)

- [ ] Calendar months and years buttons text is not centered
![image](https://user-images.githubusercontent.com/17496353/100744047-7a71cf00-33dd-11eb-8cb8-4cd40ad1de42.png)

- [ ] Misaligned icons in shellbar buttons
![image](https://user-images.githubusercontent.com/17496353/100747179-0128ab00-33e2-11eb-8251-273de80ca920.png)

- [ ] Vertically and horizontally misaligned select and date-picker controls (IE11)
![image](https://user-images.githubusercontent.com/17496353/100747797-cd01ba00-33e2-11eb-934c-f5e88012c543.png)

- [ ] Missing padding in two column combo-box items list
![image](https://user-images.githubusercontent.com/17496353/100748313-78ab0a00-33e3-11eb-9e75-8a29ed19b964.png)

**Comment by JKMarkowski** [comment]
- [ ] calendar - button - all browsers
![image](https://user-images.githubusercontent.com/26483208/100749256-b78d8f80-33e4-11eb-89ff-0a0a77a4b7f2.png)

**Comment by JKMarkowski** [comment]
- [ ] IE11 - tiles- one word is cut - I see initial width value is used. IE11 doesn't like initial.

![image](https://user-images.githubusercontent.com/26483208/100749624-35ea3180-33e5-11eb-88bd-b948320155ca.png)

**Comment by mikerodonnell89** [comment]
Shellbar button hover state misaligned

![Screen Shot 2020-12-01 at 11 04 16 AM](https://user-images.githubusercontent.com/2471874/100779001-f57abb80-33c4-11eb-8a14-1e91fc13ec48.png)

![Screen Shot 2020-12-01 at 11 04 23 AM](https://user-images.githubusercontent.com/2471874/100779014-f9a6d900-33c4-11eb-9fe6-e1e5d6f659ad.png)

**Comment by katekozlowska** [comment]
- [ ] Multi ComboBox - different styling of checkboxes

![fundamental-styles netlify app__path=_story_patterns-multi-combobox--cozy-and-compact](https://user-images.githubusercontent.com/7014311/100992967-15d98000-3555-11eb-89d1-52ba40d47ecf.png)
