### ISSUE TITLE
Carousel: Wrong hover state on the navigations

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-styles#1909]
**Describe the bug**

The hover state of the navigation buttons is not light blue.
It should have a box-shadow on hover:
![Screen Shot 2020-11-23 at 1 39 05 PM](https://user-images.githubusercontent.com/72403541/100018427-210a0e80-2de5-11eb-9d1e-ea3f1251e260.png)

Visual core ref: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2059230114
Fiori ref: https://ux.wdf.sap.corp/fiori-design-web/carousel/#behavior-and-interaction

**Comment by N1XUS** [comment]
As discussed:
* Item 1 fixed
* Item 2 is in line with official design specs for the carousel navigation
