### ISSUE TITLE
Remove CoPilot Container

### ISSUE THREAD

**Issue by jessmetivier** [SAP/fundamental-styles#1916]
**CoPilot container needs to be removed**
While updating the documentation for Shellbar in **Styles**, it came to my attention that the CoPilot functionality was removed from the UX team. However, we still have a container called <fd-shellbar__group--copilot>.

**Comment by jessmetivier** [comment]
Taken from my VS Code view:
![Screen Shot 2020-11-25 at 2 20 56 PM](https://user-images.githubusercontent.com/57453945/100272604-70f1ee00-2f29-11eb-9d1b-d9716610a63f.png)

PR: https://github.com/SAP/fundamental-styles/pull/1914

**Comment by droshev** [comment]
we will keep it as it is optional
