### ISSUE TITLE
Wizard in Modal Dialog

### ISSUE THREAD

**Issue by mengbingguo** [SAP/fundamental-styles#1941]
As a Fundamental Library user, I would like to have the wizard also displayed in a modal dialog. Especially useful when there aren't so much steps and content.

Should look and behave like in Fiori 3.

[Cloud Platform Design System Specification](https://sap.frontify.com/document/222581#/creation/wizard)
[Demo Kit Example](https://sapui5.hana.ondemand.com/#/entity/sap.m.Wizard/sample/sap.m.sample.WizardSingleStep)

**Comment by salarenko** [comment]
I think this is available right now with composition of the Dialog and Wizard components.

**Comment by droshev** [comment]
Let's follow https://github.com/SAP/fundamental-ngx/issues/4012
