### ISSUE TITLE
review Moments design and artifacts

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1944]
The goal of this issue is to review and prepare for bringing Moments as part of Fundamental Library.

**Comment by JKMarkowski** [comment]
### Description
In most of the cases it should be used, when page, or some essential data couldn't be loaded, also when results are not found (mostly in search). In some cases it can be used to inform about some success/failure.

### Layout
There are 3 types of component, which contains different spacing. All of them got same structure 

1. illustration
2. Title
3. Text
4. Action button(s) (optional)

More specified docs for layout can be found [here](https://pages.github.tools.sap/sap-design-ops/fiori-moments/empty-states.html#design-layout).

### Specification
Fiori 3 documentation has strict rules for (with component related delta theming differences)
- card
- dialog
- message box
- scene (similar to message page).

### Illustrations
For illustations there should be used different colors matching theme, those are defined in [visual spec](https://wiki.wdf.sap.corp/wiki/display/visualcore/Fiori+Moments+Illustration+Specification). Unfortunately I couldn't find any source of prepared illustrations
