### ISSUE TITLE
Defect Hunting Sprint 52

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-styles#1977]
Byline list selection - checkboxes should be centered vertically

![Screen Shot 2020-12-15 at 3 40 12 PM](https://user-images.githubusercontent.com/2471874/102281250-d2cfc300-3eeb-11eb-952a-c77945d89d1b.png)

**Comment by katekozlowska** [comment]
IE11 - help icon misalignment

![image](https://user-images.githubusercontent.com/7014311/102996935-41cc9d80-4524-11eb-870c-3a1385dde698.png)

**Comment by katekozlowska** [comment]
IE11 - text overflow in rating example

![image](https://user-images.githubusercontent.com/7014311/102997352-2f069880-4525-11eb-98b9-2ec23bc581d4.png)
