### ISSUE TITLE
The content of the Split button should not be centered

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#1981]
A bug found by @JKMarkowski 
The left hand side content of the Split button should not be centered.

![split button](https://user-images.githubusercontent.com/26483208/102481798-865ac380-4062-11eb-9b6b-da53eec4eb50.gif)

**Comment by stefanoScalzo** [comment]
Assuming this should be transfered to ngx ? @InnaAtanasova due to PR [4116](https://github.com/SAP/fundamental-ngx/pull/4116) ?
