### ISSUE TITLE
fix: Rating indicator Non-interactive mode styles are not implemented

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-styles#2008]
> Is this issue related to a specific component?
Rating indicator

> What browser are you working in?
any

> What version of Fundamental Library Styles are you using?
0.15

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**Describe the solution you'd like**
Styles need to be implemented for Non-interactive mode of rating indicator component.
Fiori has given styles for Non-interactive rating-indicator, but current implementation is missing this mode.
See screenshot below.

<img width="492" alt="screenshot-rating-indicator" src="https://user-images.githubusercontent.com/57661487/115814086-09759700-a412-11eb-801f-b2891061ad0f.png">

fiori:
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2035269535

**Comment by droshev** [comment]
@DeepakSap14 could you be more concrete and elaborate with more details?

**Comment by DeepakSap14** [comment]
@droshev i have described more now, and i did create markup in screenshot to make more clear. hope, this is well now.
