### ISSUE TITLE
Bug: Status Indicators - Counter with notification styling inconsistency

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#202]
**Description of the bug**

> Is this issue related to a specific component?
 [Status Indicators](https://sap.github.io/fundamental-styles/components/status-indicators.html) Counter with --notification modifier

> What version of the Fundamental Styles are you using?
v0.1.0

**Expected behavior**

- The background-color of the notification counter is `var(--fd-color-status-3)`. In Fiori the background-color is #D04343 (--sapContent_BadgeBackground)  which corresponds to var(--fd-color-accent-2).
- The notification counter placement offset in Fiori is 0.125rem.
- Fiori specifies a maximum of 4 characters for the counter.
- Inconsistency in the border-radius.  

**Screenshots**

Fundamental-styles:
![Screen Shot 2019-07-24 at 9 04 16 AM](https://user-images.githubusercontent.com/39598672/61795749-1d7e0600-adf2-11e9-9b40-ce766a7d6ea2.png)

Fiori:
<img width="280" alt="Screen Shot 2019-07-24 at 9 04 33 AM" src="https://user-images.githubusercontent.com/39598672/61795763-2373e700-adf2-11e9-9215-c043cfeb6036.png">

**Comment by droshev** [comment]
It has been migrated to Fiori 3
