### ISSUE TITLE
Introduce Facets(Form, Key-Value, etc) as component

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-styles#2020]
### Component name
> Propose a new or variant name

Facet

### Detailed description
> Describe the request

Facets are used with Object Page and Dynamic Page usually, but the facet types can also be used independently. Therefore, we can introduce Facets as their own component.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

ngx

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular

### Use case
> Describe when to use (and when not to use)

- most frequently used with Object Page and Dynamic Page as part of the header content.
- the facet types Form Facets, Key Value Facets, Image Facets etc. can also be used independently

### Visual style
> Describe specific needs related to color, typography, iconography, borders, space, size, and other visual properties.

as per Fiori3 visual spec.

> Describe how to arrange multiple instances and other alignment specifics.

as per Fiori3 visual spec.

> How should this respond to common contexts, i.e., touch, RTL, small screens.

as per Fiori3 visual spec.

> Describe interactive states, e.g., disabled, expanded, pressed.

as per Fiori3 visual spec.

### Expected behavior
> How should this handle events, outcomes, and transitions

as per Fiori3 visual spec.

> What [states should be available](https://medium.com/swlh/the-nine-states-of-design-5bfe9b3d6d85), i.e., nothing, loading, none, one, some, too many, incorrect, correct, done.

as per Fiori3 visual spec.

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/53509521/103755919-a0ba0880-5034-11eb-9f73-cbbd09f6fba0.png)

* Notes
Each facet has composing components but also has differences or additional styles. 
Should we use the underlying components as a pattern but add the additional styles with their own element/modifier classes? Or should we just add these deltas as modifiers to each underlying component and use these components directly as a pattern?

**Comment by kavya-b** [comment]
08/01- in progress

**Comment by kavya-b** [comment]
11/01- in progress, few queries/doubts on implementing styles, mailed to designers.

**Comment by kavya-b** [comment]
12/01- in progress, received clarifications to queries from designers. To be noted, images in the visual spec are not always correct, best to cross-refer against the following url for facets:
https://sapui5.hana.ondemand.com/#/entity/sap.uxap.HeaderFacetPattern/sample/sap.uxap.sample.Sample2

**Comment by kavya-b** [comment]
13/01- in progress

**Comment by kavya-b** [comment]
15/01- in progress, working on documentation pages.

**Comment by kavya-b** [comment]
20/01- on hold, working on different issue in ngx. will come back to this by tomorrow

**Comment by kavya-b** [comment]
21/01- in progress, working on adding Image Facet as well

**Comment by InnaAtanasova** [comment]
Hi @kavya-b I reviewed your PR but I have some questions I want to discuss with my team. My biggest struggle is to understand the purpose of this "component". There's no such component in the Wiki and I'm not sure we can introduce it as such in Fundamentals.

**Comment by kavya-b** [comment]
25/01- on leave
26/01- IDC holiday
27/01- in progress, PR raised, addressing review comments

**Comment by kavya-b** [comment]
28/01- working on review comments

**Comment by kavya-b** [comment]
01/02- awaiting further review comments
02/02- awaiting further review comments

**Comment by manjunathanagaraj** [comment]
Following is the scope:
- key value facets
- Form facets
- Image facets
- Rating indicator facets
