### ISSUE TITLE
Resizable Card Layout - implement styles

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-styles#2022]

**Comment by manjunathanagaraj** [comment]
Define styles as per Fiori3 specifications.

Fiori3 guidelines: https://ux.wdf.sap.corp/fiori-design-web/resizable-card-layout-overview-page/

Fiori3 visual specs: https://wiki.wdf.sap.corp/wiki/display/visualcore/OVP+Resizable+Layout

**Comment by DeepakSap14** [comment]
creating examples and writing styles

**Comment by DeepakSap14** [comment]
continue with styles for resizable card layout - 10-15% done

**Comment by DeepakSap14** [comment]
continue with styles for resizable card layout - 40-50% done

**Comment by DeepakSap14** [comment]
writing documentation and examples for resizable card layout.
Development done.
