### ISSUE TITLE
Storybook Documentation - Table - Wrong row navigation icon

### ISSUE THREAD

**Issue by mengbingguo** [SAP/fundamental-styles#2042]
**Describe the bug**

In Storybook showcase, navigable responsive table rows show the icon `sap-icon://navigation-right-arrow`, but it should be `sap-icon://slim-arrow-right`, as in SAPUI5.
Please update the showcases in Storybook.

> Is this issue related to a specific component?

Table

> What version of the Fundamental Library Styles are you using?

Latest (0.14.0)

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular

**Screenshots**

In Fundamental Styles Storybook:
![image](https://user-images.githubusercontent.com/75482561/104165204-58666600-53f9-11eb-9e3d-bb4578d2707b.png)

SAPUI5:
![image](https://user-images.githubusercontent.com/75482561/104165321-7df36f80-53f9-11eb-86fa-0176cac502cd.png)

**Comment by droshev** [comment]
@mengbingguo 
Actually according to the spec both icons are supported:
- navigation icon `slim-arrow-right` not clickable
- navigation icon button `navigation-right-arrow` for clickable
