### ISSUE TITLE
Defect Hunting sprint 53

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-styles#2045]
- [x] Buttons docs - buttons should have some vertical margin (not new to this sprint) - Mike https://github.com/SAP/fundamental-styles/pull/2054

![Screen Shot 2021-01-12 at 10 04 55 AM](https://user-images.githubusercontent.com/2471874/104347248-a04ec100-54bd-11eb-9e4c-812262870228.png)

- [x] Field Set - Need space between checkbox and label

![Screen Shot 2021-01-12 at 10 09 02 AM](https://user-images.githubusercontent.com/2471874/104347745-34208d00-54be-11eb-9348-2c039c4eb8d5.png)

- [x]  Product switch small screen - UI5 centers the title vertically if there is no subtitle, our lib does not.  Unclear in the specs what should really happen, should probably talk to designers **(Inna: I agree, it's not very clear from the specs what should happen. I will add this to the topics to be discussed and will move this to a separate issue)** 
Opened an issue https://github.com/SAP/fundamental-styles/issues/2052

UI5
![Screen Shot 2021-01-12 at 10 38 28 AM](https://user-images.githubusercontent.com/2471874/104351188-51eff100-54c2-11eb-8a65-e3ea420fcf35.png)

fd-styles
![Screen Shot 2021-01-12 at 10 39 52 AM](https://user-images.githubusercontent.com/2471874/104351341-82378f80-54c2-11eb-8cb4-364a6fb9ce6d.png)

- [x] Select popover body width should match width of control unless min/max explicitly set - **It shouldn't be same by default - Jedrzej**

![Screen Shot 2021-01-12 at 10 46 35 AM](https://user-images.githubusercontent.com/2471874/104352077-74363e80-54c3-11eb-803e-e45b3cc58261.png)

- [x] I do not think the shellbar user menu button should have this border - Mike
![Screen Shot 2021-01-12 at 10 52 14 AM](https://user-images.githubusercontent.com/2471874/104352705-3dacf380-54c4-11eb-870a-e9f510989064.png)

- [x] Table docs - Contextual menu popovers not working - **Inna** https://github.com/SAP/fundamental-styles/pull/2056
![Screen Shot 2021-01-12 at 10 53 53 AM](https://user-images.githubusercontent.com/2471874/104352894-79e05400-54c4-11eb-9f49-5d068964f5e1.png)

**Comment by InnaAtanasova** [comment]
- [ ] Multi Input - missing spacing between the checkbox and the text
<img width="1261" alt="Screen Shot 2021-01-12 at 1 30 34 PM" src="https://user-images.githubusercontent.com/39598672/104356966-95eef000-54da-11eb-9a11-51ed211e6d93.png">

- [ ] Side Nav - the arrow for showing/hiding the second level is not changing (rotating)
<img width="332" alt="Screen Shot 2021-01-12 at 1 27 24 PM" src="https://user-images.githubusercontent.com/39598672/104357074-b9b23600-54da-11eb-86f7-49f5ab5504ce.png">
<img width="314" alt="Screen Shot 2021-01-12 at 1 27 33 PM" src="https://user-images.githubusercontent.com/39598672/104357076-ba4acc80-54da-11eb-818a-1cdf7abb1047.png">

- [ ] Feed List and Item - Shouldn't it be called "Feed List Item" ? 
The "More" and "Less" buttons have a text cursor but should be a pointer
<img width="677" alt="Screen Shot 2021-01-12 at 1 13 19 PM" src="https://user-images.githubusercontent.com/39598672/104357301-00079500-54db-11eb-8d9a-4b828b1a471c.png">
<img width="684" alt="Screen Shot 2021-01-12 at 1 13 23 PM" src="https://user-images.githubusercontent.com/39598672/104357304-0138c200-54db-11eb-8981-2566ccbff3d0.png">

**Comment by InnaAtanasova** [comment]
IE11 issues:
- [ ] Missing top border in Dialog
<img width="1300" alt="Screen Shot 2021-01-12 at 2 01 38 PM" src="https://user-images.githubusercontent.com/39598672/104360336-e36d5c00-54de-11eb-9bc5-fdc66c78fb3c.png">

- [ ] Some examples are not centered in the container. See dialog above and Multi Input (many more in the docs)
<img width="1285" alt="Screen Shot 2021-01-12 at 2 02 15 PM" src="https://user-images.githubusercontent.com/39598672/104360410-013ac100-54df-11eb-9987-beae9accfe63.png">

- [ ] Links with icons do not display the icon. The arrows are missing from Right icon link and Left icon link
<img width="1351" alt="Screen Shot 2021-01-12 at 2 01 56 PM" src="https://user-images.githubusercontent.com/39598672/104360480-1dd6f900-54df-11eb-88ab-ca6a57bac041.png">
