### ISSUE TITLE
Documentation - Multi Input examples should have no checkbox and use correct icon

### ISSUE THREAD

**Issue by mengbingguo** [SAP/fundamental-styles#2046]
**Describe the bug**
The showcases should be Fiori-compliant and correct.

> Is this issue related to a specific component?

Multi Input

> What version of the Fundamental Library Styles are you using?

Latest (0.14.0)

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular

**To Reproduce**
1. Go to [https://sap.github.io/fundamental-styles/?path=/docs/patterns-multi-input--cozy-and-compact](https://sap.github.io/fundamental-styles/?path=/docs/patterns-multi-input--cozy-and-compact)

**Expected behavior**
- No checkbox in dropdown, that's Multi Combo Box
- The default icon in the input should be `sap-icon://slim-arrow-down`. Only use `sap-icon://value-help` if a value help dialog will be opened.

**Screenshots**
Screenshot from Fundamental Styles Storybook
![image](https://user-images.githubusercontent.com/75482561/104364416-d8ceb900-5516-11eb-9c72-8f9fcbb09b07.png)

**Additional context**
[Multi Input sample in SAPUI5](https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInput)
[]()

**Comment by droshev** [comment]
follow up with designers
