### ISSUE TITLE
Avatar Group Overflow Button border color design question

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#2091]
What is the border color of the Overflow button when semantics colors are applied?

**Comment by olshansky** [comment]
> Regarding the spacing around Avatars when placed inside a Popover body (attached image) here’s what they answered:
> The Popover body should have an inner padding of 1 rem and the spacing between the Avatars should be 0.5rem.
> 
> For the overflow button which has a blue border in its default state, when accent colors are applied, the border should have the same color as the accent color.
