### ISSUE TITLE
Table - Focus style on row not correct

### ISSUE THREAD

**Issue by mengbingguo** [SAP/fundamental-styles#2093]
**Describe the bug**
Focus style on table row is not the same as in SAPUI5

> What version of the Fundamental Library Styles are you using?

0.15.0

**To Reproduce**
https://sap.github.io/fundamental-styles/?path=/docs/components-table--primary

Chrome:
![image](https://user-images.githubusercontent.com/75482561/105995071-c755e700-60a8-11eb-9173-ebd0bc0f14f1.png)

Safari:
![image](https://user-images.githubusercontent.com/75482561/105995463-4f3bf100-60a9-11eb-829c-076b118480f6.png)

**Expected behavior**
https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.Table
![image](https://user-images.githubusercontent.com/75482561/105995286-11d76380-60a9-11eb-9bea-06867ba93c24.png)

**Comment by droshev** [comment]
the issue has been addressed 
you can test the issue here https://sap.github.io/fundamental-styles/iframe.html?id=components-table--primary&viewMode=docs#focusable-rows
by clicking on the rows

**Comment by mengbingguo** [comment]
Hi @droshev, thanks, I can confirm that the focus styles are corrected.
Just one thing, tables in SAPUI5 are focusable by default. From the doc examples, the developers would have to compose the focus behavior manually by adding the attribute. I think we could already add `fd-table__row--focusable` and `tabindex` to the examples so people just copy and use it.

I can create another BLI for improving the docs.
