### ISSUE TITLE
Card - Unwanted hover style on card header

### ISSUE THREAD

**Issue by mengbingguo** [SAP/fundamental-styles#2097]
**Describe the bug**
There is hover style change on the card header, even if no interaction is set on the card header.

> Is this issue related to a specific component?

Card

> What version of the Fundamental Library Styles are you using?

0.15.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular, React

**To Reproduce**
https://sap.github.io/fundamental-styles/?path=/docs/components-card--card-anatomy

**Expected behavior**
Should have the possibility to turn on/off card header interactibility.

Non-interactive card header example in SAPUI5:
https://sapui5.hana.ondemand.com/#/entity/sap.f.Card/sample/sap.f.sample.Card

- Background color shouldn't change on hover
- Cursor should be `default`, unless hovering over text in header, then it should be the `text` cursor

**Screenshots**

https://user-images.githubusercontent.com/75482561/106125558-99ca7580-615c-11eb-81a6-b5aaa6a90225.mov

**Comment by droshev** [comment]
Action item:
- [ ] create examples for cards with header that navigates to something and cards with a header that doesn't do so. Make sure to use correct card type examples
