### ISSUE TITLE
Visual Issues - Avatar Group

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2153]
- [ ] Avatar Group - dark theme; menu header border color is different than the body border in Dark theme
<img width="433" alt="Screen Shot 2021-02-15 at 7 46 27 PM" src="https://user-images.githubusercontent.com/4380815/108005393-9a6d6380-6fc6-11eb-9698-7001cec407e9.png">

- [ ] Avatar Group - menu arrow LTR is not centered (https://github.com/SAP/fundamental-styles/pull/2121)
<img width="474" alt="Screen Shot 2021-02-15 at 7 48 24 PM" src="https://user-images.githubusercontent.com/4380815/108005484-d86a8780-6fc6-11eb-958f-e495a53b1497.png">
<img width="420" alt="Screen Shot 2021-02-15 at 7 48 30 PM" src="https://user-images.githubusercontent.com/4380815/108005485-d86a8780-6fc6-11eb-9f0a-d0d91f6d454f.png">

**Comment by N1XUS** [comment]
@droshev as discussed:
* First item has been fixed
* Second item is not possible to achieve with static nature of the fundamental styles. Yet, it can be achieved in fundamental ngx. Further discussion on implementation for fundamental ngx is required.
