### ISSUE TITLE
Select: cliping styles required as per fiori3

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#2160]
> Is this issue related to a specific component?
Select

> What browser are you working in?
all

> What version of Fundamental Library Styles are you using?
0.17.rc.1

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
angular

**Describe the solution you'd like**
Need to have a clipping styles with desired values as mentioned in fiori3.

**Describe alternatives you've considered**
creating own styles in respective applications where ever we are using it.

**Additional context**
<img width="1378" alt="2021-02-22_09-44-46" src="https://user-images.githubusercontent.com/53487468/108662060-77c1da00-74f3-11eb-90b2-1818905899ad.png">
<img width="1383" alt="2021-02-22_09-44-41" src="https://user-images.githubusercontent.com/53487468/108662069-7ee8e800-74f3-11eb-9acc-88d2d2967e69.png">

**Comment by InnaAtanasova** [comment]
@sKudum I made another ticket which includes as an action point this one. Closing this in favour of https://github.com/SAP/fundamental-styles/issues/2207
