### ISSUE TITLE
Collapsible sidebar support?

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental-styles#2181]
Are navigation drawers (collapsible sidebars) supported or planned to be supported? 

https://mdbootstrap.github.io/bootstrap-material-design/docs/4.0/material-design/drawers/#templates-and-examples

**Comment by droshev** [comment]
i think we have it https://sap.github.io/fundamental-styles/?path=/docs/components-side-navigation--cozy#condensed
