### ISSUE TITLE
Select component update

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#2207]
The Select component needs to be updated according to the latest Fiori 3 design:
- [x] Select Field deltas for HCB/W in hover and pressed/down states - Should be fine  
- [x] Implement Max and Min Width variations - https://github.com/SAP/fundamental-styles/pull/2218
- [ ] Less/More - Jedrzej

**Comment by droshev** [comment]
We can implement more/less once someone requests the need for it
