### ISSUE TITLE
ShellBar migration to latest design

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#2208]
- [ ] Inputs (Search Field and Select) colors in normal and hover states
- [ ] Overlay - when the Search is triggered the content is covered with an Overlay
- [ ] Overflow and truncation
- [ ] Title Truncation - with and without CoPilot
- [ ] States of Search Field - collapsed, expanded large, expanded small

**Comment by droshev** [comment]
It is not valid at the moment as we are focusing on the new design
