### ISSUE TITLE
Scroll bar in popover

### ISSUE THREAD

**Issue by itmilos** [SAP/fundamental-styles#2219]
**Describe the bug**

> Is this issue related to a specific component?

Popover with scroll bar 

> What version of the Fundamental Library Styles are you using?

v0.17.0-rc.31

**To Reproduce**
1. Go to 'Avatar Group'
3. Scroll down to 'Group Type'

**Expected behavior**
Slide bar should be under popover, instead it is over

**Screenshots**
![image](https://user-images.githubusercontent.com/2508127/112491462-9e886000-8d80-11eb-9307-c26d225c446b.png)

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by droshev** [comment]
In case you are talking about the scrollbar that it should not be there -> this is limited to the storybook canvas
