### ISSUE TITLE
Input Field component should be refactored to latest Fiori3 specs

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-styles#2227]
**Describe the bug**
There are some features missing from the Input component, such as :
- Input with suggestions:
![image](https://user-images.githubusercontent.com/53509521/113256733-3dfca400-92e7-11eb-9b68-a9b62c06a461.png)
- Input with descriptions:
![image](https://user-images.githubusercontent.com/53509521/113256879-6e444280-92e7-11eb-80da-d15c14422247.png)

> Is this issue related to a specific component?

Input Component

**Comment by droshev** [comment]
I think we have all needed styling available. it just need to create an example
