### ISSUE TITLE
Missing focus styles on input-group elements

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-styles#2235]
**Describe the bug**

Focus styles of elements in `input-group`.

> Is this issue related to a specific component?

`Input-group`

> What version of the Fundamental Library Styles are you using?

Latest, `v0.17.0-rc.40`

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Maintaining Fundamental-NGX.

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular.

**To Reproduce**
1. Go [here](https://deploy-preview-5064--fundamental-ngx.netlify.app/#/platform/table).
* If down - create input-group with some elements in any possible way using the described version of the fundamental-styles.
2. Focus on the search input.
3. Type something
4. Click `Tab`
5. Clear button in focus but it's not visually represented.

**Expected behavior**
Focus is visually represented.

**Screenshots**

![image](https://user-images.githubusercontent.com/20265336/113820656-a7ffc800-9783-11eb-9565-e3c582b03106.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 89 (chrome)
 
**Additional context**

-

**Comment by Smiranin** [comment]
@platon-rov Seems like works well for dark and light themes.
![2021-05-25_10-07](https://user-images.githubusercontent.com/14183958/119454420-3387e500-bd41-11eb-9064-1eb0f738780a.png)
![2021-05-25_10-06](https://user-images.githubusercontent.com/14183958/119454424-34207b80-bd41-11eb-9f31-ff121001a008.png)

**Comment by Smiranin** [comment]
Reproduced issue on input-group. Fixing.
