### ISSUE TITLE
Popover body (arrow) not centered when used with a bigger size of Avatar component

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#2268]
The popover body with arrow is not centered when used with Avatar sizes bigger than xs.

<img width="354" alt="Screen Shot 2021-04-19 at 1 54 50 PM" src="https://user-images.githubusercontent.com/39598672/115281373-eb105280-a116-11eb-8cc8-ac0604d3b0a8.png">

**Comment by Smiranin** [comment]
@InnaAtanasova  Are you sure that is bug? I think this is improvement. I don't see such a possibility either in the documentation or in the code. There two alignment options 1 - left and 2 - right. Popover is left and right aligned accordingly. Position of arrow is always static `.5 rem ` from the edge. 
Actually, we can add third option - center alignment for popover.

**Comment by InnaAtanasova** [comment]
> @InnaAtanasova Are you sure that is bug? I think this is improvement. I don't see such a possibility either in the documentation or in the code. There two alignment options 1 - left and 2 - right. Popover is left and right aligned accordingly. Position of arrow is always static `.5 rem ` from the edge.
> Actually, we can add third option - center alignment for popover.

It's def a bug :) 
Here's how the specs define the look of the component:
<img width="603" alt="Screen Shot 2021-09-08 at 9 39 44 AM" src="https://user-images.githubusercontent.com/39598672/132520344-93d1011a-c621-4c7e-9f33-96f4f7c42863.png">
<img width="310" alt="Screen Shot 2021-09-08 at 9 39 38 AM" src="https://user-images.githubusercontent.com/39598672/132520353-b6ec6a47-b6d4-412b-84f8-a74fde74a04d.png">
