### ISSUE TITLE
Bug: Left and right padding on Action Bar is too wide and not aligned with Visua Core

### ISSUE THREAD

**Issue by xandrio** [SAP/fundamental-styles#2269]
**Is this a bug, enhancement, or feature request?**
Bug

**Briefly describe your proposal.**
Description imported from https://github.com/SAP/fundamental-ngx/issues/4849

Left and right padding on Action Bar is 32px. According to Visual Core it should be 1rem.
![109900796-c8040f00-7c4c-11eb-9421-9c59b7a0edb6](https://user-images.githubusercontent.com/5276786/115472905-6c650380-a243-11eb-89ce-9e9d91e6a7b1.png)
![109900805-cc302c80-7c4c-11eb-94ac-f20c39c94cb0](https://user-images.githubusercontent.com/5276786/115472934-7850c580-a243-11eb-9dba-fdf51aadcec5.png)
![109902792-c8ea7000-7c4f-11eb-9788-34914b475727](https://user-images.githubusercontent.com/5276786/115472966-830b5a80-a243-11eb-9548-4c7b7b0fc3e7.png)
![109902806-cdaf2400-7c4f-11eb-8af9-75f65b78a0b2](https://user-images.githubusercontent.com/5276786/115472978-89013b80-a243-11eb-97db-eb78229fad4f.png)
![109902833-d273d800-7c4f-11eb-8e03-28e6ffcc8b0f](https://user-images.githubusercontent.com/5276786/115472990-8e5e8600-a243-11eb-9fec-d7275ffdf2e1.png)

**Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)**
v0.28.0

**If this is a bug, please provide steps for reproducing it.**
Go to: https://sap.github.io/fundamental-ngx/#/platform/action-bar
Look at all the Action Bar items

**Comment by xandrio** [comment]
@pierrom you took documentation from **bar** component but test **action bar** component.
Component and documentation is different.
Please check:
https://sap.github.io/fundamental-ngx/#/core/action-bar
https://sap.github.io/fundamental-ngx/#/core/bar

**Comment by pierrom** [comment]
Thanks @xandrio. Can you point me to documentation for Action Bar. All I can find are old discussion on Action Bar "simply being an extension of Title Toolbar..." which has the same specs as what I included for Bar. Thanks for any info.
