### ISSUE TITLE
.fd-breadcrumb has a negative margin-bottom: -12px;

### ISSUE THREAD

**Issue by ghiobi** [SAP/fundamental-styles#229]
.fd-breadcrumb has a negative margin bottom which brings up the bottom element below it. If the breadcrumb has links, it may prevent the user from clicking it since the bottom element is covering it.

I believe, It's a bad practice to use negative margins unless they are indented.

> Is this issue related to a specific component?
.fd-breadcrumb 

> What version of the Fundamental Styles are you using?
0.1.0
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Internal SAP Project.

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular with NGX-Fundamental.

It looks like NGX-Fundamental is not using the ul element. There's a selector in the breadcrumb example of fundamental-styles where it sets the last ul to `margin-bottom: 0`.

```
ul:last-child {
    margin-bottom: 0;
}
```
So should this issue be part of NGX-Fundamental's issue for now? 

*Expected behavior**
Elements should flow with the content.

**Comment by MattL75** [comment]
Hey Laurendy

I think this is fixed in the fundamental-styles release candidates, but Fundamental-NGX uses the stable 0.1.0. Not sure when we'll be adopting the newer stuff.

**Comment by ghiobi** [comment]
Alright, looks like we can wait

**Comment by droshev** [comment]
I think this issue has been fixed already
