### ISSUE TITLE
ActionBar: Title/description editable

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#233]
As a User , I would like to edit the title present in the action bar. Once I clicked on "Rename" action button it should allow me to edit the title by providing the input text box with populating the current title
<img width="1032" alt="Screenshot 2019-08-12 at 10 23 43 AM" src="https://user-images.githubusercontent.com/53512176/62846190-a4d0e200-bceb-11e9-93c2-f8999f80f3e8.png">

**Comment by droshev** [comment]
@LeoT7508 @jeannewalters There is a team that need to provide action bar where the title/description can be edited inline.
What do you think of that idea?

**Comment by LeoT7508** [comment]
@droshev 

We have experimented with the idea of having an editable title before. I don't see why we couldn't. However I'm not sure if putting that option in the menu is the best route, in our previous exploration editing the title was available simply by hovering over the text and a field would appear.

**Comment by droshev** [comment]
@LeoT7508 I agree with you - it makes less dependant to other components(e.g. item in the menu)

**Comment by droshev** [comment]
closing this as we will deprecate the component
