### ISSUE TITLE
ActionBar: responsive design needed

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#234]
Responsiveness for the Action bar component is not proper.
 
- Iphone X device Contextual menu is displaying out of the screen.
<img width="332" alt="Screenshot 2019-08-12 at 10 44 28 AM" src="https://user-images.githubusercontent.com/53512176/62846926-13646e80-bcf1-11e9-993c-29e2c7e7e7ad.png">
 
 - Iphone 5/SE not able to see any actions or contextual menu itself.

<img width="360" alt="Screenshot 2019-08-12 at 11 07 10 AM" src="https://user-images.githubusercontent.com/53512176/62847020-91287a00-bcf1-11e9-8076-5f4338e2776e.png">

**Comment by droshev** [comment]
I think we have a design for that, it is just buggy.

**Comment by wizgd** [comment]
@droshev So probably it makes sense for @manu-kr to fix it. I am assigning it to him.

**Comment by manu-kr** [comment]
Fixed the issue.
