### ISSUE TITLE
ActionBar: compatibility/browser issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#235]
**Describe the bug**
Action bar compoent is not supported in IE browser.

Action bar

Next Gen UI

 Angular

**Desktop (please complete the following information):**
 - OS: Windows 10
 -Internet Explorer 
 - 11+

**Comment by fkolar** [comment]
I think in general travis along wiht chrome headless mode is not good here. When I was discussing this with other teams such angular teams, they are using https://www.browserstack.com/ which has  drivers as well. 

So you are able to not only run your test across multiple browsers but also multiple OS and devices Let's think about such service.

**Comment by droshev** [comment]
@fkolar we are open for any idea for improvement. Maybe you can help us in this direction?

**Comment by fkolar** [comment]
The quesiton is do we have some (budget) to purchase such service or similar?

They are two popular https://www.browserstack.com/pricing? or https://saucelabs.com/pricing.
Angular team is using both. 

I will ping someone inside clarity design (vmware) what they are using, so we can have right solution!!

**Comment by droshev** [comment]
closing as we will deprecate the component
