### ISSUE TITLE
Update Info Label to latest BTP design

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#2441]
The design of Info Label needs to be updated to follow the latest design guidelines for BTP:
![51](https://user-images.githubusercontent.com/39598672/121239890-c65b7000-c867-11eb-8eaa-e4ce7e820d67.png)

Refer to this page (BTP Visual Design WIKI) for detailed specification: https://wiki.wdf.sap.corp/wiki/display/CPDesign/Info+Label

**Comment by droshev** [comment]
closing as we are shifting toward Fiori Horizon
