### ISSUE TITLE
Form Grid design corrections needed

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2444]
**Describe the bug**

> Is this issue related to a specific component?
Form Grid

**To Reproduce**
1. Go to https://fundamental-styles.netlify.app/?path=/docs/components-forms-form-grid--s-size
2. Go to https://fundamental-styles.netlify.app/?path=/docs/components-forms-form-group--primary

**Expected behavior**
- [ ] the spacing between fields and forms needs to be updates
- [ ] add Display Mode examples (horizontal and vertical). Maybe there are missing stylings for the display mode (e.g. padding, background)
- [ ] add Display Mode and Horizontal Layout examples for `Form Item`, `Form Label`, `Form Group`, and `Form Header`
- [ ] add examples with form items in `Form Header` page

**Screenshots**
![Screen Shot 2021-06-12 at 6 49 58 AM](https://user-images.githubusercontent.com/4380815/121773702-93f19180-cb4b-11eb-8a71-a2191513deba.png)
![Screen Shot 2021-06-12 at 6 58 52 AM](https://user-images.githubusercontent.com/4380815/121773718-ac61ac00-cb4b-11eb-9cbc-a5603de4d668.png)
![Screen Shot 2021-06-12 at 6 52 27 AM](https://user-images.githubusercontent.com/4380815/121773725-b8e60480-cb4b-11eb-8cb4-c2ab52255c48.png)

**Comment by aberikashvili** [comment]
@droshev I noticed, when there's 2 columns and you delete once component from any column, other components are centered in the middle:

Before deletion:
![image](https://user-images.githubusercontent.com/3863691/125079977-4bd77780-e0d5-11eb-9dc9-ebbeecaa4c9b.png)
After deletion:
![image](https://user-images.githubusercontent.com/3863691/125080030-5d208400-e0d5-11eb-8d89-4f7b3458ef75.png)

Is this also a bug which need to be fixed?

**Comment by droshev** [comment]
> @droshev I noticed, when there's 2 columns and you delete once component from any column, other components are centered in the middle:
> 
> Before deletion:
> ![image](https://user-images.githubusercontent.com/3863691/125079977-4bd77780-e0d5-11eb-9dc9-ebbeecaa4c9b.png)
> After deletion:
> ![image](https://user-images.githubusercontent.com/3863691/125080030-5d208400-e0d5-11eb-8d89-4f7b3458ef75.png)
> 
> Is this also a bug which need to be fixed?

we should add this class https://github.com/SAP/fundamental-styles/blob/7d1097ddd9e0787ebfe939e9f682ace2a4356dea/src/form-layout-grid.scss#L38

**Comment by dimamarksman** [comment]
Do we have an ability to add some complex inputs to the Form Grid?
I mean adding multi-input, date-picker, combobox, and so on (input group components).
Asking cause as far as I can see vertical Form Grid margins between rows are working only for simple `.fd-input` and `.fd-select__control`. 
So when I try to insert for example `datepicker` there is no vertical margins
