### ISSUE TITLE
User Menu component missing inner padding

### ISSUE THREAD

**Issue by UlianaMunich** [SAP/fundamental-styles#2457]
According to the spec of User Menu https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2104434669 there should be padding inside of the popover. 

**Compact**
padding: 1rem 0.5rem; (results in 16px 8px)

**Cozy**
padding: 1rem 0rem; (results in 16px 0px)

Please add it, if possible. 
Thanks

**Comment by kavya-b** [comment]
Hi @UlianaMunich , I checked and I see that the inner padding is present: 
For compact:
![image](https://user-images.githubusercontent.com/53509521/123915781-80915380-d99e-11eb-89b8-f30feb37f05d.png)

For cozy:
![image](https://user-images.githubusercontent.com/53509521/123915604-50e24b80-d99e-11eb-88ed-9dc01cd809b7.png)

**Comment by UlianaMunich** [comment]
Thank you, @kavya-b, have missed it somehow.
