### ISSUE TITLE
Defect Hunting for Sprint 65 - Bern

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#2460]
Please report the issues you found during the defect hunting with the following format:

```
- [ ] Short title containing the component name
- Description of the issue
- Ways to reproduce it
- Screenshot or gif
- Browser 
```

Before starting to work on the issue please write your name after the title in bold.
Once the PR is open, please link a link to the PR after your name
Mark this issue as done by checking the checkbox

Example:
<img width="836" alt="Screen Shot 2021-06-03 at 3 29 26 PM" src="https://user-images.githubusercontent.com/39598672/120701160-828bf380-c480-11eb-8aba-d84e08204da8.png">

**Comment by InnaAtanasova** [comment]
Issues from previous sprints:
- [ ] https://github.com/SAP/fundamental-styles/issues/2194
- [ ] https://github.com/SAP/fundamental-styles/issues/2364

**Comment by mikerodonnell89** [comment]
- [ ] Calendar in phone portrait mode does not look correct, it looks almost identical to the landscape mode
<img width="959" alt="Screen Shot 2021-06-23 at 1 40 07 PM" src="https://user-images.githubusercontent.com/2471874/123143384-87f9af80-d428-11eb-9b9c-0855b138f29c.png">

But here it is the actual design
<img width="869" alt="Screen Shot 2021-06-23 at 1 38 32 PM" src="https://user-images.githubusercontent.com/2471874/123143205-4ff26c80-d428-11eb-8c92-6310dedc0beb.png">

**Comment by mikerodonnell89** [comment]
- [ ] Tabs - leftmost tab missing padding on the left (same problem but on the right in RTL)

<img width="300" alt="Screen Shot 2021-06-23 at 2 13 45 PM" src="https://user-images.githubusercontent.com/2471874/123147593-3acc0c80-d42d-11eb-83fe-367c0e39380b.png">

**Comment by mikerodonnell89** [comment]
- [ ] Grid list - header that contains edit button is not tall enough.  This is readily apparent in the high contrast color themes. I think the class `fd-grid-list__item-toolbar` should also set the height.

From fundamental-styles:
<img width="305" alt="Screen Shot 2021-06-23 at 3 07 53 PM" src="https://user-images.githubusercontent.com/2471874/123154409-cac18480-d434-11eb-9c1d-70e1499ae773.png">

From the specs:
<img width="309" alt="Screen Shot 2021-06-23 at 3 08 33 PM" src="https://user-images.githubusercontent.com/2471874/123154472-e2990880-d434-11eb-9ea2-bb2b6b27ceb0.png">

**Comment by mikerodonnell89** [comment]
- [ ] None of these things from the bottom of the nav actually bring up any content when clicked
<img width="209" alt="Screen Shot 2021-06-23 at 3 48 04 PM" src="https://user-images.githubusercontent.com/2471874/123158953-686b8280-d43a-11eb-9f10-26ed6f361ea6.png">

**Comment by InnaAtanasova** [comment]
> * [ ]  None of these things from the bottom of the nav actually bring up any content when clicked
> 
> <img alt="Screen Shot 2021-06-23 at 3 48 04 PM" width="209" src="https://user-images.githubusercontent.com/2471874/123158953-686b8280-d43a-11eb-9f10-26ed6f361ea6.png">

This is expected. Everything inside Dev section should not be available to the user. These are helper components used inside other components but per Fiori 3 specs are not stand-alone. The Dev section should not be visible, it was invisible and an update of Storybook broke it and made it visible. No idea how to hide it again.

**Comment by InnaAtanasova** [comment]
- [ ] Disabled focusable button should be "tabbable and focusable" according to the text in the section description but the buttons do not get the focus.
<img width="1242" alt="Screen Shot 2021-06-29 at 1 28 58 PM" src="https://user-images.githubusercontent.com/39598672/123841797-ff728780-d8dd-11eb-9ee3-fe857f424118.png">

**Comment by InnaAtanasova** [comment]
<img width="582" alt="Screen Shot 2021-06-29 at 1 35 12 PM" src="https://user-images.githubusercontent.com/39598672/123842552-e7e7ce80-d8de-11eb-8ad9-a0702d6b5f86.png">
<img width="478" alt="Screen Shot 2021-06-29 at 1 35 06 PM" src="https://user-images.githubusercontent.com/39598672/123842554-e8806500-d8de-11eb-8b73-2a8f9dcc6ac0.png">

Tristate not centered again
