### ISSUE TITLE
Is there any documentation or help about How to switch the theming of FD during the runtime

### ISSUE THREAD

**Issue by Vita-Meow** [SAP/fundamental-styles#2465]

**Comment by droshev** [comment]
Hi @Vita-Meow. What you need to do is to toggle the following files:
- for Fiori 3 light: https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3/css_variables.css
- for Fiori 3 dark: https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3_dark/css_variables.css
- for Fiori 3 High-Contrast-Black: https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3_hcb/css_variables.css
- for Fiori 3 High-Contrast-White: https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3_hcw/css_variables.css
We have done the implementation for [Fundamental NGX](https://sap.github.io/fundamental-ngx/#/core/theme-switcher)

**Comment by Vita-Meow** [comment]
> Hi @Vita-Meow. What you need to do is to toggle the following files:
> 
> * for Fiori 3 light: https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3/css_variables.css
> * for Fiori 3 dark: https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3_dark/css_variables.css
> * for Fiori 3 High-Contrast-Black: https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3_hcb/css_variables.css
> * for Fiori 3 High-Contrast-White: https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3_hcw/css_variables.css
>   We have done the implementation for [Fundamental NGX](https://sap.github.io/fundamental-ngx/#/core/theme-switcher)

Great! That's cool.
And I have checked the Fundamental NGX, seems what I need to do is pack all theme CSS into my project, and just switch the theme CSS when the user switches the theme.
Thank you so much!

**Comment by droshev** [comment]
@Vita-Meow thanks for raising this questions. It is a great candidate for an article or a blog
