### ISSUE TITLE
Segmented Button not showing state if disabled

### ISSUE THREAD

**Issue by trilodge** [SAP/fundamental-styles#2501]
**Describe the bug**
A segmented button doesn't show its state if u either set it to disabled via attribute or set it to disabled via "is-disabled" class attribute. 

> Is this issue related to a specific component?

Segmented Button - https://sap.github.io/fundamental-styles/?path=/docs/components-button--primary#segmented-button

> What version of the Fundamental Library Styles are you using?

0.18.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Fundamental Styles + vue.js (w/o vue fundamentals because of outdated components)

**To Reproduce**
1. set disabled attribute to button within segmented button
2. set "is-disabled" class attribute to button within segmented button
3. button loses its selected state

**Expected behavior**
The button still shows its selected or not selected state regardless of disabled or not.

**Screenshots**

<img width="1052" alt="Screenshot 2021-06-28 at 17 07 21" src="https://user-images.githubusercontent.com/4234544/123659814-5bcc9d00-d833-11eb-9fe1-27c7fc518bd0.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: latest

**Additional context**
The combination of "is-selected" and "is-disabled" or "disabled" is not represented in the CSS.

**Comment by droshev** [comment]
actually the problem is that we don't provide styling for selected disabled button:
```
<button class="fd-button fd-button--positive is-selected" disabled>Selected State</button>
```
this has to have the selected color/background

**Comment by platon-rov** [comment]
not reproducible, fixed
