### ISSUE TITLE
Fixed Card Layout - issue

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2510]
Fixed Card Layout - there's a word-break rule that is causing troubles in DXP (when table is used inside a card). Need to find out why it's added:
<img width="464" alt="Screen Shot 2021-05-20 at 4 05 02 PM" src="https://user-images.githubusercontent.com/39598672/119042096-67e85380-b985-11eb-8c0c-8b224726f819.png">

**Comment by platon-rov** [comment]
Introduced with: https://github.com/SAP/fundamental-styles/pull/2326
Fixed with: https://github.com/SAP/fundamental-styles/pull/2595

@droshev reassigning on you for fix confirmation & closing. In case of any issues let me know.
