### ISSUE TITLE
Byline Thumbnail issue

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2512]
Thumbnail not centered in Byline
<img width="255" alt="Screen Shot 2021-05-20 at 4 30 33 PM" src="https://user-images.githubusercontent.com/39598672/119044919-c95df180-b988-11eb-9faa-b40d3b450ae4.png">

**Comment by InnaAtanasova** [comment]
<img width="2042" alt="Screen Shot 2021-07-19 at 3 26 40 PM" src="https://user-images.githubusercontent.com/39598672/126215824-ac7eaaa3-69df-4682-9f5d-911253f8b713.png">

Issue no longer reproducible. Screenshot taken from the current main branch deploy.
