### ISSUE TITLE
Icon in Link wrong color

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2516]
Wrong color of the icon inside Link - Jedrzej
<img width="490" alt="Screen Shot 2021-03-25 at 4 58 30 PM" src="https://user-images.githubusercontent.com/39598672/112542815-65a1b880-8d8b-11eb-9cf1-7cb54df403e1.png">
Specs:
<img width="1518" alt="Screen Shot 2021-03-25 at 4 58 21 PM" src="https://user-images.githubusercontent.com/39598672/112542850-6df9f380-8d8b-11eb-85fc-c2a2283b2d46.png">

**Comment by N1XUS** [comment]
@droshev cannot reproduce here: https://fundamental-styles.netlify.app/?path=/docs/components-link--primary
![image](https://user-images.githubusercontent.com/6586561/124763003-29f6bd00-df3c-11eb-9e7d-23f092dcbd03.png)
