### ISSUE TITLE
Grid List Item issue

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2517]
Weird focus for the radio button inside Grid List item: - Jedrzej
<img width="544" alt="Screen Shot 2021-03-25 at 5 00 17 PM" src="https://user-images.githubusercontent.com/39598672/112543092-b0233500-8d8b-11eb-9c51-377b67c82bc0.png">

**Comment by manjunathanagaraj** [comment]
I tested this on Mac - Chrome, Safari, Firefox. Not reproducible. QA can check and close it.

**Comment by manjunathanagaraj** [comment]
closing it as @nikvalor - QA, has reported it to be not reproducible.
