### ISSUE TITLE
Standard List documentation bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2518]
Standard List documentation bug: - Jedrzej
<img width="1186" alt="Screen Shot 2021-03-25 at 5 03 33 PM" src="https://user-images.githubusercontent.com/39598672/112543405-14de8f80-8d8c-11eb-8c97-37bc234f6b81.png">

**Comment by sKudum** [comment]
Hi @droshev ,

Could you please elaborate the issue. So we can proceed accordingly.

Thank You.

**Comment by droshev** [comment]
not reprodicable
