### ISSUE TITLE
Carousel layout: add wrapper for slides

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-styles#2574]
**Describe the bug**

> Is this issue related to a specific component?
Carousel

> What version of the Fundamental Library Styles are you using?
0.19.0-rc.26
> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular, fundamental-ngx

**Additional context**
At the moment in fundamental-ngx/core carousel component we have additional wrapper for slides, which then applied with transform css property to move the content.
This wrapper should be also reflected in fundamental-styles due to floating buttons inside content container:
![image](https://user-images.githubusercontent.com/6586561/125673166-0e718b07-dd80-411b-8e14-eac15efb268c.png)

**Comment by InnaAtanasova** [comment]
will be done as part of v.1 ticket https://github.com/SAP/fundamental-styles/issues/3962
