### ISSUE TITLE
Horizontal Navigation design revisit

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#2617]
During a discussion with designers (Erico and Carmen) today it became clear that the way we implemented the horizontal navigation is not entirely correct. We are currently using the Shell Navigation control but should be following the specs for horizontal navigation. Both components rely on IconTabBar but they have minor specific differences. 
We need to:
- [ ] decide on how we are going to handle such components that are very similar but used in different LOBs
- [ ] refactor the implementation of Horizontal Navigation

**Comment by droshev** [comment]
Since we are moving toward the new design i don't think we should refactor what we have.
