### ISSUE TITLE
Docs site: Organize components into categories

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-styles#263]
In the left navigation of the docs site, the list of components is getting pretty long and is just alphabetized.  We should look into grouping components into logical categories to place related components together.

Here is a suggested list of categories (used on the [Concur HIG](https://hig.concur.com) site):
* Alerts & Messaging
* Buttons & Navigation
* Controls & Inputs
* Data & Lists
* Layout & Structure
* Overlays

**Comment by droshev** [comment]
Let's discuss and agree whether we want to group the components

**Comment by droshev** [comment]
we will close this issue for now and if it arises we can address it
