### ISSUE TITLE
Shadow issue | Menu 

### ISSUE THREAD

**Issue by kenykim** [SAP/fundamental-styles#2662]
There is a gap on shadow for Menu between visual guidelines and NGX demo 

**NGX**
https://fundamental-ngx.netlify.app/#/core/menu
<img width="209" alt="Screen Shot 2021-08-09 at 7 54 23 PM" src="https://user-images.githubusercontent.com/58018352/128801368-b12c9c94-3480-4f2c-b9b7-ba4bafa2e7cf.png">

**Fiori**
<img width="533" alt="Screen Shot 2021-08-09 at 8 00 27 PM" src="https://user-images.githubusercontent.com/58018352/128801776-c758a7c6-35ea-4a17-8764-6ea41a74270d.png">
Menu guideline: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2061501144

The shadow on the menu looks darker than its design spec

<img width="945" alt="Screen Shot 2021-08-09 at 7 52 14 PM" src="https://user-images.githubusercontent.com/58018352/128801140-e2057faa-0374-4551-8e47-70766d356732.png">
Shadow guideline : https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2144577672#SemanticControlParameters(Fiori3)-ShadowLevels

Please take a look and let me know

**Comment by InnaAtanasova** [comment]
Hi @kenykim ,

I checked the implementations in fund-styles and fund-ngx and in both cases the box-shadow that is used is `--sapContent_Shadow1`. This value comes from the package `sap-theming`, which we use for colors, metrics, etc. Why the result looks different in the images and in the implementation I have no clue. 
Let me know if there's anything else I can do from my side.

Cheers,
Inna

Here's our implementation in fund-styles and fund-ngx:
![Screenshot 2022-12-08 at 3 05 01 PM](https://user-images.githubusercontent.com/39598672/206557244-5dad5178-667e-491b-988d-640b649c8db5.png)
![Screenshot 2022-12-08 at 3 05 33 PM](https://user-images.githubusercontent.com/39598672/206557247-87631c2b-d655-4c5a-940d-369916463aa7.png)
