### ISSUE TITLE
Style cleanup for Table Component

### ISSUE THREAD

**Issue by aberikashvili** [SAP/fundamental-styles#2726]
It looks like the technical debt with hardcoded styling in ngx has augmented. We need to address this asap.
There are few options:

1. the hardcoded styles in ngx has been already address in fundamental-styles repo
2. the hardcoded styles in ngx is not reflected in fundamental-styles repo
In case of the first option then the developer needs to remove the hardcoded styling; use the latest from styles; test and open a PR
In case of the second, then the developer needs to bring it there, open a PR, test it, merge it, then do the steps above.

https://github.com/SAP/fundamental-ngx/issues/5025

**Comment by droshev** [comment]
@nickiovenko any update here?

**Comment by nickiovenko** [comment]
@droshev in the corresponding PR Arkadii made the edits but didn't have a chance to check them due to the high load
