### ISSUE TITLE
Localization Editor should be redesigned

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-styles#275]
The Localization Editor component should be redesigned and use cases adjusted.

* The popover should only show when the button is clicked (not on focus of the input)
* The use of input groups for both the default language and all subsequent languages is confusing because the default one is a button and all others are just addon text
* If the other languages are going to use input groups, there needs to be some aria attributes added to help describe the inputs

**Comment by droshev** [comment]
we will remove it
