### ISSUE TITLE
Refactor Time styling to remove hard-coded width

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-styles#280]
Currently, the `.fd-time` class has a hard-coded width of 184px.  This should be refactored into better CSS (maybe using flex box to layout the items?).

**Comment by jbadan** [comment]
We should probably just update to match the newest spec: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2033852418

![Screen Shot 2019-08-20 at 8 33 16 AM](https://user-images.githubusercontent.com/29607818/63361659-5d6ad700-c325-11e9-8033-50e857eed84a.png)

**Comment by jbadan** [comment]
related to https://github.com/SAP/fundamental-styles/issues/18

**Comment by stefanoScalzo** [comment]
Let's completely refactor component to match fiori 3

**Comment by droshev** [comment]
@stefanoScalzo did you work on that?
