### ISSUE TITLE
Dark theme bundled CSS

### ISSUE THREAD

**Issue by jasssonpet** [SAP/fundamental-styles#2837]
**Describe the bug**

Hello, it looks like the dark theme distribution is the (almost) the same as the white theme:
* https://sap.github.io/fundamental-styles/fundamental-styles.css
* https://sap.github.io/fundamental-styles/fundamental-styles-sap_fiori_3_dark.css

It looks like that only separated CSS component files have the dark theme but not the bundled one (`fundamental-styles-sap_fiori_3_dark.css`).

This is also the same in the NPM distribution (0.20).

**Comment by droshev** [comment]
@jasssonpet thank you for reporting the issue. I have opened a PR (#2875 )
