### ISSUE TITLE
Table: Undo hardcode of 200px for fixed col header table

### ISSUE THREAD

**Issue by hertweckhr1** [SAP/fundamental-styles#292]
**Describe the bug**
Currently tables with fixed columns have a 200px width hardcoded into styles.  This is limiting right now - the width should be able to be selected by the consuming library. 
![image](https://user-images.githubusercontent.com/34703079/63621422-bb5b2100-c5a8-11e9-8d01-5a3100aac7e4.png)

* Docs site blurb for fixed column table will also need to be edited to match appropriately. 
![image](https://user-images.githubusercontent.com/34703079/63621526-fbba9f00-c5a8-11e9-9998-6e5903e8efac.png)

Component: Table 

Fundamental Styles version: v0.2.0-rc.89

**Comment by droshev** [comment]
tables were refactored
