### ISSUE TITLE
visual assets for the doc page

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2931]
at the moment we are using different visual assets from different sources:
e.g. https://fundamental-styles.netlify.app/?path=/docs/components-feed-list-and-item--standard is using https://avatars.dicebear.com/api/human/fe.svg?m=6&b=%23f5f0f0&mood[]=surprised

The idea is to craft our own ones and use them.

The main benefits:
- they are local
- they don't change

List of items:
- profile pictures - for avatar https://fundamental-styles.netlify.app/?path=/docs/components-avatar-group--individual-type and https://fundamental-styles.netlify.app/?path=/docs/components-avatar--icon; for bar; for feed input; for feed list
- card images - https://fundamental-styles.netlify.app/?path=/docs/components-card--card-anatomy
- carousel - https://fundamental-styles.netlify.app/?path=/docs/components-carousel--carousel-bottom
- generic tiles - https://fundamental-styles.netlify.app/?path=/docs/components-generic-tiles--generic-tile-sizes
- grid list - https://fundamental-styles.netlify.app/?path=/docs/components-grid-list--none-mode
- list - https://fundamental-styles.netlify.app/?path=/docs/components-list-byline--standard 
- notification - https://fundamental-styles.netlify.app/?path=/docs/components-notifications--primary
- object list - https://fundamental-styles.netlify.app/?path=/docs/components-object-list--object
- shellbar - https://fundamental-styles.netlify.app/?path=/docs/components-shellbar--primary
- user menu - https://fundamental-styles.netlify.app/?path=/docs/components-user-menu--shellbar
-

**Comment by FlorianKoerner** [comment]
DiceBear supports versioning in the API. Then the avatars do not change anymore.

https://avatars.dicebear.com/docs/http-api#versioning

If you need support, please let me know.

**Comment by FlorianKoerner** [comment]
DiceBear supports versioning in the API. Then the avatars do not change anymore.

https://avatars.dicebear.com/docs/http-api#versioning

If you need help, please let me know.

**Comment by droshev** [comment]
The artifacts are already in the repo
