### ISSUE TITLE
Make layout-grid component IE11 compatible 

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-styles#297]
Blocked by https://github.com/SAP/fundamental-styles/issues/296

This article series shows how to do this. https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/

The build changes to the playground in #296 will make this work much easier to accomplish.

**Comment by InnaAtanasova** [comment]
This is being solved here https://github.com/SAP/fundamental-styles/pull/889
