### ISSUE TITLE
RELEASE Defect Hunting for Sprint 78 - New York

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#3004]
List all the findings as thread to this issue. The goal is to check if all components in `styles` section are stable for release.

**Comment by platon-rov** [comment]
Review from [b70e46a5de236bef1498b481c9f4042d0f8d3d27](https://github.com/SAP/fundamental-styles/commit/d942ca0c9525965a5730541ae2182b12cbe78d99)

## Progress Indicator
* Popover should have `0.25rem` of vertical padding
![image](https://user-images.githubusercontent.com/20265336/146771041-f2caa58d-5713-40be-b3b2-2c70377fabf5.png)
* Popover close button touch area should be `1.625rm x 1.5rem`.
![image](https://user-images.githubusercontent.com/20265336/146770787-d9e64ce1-483a-49d0-a440-520e68b3b11e.png)

## Illustrated message
* Component shouldn't have margin top. 
![image](https://user-images.githubusercontent.com/20265336/146777109-61c3a941-e1d7-4628-a73e-5cce949d0555.png)
* Scene illustration should be resizable, dimensions shouldn't be fixed.

## Select 
* Min-width not `5rem`
![image](https://user-images.githubusercontent.com/20265336/146778405-08822d78-13a6-4d2d-8d7b-8c9766cc9c64.png)
![image](https://user-images.githubusercontent.com/20265336/146778494-c9e6d822-8560-44a2-9514-7afc3d699eee.png)
