### ISSUE TITLE
component token doesn't have disabled state

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#309]
The token renders always `x` and the icon is clickable. It would be useful to have a disabled state.

**Comment by stefanoScalzo** [comment]
Completely refactor to reflect fiori3 specs and theming parameters

**Comment by InnaAtanasova** [comment]
will be fixed [#455 ](https://github.com/SAP/fundamental-styles/issues/455)

**Comment by salarenko** [comment]
After rework `Token` has no visual representation of `disabled` state. It has `read-only` state which is represented as standard `Token` with faded font color:
![image](https://user-images.githubusercontent.com/17496353/73940725-44161100-48ec-11ea-904e-6821c193f90f.png)

Unfortunately looks a little bit weird when combined with `selected` state:
![image](https://user-images.githubusercontent.com/17496353/73940805-6871ed80-48ec-11ea-924d-3977df4566e9.png)
