### ISSUE TITLE
Border color, radius and shadow of Menu Component are not as per spec. 

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-styles#318]
**Describe the bug**
Border color, radius and shadow are not as per spec. 
Actual:
![image](https://user-images.githubusercontent.com/53509521/64784671-3f8d3c80-d588-11e9-9dad-bb54d0cb0075.png)

> Is this issue related to a specific component?
Menu component

> What version of the Fundamental Styles are you using?
0.1.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular 7

**To Reproduce**
1. Open https://sap.github.io/fundamental-ngx/menu
2. Inspect element on the fd-menu tag and observe the style values.
3. Observe that they do not match with specs.

**Expected behavior**
(spec link: Invision [specs])(https://sapariba.invisionapp.com/d/#/console/17490319/373158067/preview)
(page history: 24. Sep 05, 2019 at 3:56AM)):
![image](https://user-images.githubusercontent.com/53509521/64784296-6e56e300-d587-11e9-9aae-d584f744665b.png)

**Comment by stefanoScalzo** [comment]
Completely refactor to reflect fiori 3 and theming parameters

**Comment by droshev** [comment]
menu has been refactored
