### ISSUE TITLE
Padding values for menu item name is not as per spec 

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-styles#319]
**Describe the bug**
Padding values for menu item name is not as per spec 
Actual:
![image](https://user-images.githubusercontent.com/53509521/64785107-45375200-d589-11e9-91c3-cdfba1eea0f3.png)

> Is this issue related to a specific component?
Menu component

> What version of the Fundamental Styles are you using?
0.1.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular 7

**To Reproduce**
1. Open https://sap.github.io/fundamental-ngx/menu
2. Inspect element on any menu item and observe the style values.
3. Observe that they do not match with specs.

**Expected behavior**
(spec link: Invision [specs])(https://sapariba.invisionapp.com/d/#/console/17490319/373158067/preview)
(page history: 24. Sep 05, 2019 at 3:56AM)):
![image](https://user-images.githubusercontent.com/53509521/64785039-1ae59480-d589-11e9-9c08-80cc7ceb2111.png)

**Comment by fkolar** [comment]
@droshev can we look at this one?

**Comment by stefanoScalzo** [comment]
Please follow up: https://github.com/SAP/fundamental-styles/issues/318
