### ISSUE TITLE
Spacing between icons for Menu with add-on container is not as per spec

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-styles#320]
**Describe the bug**
Spacing between icons for Menu with add-on container is not as per spec
Actual:
![image](https://user-images.githubusercontent.com/53509521/64785374-d6a6c400-d589-11e9-81fa-620e494c389a.png)

> Is this issue related to a specific component?
Menu component

> What version of the Fundamental Styles are you using?
0.1.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular 7

**To Reproduce**
1. Open https://sap.github.io/fundamental-ngx/menu
2. Inspect element on the menu item with add-on icons and observe the style values when hovered over icon and it's surrounding element.
3. Observe that they do not match with specs.

**Expected behavior**
(spec link: Invision [specs])(https://sapariba.invisionapp.com/d/#/console/17490319/373158067/preview)
(page history: 24. Sep 05, 2019 at 3:56AM)):
![image](https://user-images.githubusercontent.com/53509521/64785268-9b0bfa00-d589-11e9-87a9-e6ed548c1829.png)

**Comment by stefanoScalzo** [comment]
Please follow: https://github.com/SAP/fundamental-styles/issues/318
