### ISSUE TITLE
Styling for active, hover, disabled, etc states are not as per spec

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-styles#321]
**Describe the bug**
Styling for active, hover, disabled, etc states are not as per spec
Actual: for Hover:
![image](https://user-images.githubusercontent.com/53509521/64785489-1c638c80-d58a-11e9-9fe9-562190455a09.png)

> Is this issue related to a specific component?
Menu component

> What version of the Fundamental Styles are you using?
0.1.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular 7

**To Reproduce**
1. Open https://sap.github.io/fundamental-ngx/menu
2. Hover over any menu item, keep it selected, or observe hover on a selected item.
3. Observe that they do not match with specs. For example, for Hover, text should turn bold as well.

**Expected behavior**
(spec link: Invision [specs])(https://sapariba.invisionapp.com/d/#/console/17490319/373158067/preview)
(page history: 24. Sep 05, 2019 at 3:56AM)):
![image](https://user-images.githubusercontent.com/53509521/64785453-05bd3580-d58a-11e9-8105-3d3710326ff5.png)

**Comment by fkolar** [comment]
@droshev do you think you somebody can check this out?

**Comment by stefanoScalzo** [comment]
Please follow: https://github.com/SAP/fundamental-styles/issues/318
