### ISSUE TITLE
Fundamental Styles and ui5 webcomponents visual comparison for Fiori 3

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#3214]
The goal:
- [x] Compare Fundamental Styles and Web Components - Inna: created a website where we have Fund-styles components next to ui5 web components side by side. 

**The comparison is done for the following components:**
- Button (no SegmentedButton, no MenuButton, maybe ToggleButton)
- CheckBox
- RadioButton
- Input
- Label
- ComboBox
- Select (no Menu)
- Link
- Card
- Panel
- Switch
- Slider
- TextArea
- IconTabBar / TabContainer (optional component)

- [ ] list the discrepancies against Fiori 3 design
repo in tools/ui

**Comment by InnaAtanasova** [comment]
done
