### ISSUE TITLE
new blog - how to use fundamental-styles in an application

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#3243]
It would be very useful to have a blog explaining how to use fundamental-styles in a web application

**Comment by ynnenu** [comment]
https://medium.com/fundamental-library/getting-started-with-fundamental-library-styles-in-vue-project-6a344ff4d16d
https://medium.com/fundamental-library/getting-started-with-fundamental-library-styles-in-angular-project-7bad71446f89
https://medium.com/fundamental-library/getting-started-with-fundamental-library-styles-in-react-project-2e417c893f84
