### ISSUE TITLE
Input type checkbox remain empty when we click on them

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-styles#326]
**Describe the bug**
The input type checkbox with class fd-checkbox remain empty when we click on them.

**Is this issue related to a specific component?**  
input type checkbox

**What version of the Fundamental Styles are you using?**  
0.2.0

**To Reproduce**
1. Create a input type checkbox and apply class="fd-checkbox"
2. Click on input
3. See error
Or see the eror directly on the doc

**Desktop (please complete the following information):**
 - OS: fedora 30
 - Browser: Chrome 77.0.3865.75

**Comment by jbadan** [comment]
Working on a fix for this in a branch right now :) Sorry for the regression!
