### ISSUE TITLE
Release notes not being published

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-styles#33]
Release notes should look like the following: https://github.com/SAP/fundamental-react/releases/tag/v0.5.3

![Screen Shot 2019-06-07 at 8 36 14 AM](https://user-images.githubusercontent.com/29607818/59116016-5d9b2f00-88ff-11e9-901f-ed2d674f34b8.png)

This is being created by github-assistant, using the Changelog and github API, which require standard-version >=`4.4.0`. Unfortunately, we've had to lock on `4.2.0`. 

When attempting to upgrade any higher than `4.2.0`, we encounter errors in Travis environment. Depending on the version, we get different variations of the same error: 
`Command failed: git commit --no-verify CHANGELOG.md -m "chore(release): version 0.1.0-rc.3 build 64 [ci skip]"`
Not only is that failing, but it's skipping bumping the version in `package.json` and `package-lock.json`. 

This does not happen on the other fundamental-* repos, using the exact same scripts, travis environment, standard-version version, etc. 

See: 
https://travis-ci.com/SAP/fundamental-styles/builds/114492798
https://travis-ci.com/SAP/fundamental-styles/builds/114465152

I believe it's related to these issues in standard-version, but I'm not sure how else to debug this as everything works locally, just not in Travis:
https://github.com/conventional-changelog/standard-version/issues/256
https://github.com/conventional-changelog/standard-version/issues/231

I think the root of the problem might be the changes made in `4.3.0` related to the skip argument: https://github.com/conventional-changelog/standard-version/blob/master/CHANGELOG.md#430-2018-01-03

**Comment by droshev** [comment]
it happens to `fundamental-ngx` now

**Comment by jbadan** [comment]
fixed by https://github.com/SAP/fundamental-styles/pull/864
