### ISSUE TITLE
NPM package, unpkg and Message page issue

### ISSUE THREAD

**Issue by StanZGenchev** [SAP/fundamental-styles#3300]
**Describe the bug**

When I use the npm package (either locally of through unpkg) and try to render `fd-message-page`, I get an empty page with a missing icon (screenshot 1). However, if I build fundamental-styles locally and copy the dist folder over the dist folder from the npm package, it starts working (screenshot 2).
The code I use is 100% identical from the documentation.
A quick comparison between the local dist folder and the npm package dist folder reveals that in the local dist folder, all the css widgets also have a specific theme css (for example `bar-sap_fiori_3.css`) along with the generic one (`bar.css`).
The unpkg link from the "Introduction" documentation page does not work:
```
<link href='https://unpkg.com/fundamental-styles@0.23.0/dist/fundamental-styles-sap_fiori_3.css' rel='stylesheet'>
```

It says that the file does not exist. When I install the npm package locally and inspect its contents, I don't find the theme files either.

This is the html code for the message page:

```html
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Test</title>
    <link type="text/css" rel="stylesheet" href="/node_modules/fundamental-styles/dist/fundamental-styles.css" />
    <link type="text/css" rel="stylesheet" href="/node_modules/fundamental-styles/dist/theming/sap_fiori_3.css" />
    <link type="text/css" rel="stylesheet" href="/node_modules/@sap-theming/theming-base-content/content/Base/baseLib/sap_fiori_3/css_variables.css" />
    <!-- For SAP fonts and icons: -->
    <link type="text/css" rel="stylesheet" href="theme.css" />
  </head>
  <body>
    <div class="fd-message-page">
      <div class="fd-message-page__container">
        <div class="fd-message-page__icon-container">
          <i role="presentation" class="sap-icon--search fd-message-page__icon"></i>
        </div>
        <div role="status" aria-live="polite" class="fd-message-page__content">
          <div class="fd-message-page__title">
            No matching items found.
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
```

This code works when I replace the dist folder from the npm package with the dist folder from my local build. Just adding the `*-sap_fiori_3`, `*-sap_fiori_3_dark`, `*-sap_fori_3_light_dark`, `*-sap_fiori_3_hcb`, `*-sap_fori_3_hcw` and `*-sap_horizon` css files to the dist folder does not work, the generic ones have to be replaced as well, so I think there is something wrong with the general css files found in the npm package.

> Is this issue related to a specific component?

I know it affects `fd-message-page` but it could possibly affect others.

> What version of the Fundamental Library Styles are you using?

0.23.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

I'm working on Eclipse Dirigible. It's not critical but it would be nice to have a fix before April 24th.

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

AngularJS

**To Reproduce**
1. Create a project and `npm install fundamental-styles@0.23.0 @sap-theming/theming-base-content`
2. Paste the example code into index.html
3. Start a web server (`python3 -m http.server`)
4. Open the localhost page and see the missing icon.
5. Build fundamental-styles locally
6. Copy the generated dist folder and replace the dist folder in the fundamental-styles npm package
7. Reload the localhost page and see the icon

**Screenshots:**
Screenshot 1:
![Screen Shot 2022-04-07 at 5 22 24 PM](https://user-images.githubusercontent.com/82379274/162222195-f16c8654-33e6-4836-a5e3-a86b4b61f696.png)

Screenshot 2:
![Screen Shot 2022-04-07 at 5 22 36 PM](https://user-images.githubusercontent.com/82379274/162222242-11e33563-1191-4670-82c9-34c853c7211b.png)

**Desktop:**
 - OS: macOS 12.3.1, Fedora Linux 35
 - Browser: Firefox 98, Chrome 100

**Comment by StanZGenchev** [comment]
Further testing revealed that the icon is there but for some reason, there is a difference in the local and npm css files.

Local build:
```css
.fd-message-page__icon [class*="sap-icon"],
.fd-message-page__icon[class*="sap-icon"] {
  ...
  opacity: 50%;
}
```

NPM package:
```css
.fd-message-page__icon [class*="sap-icon"],
.fd-message-page__icon[class*="sap-icon"] {
  ...
  opacity: 1%;
}
```

This is essentially making the icon invisible.

**Comment by droshev** [comment]
@StanZGenchev you are very right: for some reason the CDN [version](https://unpkg.com/browse/fundamental-styles@0.23.0/dist/fundamental-styles.css) for message page icon(class `fd-message-page__icon`) sets the opacity to 1% instead to 50% as it is in the [src](https://github.com/SAP/fundamental-styles/blob/5f537c486f07433d0b4b2cabd53cad77ab314a0c/src/styles/message-page.scss#L56). We will investigate further and come back to you.

**Comment by droshev** [comment]
It looks like the issue is from the minification step with cssnano  [issue](https://github.com/cssnano/cssnano/issues/1064)

**Comment by g-cheishvili** [comment]
Also, I would like to add that in [cdn description](https://62321868e020b7000831b1da--fundamental-styles.netlify.app/?path=/docs/introduction--overview#cdn) we have only `https://unpkg.com/fundamental-styles/dist/fundamental-styles.css`, without theme name in file name, that is after finally dropping IE11 support, which was deprecated while ago.
[this is small example of usage](https://stackblitz.com/edit/web-platform-mhy2hh?file=index.html). Although here I typed strictly 50% of opacity with inline styling, bear in mind that it is not a solution I'm proposing, it's just for the demonstration.
