### ISSUE TITLE
switch SAP Icons font file when the user changes the themes

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#3324]
The npm package theming-base-content offers 2 variants of sap-icons:
- pre-horizon [variant](https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/baseTheme/fonts/SAP-icons.woff)
- horizon [variant](https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_horizon/fonts/SAP-icons.woff)
Both of them have the same icon set/names, just the design is different (e.g. wrench)
<img width="145" alt="Screen Shot 2022-04-12 at 13 34 00" src="https://user-images.githubusercontent.com/4380815/163020825-10e25b15-0e20-485a-a1c7-20e814c97d81.png">
<img width="153" alt="Screen Shot 2022-04-12 at 13 33 53" src="https://user-images.githubusercontent.com/4380815/163020830-d342674d-324d-4bf1-933e-3aa889d72051.png">

The goal is to swap the sap-icon font file when the user switches between Fiori 3 and Horizon themes.

Also it is good to document that the applications have the choice to use either of the font files or even alternate in case of theming change

NGX related [issue](https://github.com/SAP/fundamental-ngx/issues/7981)

**Comment by StanZGenchev** [comment]
> Both of them have the same icon set/names, just the design is different (e.g. wrench)

No, I don't think they are the same.

For example, let's use `sap-icon--status-positive` and `sap-icon--status-negative`.

When I use the "baseTheme", I get this:

![Screen Shot 2022-04-13 at 11 15 53 AM](https://user-images.githubusercontent.com/82379274/163132664-5f3cc0c2-7715-45fa-a523-8834948424e9.png)

But when I switch to the "sap_horizon" variant, I get this:

![Screen Shot 2022-04-13 at 11 16 08 AM](https://user-images.githubusercontent.com/82379274/163132775-f3b6a5b8-8986-4cfa-ba63-2b5d1ae151fa.png)

The positive icon looks like a checkbox and I don't think it's intended to be that way. Initially, I thought that the old baseTheme is out of development and is kept for legacy/compatibility reasons, but if they indeed have to be the same, just with a different design, as you claim, then this is most probably a bug with the font. I'm not sure if there should be an issue here or over at the "theming-base-content" repo (or somewhere else).

I remember that there are more icons like this, some didn't even appear if I remember correctly. I could investigate further if you want me to.

**Comment by droshev** [comment]
> status-positive

@StanZGenchev the icons are them same but some of the icons have new design
old [design](https://60f9800f4fb67b0008a97ea0--fundamental-styles.netlify.app/?path=/docs/components-icons-sap-icons--sizes)
new [design](https://fundamental-styles.netlify.app/?path=/docs/components-icons-sap-icons--available-icons)

**Comment by droshev** [comment]
We switched to Horizon as default. If someone wants to support Quartz they can import the older version of the icons
