### ISSUE TITLE
Javascript error in Fundamental Library documentation

### ISSUE THREAD

**Issue by rubiyz** [SAP/fundamental-styles#3326]
When accessing the documentation at https://sap.github.io/fundamental-styles, it is not possible to see the "Components > Table" information. The page stays blank and a javascript error is displayed in the console. "TypeError: loadedComponentStyles[componentName] is undefined"

**To Reproduce**
1. Go to https://sap.github.io/fundamental-styles/?path=/docs/components-table--advanced-toolbar
2. See error in browser console (TypeError: loadedComponentStyles[componentName] is undefined)

**Expected behavior**
To see the documentation related to the Table component

**Desktop (please complete the following information):**
 - OS: at least Windows + Linux
 - Browser: Chromium + Firefox + Edge
 - Version: Edge 100.0.1185.39, Firefox 99.0.1, Chromium 100.0.4896.88

**Comment by droshev** [comment]
@rubiyz we are aware that the documentation has this error. While we will release a fix you can access the backup [link](https://fundamental-styles.netlify.app/?path=/docs/components-table--advanced-toolbar)
