### ISSUE TITLE
Before release Defect Hunting + Bug fixes

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#3327]
- [ ] Test the components in all themes before the Horizon release.
- [ ] Distinguish the release blockers
- [ ] Bug fixes

Browsers for testing:
- [ ] Firefox - @g-cheishvili 
- [ ] Edge - @platon-rov 
- [ ] Chrome - @InnaAtanasova 
- [ ] Safari - @N1XUS 

Themes for testing:
- [ ] Quartz Light or Dark
- [ ] Horizon Morning
- [ ] Horizon Evening
- [ ] HCB for Horizon or HCW for Horizon

RTL and LTR testing too

Components for testing:
- [ ] Avatar
- [ ] Icons
- [ ] Busy Indicator
- [ ] Button Components - Badge on Button 
- [ ] Button Components - Button 
- [ ] Button Components - Button Shortcuts
- [ ] Button Components - Menu Button
- [ ] Button Components - Segmented Button
- [ ] Button Components - Toggle Button 
- [ ] Calendar Components - Date Picker 
- [ ] Checkbox
- [ ] Dialog and Popover Components - Dialog 
- [ ] Dialog and Popover Components - Popover
- [ ] Dialog and Popover Components - Message Box 
- [ ] Toolbar and Bar
- [ ] Input Components - Combobox 
- [ ] Input Components - Input Field
    - [ ] Step Input 
    - [ ] Input Group
- [ ] Input Components - Multi Input and Multi Combo
- [ ] Message Strip 
- [ ] Page and Layout
    - [ ] Dynamic Page
    - [ ] Dynamic Side Content
    - [ ] Flexible Column Layout 
    - [ ] Message Page 
    - [ ] Page 
- [ ] Radio Button 
- [ ] Switch
- [ ] Tab Bar
- [ ] Text Components 
- [ ] Cards and Tiles 
- [ ] Shellbar
- [ ] Input Components - Dropdown
- [ ] List View
    - [ ] List 
    - [ ] GridList 
    - [ ] ObjectList 
    - [ ] Table

**Comment by mikerodonnell89** [comment]
- [ ] table - bottom border of the first column in "fixed header" example appears as two lines
![Screen Shot 2022-04-15 at 10 51 25 AM](https://user-images.githubusercontent.com/2471874/163598329-dbac9be8-72f6-4289-baaf-98ba27f38974.png)

**Comment by platon-rov** [comment]
* [ ] - radio, missing borders in horizon themes, issue created on theming-base-content's side, https://github.com/SAP/theming-base-content/issues/10

<img width="126" alt="image" src="https://user-images.githubusercontent.com/20265336/165094247-f45ecb3c-6bbf-4b43-953f-f3cf0d354ebc.png">

**Comment by droshev** [comment]
- [ ] https://github.com/SAP/fundamental-styles/issues/3361

**Comment by droshev** [comment]
- [ ] Avatar Group RTL any theme / any browser
![Screen Shot 2022-05-07 at 08 22 35](https://user-images.githubusercontent.com/4380815/167254256-2f1fad05-7e97-440b-803c-3de5b2bfc124.png)
![Screen Shot 2022-05-07 at 08 21 38](https://user-images.githubusercontent.com/4380815/167254258-85f14004-d2cf-4597-ae7f-06798d74fbbb.png)

**Comment by platon-rov** [comment]
* [ ] Link, Horizon, text underline is absent in hc themes
<img width="150" alt="image" src="https://user-images.githubusercontent.com/20265336/167271324-cffaf883-0e5c-4895-90eb-8f6fe9194fb8.png">

**Comment by N1XUS** [comment]
- [ ] Calendar page: strange line 
<img width="430" alt="image" src="https://user-images.githubusercontent.com/6586561/167400922-f2d36704-f886-41c0-b786-1cb940530de2.png">

**Comment by InnaAtanasova** [comment]
- [ ] Avatar - Chrome | HCB Horizon | Tile Icon Background example

The icon is not visible.
(Morning Horizon)
<img width="1224" alt="Screen Shot 2022-05-09 at 2 19 46 PM" src="https://user-images.githubusercontent.com/39598672/167472599-8195d890-8e1c-49fa-93f3-b2686f84e4f0.png">

(HCB Horizon)
<img width="1225" alt="Screen Shot 2022-05-09 at 2 19 37 PM" src="https://user-images.githubusercontent.com/39598672/167472601-2206d639-9933-442a-9617-942cc2c79ced.png">

**Comment by InnaAtanasova** [comment]
- [ ] Busy Indicator - Chrome 
Wrong colors for Morning & Evening Horizon

Fundamental-styles:
<img width="1231" alt="Screen Shot 2022-05-09 at 2 32 02 PM" src="https://user-images.githubusercontent.com/39598672/167474657-c88c1447-23ca-40e6-a1f5-89ec34bfc1dd.png">
<img width="1226" alt="Screen Shot 2022-05-09 at 2 31 26 PM" src="https://user-images.githubusercontent.com/39598672/167474664-124bdd35-758d-4277-82ba-6e4aed4aab1c.png">

Design specs:
<img width="689" alt="Screen Shot 2022-05-09 at 2 31 49 PM" src="https://user-images.githubusercontent.com/39598672/167474718-56a5edec-34e0-4960-ac76-c1f9c67a6294.png">

**Comment by InnaAtanasova** [comment]
- [ ] Radio Button Focus 
Fund-styles:
<img width="153" alt="Screen Shot 2022-05-09 at 3 15 06 PM" src="https://user-images.githubusercontent.com/39598672/167481488-1b045376-75c2-446e-b645-8118272e2295.png">

Design specs:
<img width="347" alt="Screen Shot 2022-05-09 at 3 15 34 PM" src="https://user-images.githubusercontent.com/39598672/167481518-665360e5-443c-4a9f-a4be-a42ee7e956ac.png">

**Comment by InnaAtanasova** [comment]
- [ ] Menu 
Down state has a white focus and the specs don't.

Fund-styles:
<img width="576" alt="Screen Shot 2022-05-09 at 3 54 58 PM" src="https://user-images.githubusercontent.com/39598672/167487888-cee8a614-8e5e-4e1f-b152-cfe830ab492a.png">

Specs:
<img width="175" alt="Screen Shot 2022-05-09 at 3 57 42 PM" src="https://user-images.githubusercontent.com/39598672/167487935-0f665586-8632-4909-a413-71dd401192c2.png">

**Comment by InnaAtanasova** [comment]
- [ ] Product Switch
The focus in active state should be white:
<img width="630" alt="Screen Shot 2022-05-09 at 4 45 52 PM" src="https://user-images.githubusercontent.com/39598672/167495583-0df17e91-739e-46ca-89ce-dd0e16740b40.png">

**Comment by InnaAtanasova** [comment]
- [ ] ShellBar 
ShellBar actions (buttons) have dark focus. Should be white (contrast color)
<img width="642" alt="Screen Shot 2022-05-09 at 6 38 30 PM" src="https://user-images.githubusercontent.com/39598672/167510629-2d6601da-bc25-4d90-8716-4d26d4f1a499.png">

**Comment by InnaAtanasova** [comment]
- [ ] Switch
On Switch toggling the focus outline "flickers".  The correct behaviour can be seen at BTP implementation: https://fundamental-styles.netlify.app/?path=/docs/btp-experimental-design-toggles--checkbox&globals=theme:sap_horizon;fioriVersion:fioriNext

<img width="182" alt="Screen Shot 2022-05-09 at 6 58 12 PM" src="https://user-images.githubusercontent.com/39598672/167511997-c33c985e-472d-46bd-9ee1-419dbd3a7830.png">

**Comment by InnaAtanasova** [comment]
-  [ ] User Menu search is broken
<img width="375" alt="Screen Shot 2022-05-09 at 7 05 54 PM" src="https://user-images.githubusercontent.com/39598672/167512690-1fbeb82b-a480-46e6-a7b7-6242a54877d2.png">
<img width="385" alt="Screen Shot 2022-05-09 at 7 05 43 PM" src="https://user-images.githubusercontent.com/39598672/167512692-8dab6a07-53b0-47ac-8433-433c5c29e152.png">
<img width="374" alt="Screen Shot 2022-05-09 at 7 05 37 PM" src="https://user-images.githubusercontent.com/39598672/167512693-a38584f9-8e25-45e4-8e46-9797b5ab6054.png">

**Comment by platon-rov** [comment]
* [ ] Wizard

* Horizon, label text should be bold, optional text should have gray color
Current:
<img width="139" alt="Screenshot 2022-05-08 at 16 36 19" src="https://user-images.githubusercontent.com/20265336/167298755-5030c01f-182a-4fd5-9eff-30e622b26a5c.png">
Specs:
<img width="140" alt="image" src="https://user-images.githubusercontent.com/20265336/167298779-3153696a-5f26-4728-a4ea-ee31492490b4.png">

* Horizon, current tab label in mobile mode shouldn't have blue color
Current:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/20265336/167298917-e385a0fe-7302-4b93-93b3-8174b1c0fdb9.png">
Specs:
<img width="154" alt="image" src="https://user-images.githubusercontent.com/20265336/167298924-c5546ded-55b2-47c1-8c7c-35fb62577fbe.png">

* Fiori, label should have grey color
Current:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/20265336/167299342-d664f43e-db0e-4788-8d03-06b0a0c70227.png">
Specs:
<img width="149" alt="image" src="https://user-images.githubusercontent.com/20265336/167299351-fad424a3-b35c-4974-81b6-7470d2441c1b.png">

**Comment by platon-rov** [comment]
* [ ] Vertical navigation isn't support Horizon

<img width="269" alt="image" src="https://user-images.githubusercontent.com/20265336/167580966-4d730b9b-626c-48f4-b8cc-8d0da611a9cf.png">

**Comment by platon-rov** [comment]
* [ ] Tree, Fiori/Horizon, HC. Focus on the expanders look quite different from all other elements. Also state active is missing. However i didn't find how it should look like, probably we should ask designers about it.
<img width="97" alt="image" src="https://user-images.githubusercontent.com/20265336/167389541-2ff44908-df94-4317-8859-4e639d343e6d.png">
<img width="101" alt="image" src="https://user-images.githubusercontent.com/20265336/167389370-434d08c4-67c3-4d2b-a2c8-fb65b93774c1.png">

**Comment by platon-rov** [comment]
* [ ] Tokenizer should have border in HC themes.
Current:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/20265336/167582621-4a0726c7-3051-4740-be60-3a554dd966cb.png">
Specs:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/20265336/167582674-bfdeffbc-9dea-4eaa-8c96-bfb7032d8eff.png">

**Comment by platon-rov** [comment]
* [ ] Tabs, HC, not enough contrast
<img width="233" alt="image" src="https://user-images.githubusercontent.com/20265336/167587369-e5fd8207-ae45-4968-abbc-9dbe1f1ce068.png">

To be honest i didn't find specifications for this component, in the wiki i only found: Icon Tab Bar, Multi-Instance TabContainer, Wizard. In case Tabs component were renamed to Icon Tab Bar we should also deprecate Tabs.

**Comment by platon-rov** [comment]
* [ ] Shellbar, not correct border in active state. All the properties should be inherited from the transparent button, except overwritings. Transparent button should be used instead default button.

<img width="83" alt="image" src="https://user-images.githubusercontent.com/20265336/167591833-994403a8-e71d-4e37-bcab-38f96417eaa1.png">

**Comment by platon-rov** [comment]
* [ ] Select, HC, no hover state on button (dropdown toggler)
<img width="117" alt="image" src="https://user-images.githubusercontent.com/20265336/167596772-c0dfa5a3-2a35-4197-9827-c8ffa3d29f80.png">

**Comment by platon-rov** [comment]
* [ ] Grid List, HC, filter bar, border should persist on hover/active

<img width="85" alt="image" src="https://user-images.githubusercontent.com/20265336/167604903-8d665d5a-ecd7-4b40-b742-2a5cf8c7ce9b.png">

**Comment by g-cheishvili** [comment]
[Counter](https://fundamental-styles.netlify.app/?path=/docs/components-counter--notifier&globals=theme:sap_horizon) colors does not seem right in HC themes and in Horizon, Mozilla

![image](https://user-images.githubusercontent.com/28543391/167609049-6a7c4f14-ee9e-4033-b180-65562148b1f2.png)

**Comment by N1XUS** [comment]
Slider:
Wrong styling:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/6586561/167639996-8ca48b21-615f-4a17-993c-e081afc61ffb.png">

**Comment by g-cheishvili** [comment]
![image](https://user-images.githubusercontent.com/28543391/167663669-818f44b8-8d6a-4ebf-a74b-2a4c718190bd.png)
Line is over icon

**Comment by g-cheishvili** [comment]
![image](https://user-images.githubusercontent.com/28543391/167672699-613c90f8-b22f-4f9b-88bc-b7baf24050dc.png)

User menu search input is not vertically centered and top border is either not visible, either does not exist

**Comment by g-cheishvili** [comment]
> * [ ]  table - off-centered checkboxes on table columns with checkboxes (cozy mode)
> 
> <img alt="Screen Shot 2022-04-15 at 10 53 20 AM" width="143" src="https://user-images.githubusercontent.com/2471874/163598485-b0856e65-b673-498d-b1f6-e4faa39435ba.png">
> 
> <img alt="Screen Shot 2022-05-07 at 14 33 52" width="2000" src="https://user-images.githubusercontent.com/4380815/167267328-4013645e-e59f-44fb-a82c-ccdc4aa8c899.png">
> 
> <img alt="Screen Shot 2022-05-07 at 14 34 21" width="342" src="https://user-images.githubusercontent.com/4380815/167267342-49ea8107-50c6-42a5-8aca-5f0e54993460.png">
> 
> * [ ]  table - bottom border of the first column in "fixed header" example appears as two lines
>   ![Screen Shot 2022-04-15 at 10 51 25 AM](https://user-images.githubusercontent.com/2471874/163598329-dbac9be8-72f6-4289-baaf-98ba27f38974.png)

Checkboxes was more of checkbox issue, rather then table one. Labelless checkboxes should have been without margin, which visually results with incorrect placement not only here, but across other components where it was used

**Comment by platon-rov** [comment]
* [ ] Micro Process Flow, some icons not visible in hc themes

<img width="210" alt="image" src="https://user-images.githubusercontent.com/20265336/168770978-3b83915f-2ffd-4a07-a7f6-feb6303e549b.png">

**Comment by N1XUS** [comment]
- [ ] Horizontal navigation (Fiori). Wrong icon colors
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/6586561/168792105-ae87f709-e5b3-4d5c-985b-96886d53ec8a.png">

**Comment by platon-rov** [comment]
* [ ] Layout Grid, nested rows broken gap https://github.com/SAP/fundamental-styles/pull/3448

![image](https://user-images.githubusercontent.com/20265336/169372303-cb1e97bd-250f-41ff-b764-7a3e5f72c2dd.png)

**Comment by mikerodonnell89** [comment]
- [ ] Vertical navigation, incorrect focus outlines
<img width="304" alt="Screen Shot 2022-05-19 at 3 00 18 PM" src="https://user-images.githubusercontent.com/2471874/169403858-5deb9f47-0069-48d0-9d78-845a4ce1a159.png">
<img width="286" alt="Screen Shot 2022-05-19 at 3 00 15 PM" src="https://user-images.githubusercontent.com/2471874/169403860-b458f3c6-721a-4bd0-9f16-62dab565ec14.png">

**Comment by mikerodonnell89** [comment]
- [ ] Horizontal nav focus
![Uploading Screen Shot 2022-05-19 at 4.00.54 PM.png…]()

**Comment by g-cheishvili** [comment]
[ ] - Readonly Textarea is focusable for some reason, with mouse click

![image](https://user-images.githubusercontent.com/28543391/169594313-5ac782b2-ff7e-4e6e-aa57-368152a4b94f.png)

**Comment by g-cheishvili** [comment]
- [ ] Horizon Tile should have border radius of 1 rem(it's 0.75 now)
![image](https://user-images.githubusercontent.com/28543391/169595497-63d10442-59de-4702-a88f-dbf819469e1b.png)

**Comment by g-cheishvili** [comment]
- [ ] Tiles focus and hover states are not correct. Box shadow is missing in Horizon

**Comment by g-cheishvili** [comment]
- [ ] Icon tab bar dropdown focus outline border radius does not seem right
![image](https://user-images.githubusercontent.com/28543391/169596839-e4c1c2b9-ca6f-4e19-b374-cc3c7cadfcce.png)

**Comment by g-cheishvili** [comment]
- [ ] Menu selected item's focus
![image](https://user-images.githubusercontent.com/28543391/169688510-8cadf2e6-8782-4e2d-8bd8-5a20ee620479.png)

Distance between outline and bottom border should be bigger

**Comment by g-cheishvili** [comment]
- [ ] readobly step input is focusable with mouse

**Comment by g-cheishvili** [comment]
- [ ] Input readonly state placeholder not visible
![image](https://user-images.githubusercontent.com/28543391/169696244-36d5348e-5080-4373-877e-e70b93ecfe44.png)
![image](https://user-images.githubusercontent.com/28543391/169696256-846d6078-ded4-415f-b546-46a92452d5ba.png)

**Comment by platon-rov** [comment]
* [ ] No text shadow on the link elements, but it's mentioned in specs.

**Comment by platon-rov** [comment]
* [ ] Tokenizr, Multi Input. Somewhere text and somewhere else link is used.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/20265336/169761518-fd564972-ac95-465d-b754-4df1b2d2f397.png">
