### ISSUE TITLE
Input Group multiple addon buttons not quite aligned properly in compact mode

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-styles#333]
## Description
For input groups with multiple addon buttons (number input spinner), they are not quite lining up properly in compact mode.  See screenshot below (from fundamental-react's docs site) for an example.
![Screen Shot 2019-09-17 at 11 32 55 AM](https://user-images.githubusercontent.com/11407353/65061318-4aa4eb80-d93f-11e9-9267-b75f6bfcd456.png)

**Comment by droshev** [comment]
is this still valid?
