### ISSUE TITLE
Browser compatibility  issue: In IE11 with windows OS

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#339]
**Describe the bug**
Styles are not reflecting when the application is opened in IE- 11.55.17763.0 browser 
of windows machine.

> Is this issue related to a specific component?
observed for all the listed components in fundamental-ngx
> What version of the Fundamental Styles are you using?
latest
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
App-framework, we have a release plan in Jan-2020
> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**To Reproduce**
1. Go to windows and open IE browser
2. Open https://sap.github.io/fundamental-ngx/
3. Check the css for all the components

**Expected behavior**
CSS should reflect consistent irrespective of browser and OS used by the customer.
**Screenshots**

![3B6C423B](https://user-images.githubusercontent.com/53487468/65234421-289f9a80-daf2-11e9-9bdf-eff672d3a771.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]-windows
 - Browser [e.g. chrome, safari]- IE
 - Version [e.g. 22]-11

**Comment by salarenko** [comment]
Styles are now cross browser compatible. Particular inconsistencies are reported as separate issues.
