### ISSUE TITLE
Reduce output size

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/fundamental-styles#3393]
In fundamental styles, we no longer have support for IE11, so now we can get rid of the SASS variables and replace them with CSS variables it will reduce code size drammatically and increase readability. Context based variables would not have need to have additional selectors to change style of the elements. Modifiers can ONLY contain CSS variables.

[Here is the example commit](https://github.com/SAP/fundamental-styles/commit/8321e0bae0a82ea57ea7fe2dc4e2cd3a46e9a53e)

**Comment by droshev** [comment]
@g-cheishvili 
- [ ] Can you list all the files where we should do that refactoring

**Comment by droshev** [comment]
We are doing that in steps while bringing Horizon design updates (#4403).
