### ISSUE TITLE
Bug: button text alignment on localizationEditor

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-styles#34]
![Screen Shot 2019-06-07 at 9 25 30 AM](https://user-images.githubusercontent.com/29607818/59118907-40b62a00-8906-11e9-8e6a-1db299d45a6e.png)

"EN" Text on button is not center aligned like it was in fundamental < 1.5.3.

**Comment by rengare** [comment]
Issue is already fixed 
![image](https://user-images.githubusercontent.com/10849982/70638016-754dca00-1c38-11ea-84e9-40982d2030e1.png)

**Comment by salarenko** [comment]
Issue has been fixed. (Cross browser check)
