### ISSUE TITLE
Popover overlay sizing issue on docs site

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-styles#344]
It appears the popover overlays are being sized to match the width of the reference element, however, in a number of cases, that's less than optimal.  See screenshot:

![Screen Shot 2019-09-24 at 10 22 36 PM](https://user-images.githubusercontent.com/11407353/65566986-26867300-df1a-11e9-868a-f48fc8f736a6.png)

**Comment by salarenko** [comment]
Has been fixed with latest releases.
