### ISSUE TITLE
Text Components

### ISSUE THREAD

**Issue by vmasl-s** [SAP/fundamental-styles#3449]
**Link** Active/Down behaves weirdly by switching to Focus state when pressed. 
**Morning/Evening Horizon** 
Subtle Link, Default state should have an underline.

**High Contrast Black and White**
Regular, Inverted, Emphasized, Subtle in Default, Disabled, Visited states need an underline. Hover and Active states no underline.

**Comment by InnaAtanasova** [comment]
These issues were fixed in PR 3409 and now not reproducible. Closing the issue.
