### ISSUE TITLE
Table with fixed column is not styled correctly

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-styles#345]
When viewing the "Table with Fix Column Header and context menu" example on the **Table** page on the docs site, the fixed column appears transparent causing styling issues when scrolling horizontally.  See screenshot.

![2019-09-24 22 27 28](https://user-images.githubusercontent.com/11407353/65567174-d22fc300-df1a-11e9-84b0-bffccb0772cd.gif)

**Comment by droshev** [comment]
we refactored this component
