### ISSUE TITLE
Horizon/Quartz Smoke testing

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#3495]
- [ ] Test the components in all themes before the Horizon release.
- [ ] Distinguish the release blockers
- [ ] Bug fixes

Browsers for testing:
- [ ] Firefox - @g-cheishvili 
- [ ] Edge - @platon-rov 
- [ ] Chrome - @InnaAtanasova 
- [ ] Safari - @N1XUS 

Themes for testing:
- [ ] Quartz Light or Dark
- [ ] Horizon Morning
- [ ] Horizon Evening
- [ ] HCB for Horizon or HCW for Horizon

RTL and LTR testing too

Components for testing:
- [ ] Avatar
- [ ] Icons
- [ ] Busy Indicator
- [ ] Button Components - Badge on Button 
- [ ] Button Components - Button 
- [ ] Button Components - Button Shortcuts
- [ ] Button Components - Menu Button
- [ ] Button Components - Segmented Button
- [ ] Button Components - Toggle Button 
- [ ] Calendar Components - Date Picker 
- [ ] Checkbox
- [ ] Dialog and Popover Components - Dialog 
- [ ] Dialog and Popover Components - Popover
- [ ] Dialog and Popover Components - Message Box 
- [ ] Toolbar and Bar
- [ ] Input Components - Combobox 
- [ ] Input Components - Input Field
    - [ ] Step Input 
    - [ ] Input Group
- [ ] Input Components - Multi Input and Multi Combo
- [ ] Message Strip 
- [ ] Page and Layout
    - [ ] Dynamic Page
    - [ ] Dynamic Side Content
    - [ ] Flexible Column Layout 
    - [ ] Message Page 
    - [ ] Page 
- [ ] Radio Button 
- [ ] Switch
- [ ] Tab Bar
- [ ] Text Components 
- [ ] Cards and Tiles 
- [ ] Shellbar
- [ ] Input Components - Dropdown
- [ ] List View
    - [ ] List 
    - [ ] GridList 
    - [ ] ObjectList 
    - [ ] Table

**Comment by droshev** [comment]
Carryover from #3327
- [ ] #3477 
- [ ] #3465
- [ ] #3474
- [ ] Tree, Fiori/Horizon, HC. Focus on the expanders look quite different from all other elements. Also state active is missing. However i didn't find how it should look like, probably we should ask designers about it.
<img width="97" alt="image" src="https://user-images.githubusercontent.com/20265336/167389541-2ff44908-df94-4317-8859-4e639d343e6d.png">
<img width="101" alt="image" src="https://user-images.githubusercontent.com/20265336/167389370-434d08c4-67c3-4d2b-a2c8-fb65b93774c1.png">


**Create a separate issue for future testing and integration with ngx**

**Comment by N1XUS** [comment]
Button: Icon & text example is broken
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/6586561/171161967-91b56691-9b93-45df-81ea-639d74cc05cb.png">

**Comment by N1XUS** [comment]
Horizon carousel: text is not filly visible
<img width="415" alt="image" src="https://user-images.githubusercontent.com/6586561/171162274-0dc37fd9-9c56-4318-9450-395caf8dc6c0.png">

**Comment by InnaAtanasova** [comment]
- [ ] Menu focus issues (Horizon)
<img width="681" alt="Screen Shot 2022-06-01 at 4 25 17 PM" src="https://user-images.githubusercontent.com/39598672/171495226-d86f7221-dc0d-4da2-be6a-a1a56dd41b4e.png">
<img width="688" alt="Screen Shot 2022-06-01 at 4 25 12 PM" src="https://user-images.githubusercontent.com/39598672/171495229-89ddac23-ab20-41be-96be-ff0752798a20.png">

- [ ] Disabled Menu element gets a focus:
<img width="560" alt="Screen Shot 2022-06-01 at 4 24 49 PM" src="https://user-images.githubusercontent.com/39598672/171495271-1d1343ad-075b-44a1-bf15-d716603471d4.png">

**Comment by InnaAtanasova** [comment]
- [ ] Micro Process Flow - focus issue:
<img width="1108" alt="Screen Shot 2022-06-01 at 4 43 51 PM" src="https://user-images.githubusercontent.com/39598672/171499030-b5a9f543-8e65-48ef-95ae-ed164db18212.png">

**Comment by InnaAtanasova** [comment]
- [ ] Rating indicator focus issue

Fund-styles:
<img width="266" alt="Screen Shot 2022-06-01 at 4 55 39 PM" src="https://user-images.githubusercontent.com/39598672/171499986-2c49bce1-25dc-44a4-ad90-9bcb023398db.png">


Should be:
<img width="133" alt="Screen Shot 2022-06-01 at 4 55 35 PM" src="https://user-images.githubusercontent.com/39598672/171500043-8b6ebdba-d815-4c69-a6ef-d4a12a65c2fc.png">
<img width="248" alt="Screen Shot 2022-06-01 at 4 55 30 PM" src="https://user-images.githubusercontent.com/39598672/171500048-814db20c-882f-45b4-a11c-2ea1585e80b3.png">

**Comment by InnaAtanasova** [comment]
- [ ] Select (Horizon) - the focus for the menu elements (first and last element) should be consistent with the Menu and List.

Select (Horizon)
<img width="400" alt="Screen Shot 2022-06-01 at 4 57 12 PM" src="https://user-images.githubusercontent.com/39598672/171500351-bfb899e8-eac0-46b4-852c-26889eeff849.png">
<img width="198" alt="Screen Shot 2022-06-01 at 4 57 21 PM" src="https://user-images.githubusercontent.com/39598672/171500354-1c414dcb-6be7-4a69-a564-712ada98750f.png">

Menu (Horizon)
<img width="379" alt="Screen Shot 2022-06-01 at 4 58 55 PM" src="https://user-images.githubusercontent.com/39598672/171500536-4a0126d1-1396-4a72-8de4-3b0118d74fe8.png">
<img width="367" alt="Screen Shot 2022-06-01 at 4 58 51 PM" src="https://user-images.githubusercontent.com/39598672/171500538-79cb4015-0246-412c-b2ca-6dbf4176d5d2.png">

**Comment by mikerodonnell89** [comment]
Combobox and multi input button focus outline needs a border radius

![Screen Shot 2022-06-01 at 4 53 34 PM](https://user-images.githubusercontent.com/2471874/171514794-0de5c579-0f94-41eb-bee2-cdb97742ad4f.png)

**Comment by g-cheishvili** [comment]
> * [ ]  Progress Indicator - issue when the bar is at 0% (Horizon)
> 
> <img alt="Screen Shot 2022-06-01 at 4 47 42 PM" width="536" src="https://user-images.githubusercontent.com/39598672/171499241-4fab1091-412d-4d40-ab2c-d2586eb51ce3.png">

This can not be solved in CSS

**Comment by N1XUS** [comment]
> > * [ ]   Progress Indicator - issue when the bar is at 0% (Horizon)
> > 
> > <img alt="Screen Shot 2022-06-01 at 4 47 42 PM" width="536" src="https://user-images.githubusercontent.com/39598672/171499241-4fab1091-412d-4d40-ab2c-d2586eb51ce3.png">
> 
> This can not be solved in CSS

You can use aria-attribute for value and apply needed styling

**Comment by N1XUS** [comment]
Horizon progress indicator:
100% width is not completely a 100% width:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/6586561/171646664-c6cd069a-07dd-4964-85a2-1a4f22bcacae.png">

**Comment by mikerodonnell89** [comment]
- [ ] Upload collection with long text - save/edit buttons get vertically stacked
![Screen Shot 2022-06-02 at 11 40 46 AM](https://user-images.githubusercontent.com/2471874/171692539-5381d5e6-75a8-4224-b422-3e604854b4cc.png)

**Comment by InnaAtanasova** [comment]
- [ ] Breadcrumb does not have an underline on hover

**Comment by g-cheishvili** [comment]
> * [ ]  Breadcrumb does not have an underline on hover

I think breadcrumb link element should go. There is no need for it, that is exactly what fd-link is

**Comment by mikerodonnell89** [comment]
- [ ] tool header - button edges are cut off
![Screen Shot 2022-06-03 at 10 16 44 AM](https://user-images.githubusercontent.com/2471874/171905166-09ff7db5-82fd-424d-a65b-9ea38c2d488f.png)
![Screen Shot 2022-06-03 at 10 16 47 AM](https://user-images.githubusercontent.com/2471874/171905171-35fe1ba5-1a9b-4aa6-be33-7d1a24ed63f3.png)

**Comment by mikerodonnell89** [comment]
- [ ] shellbar - popover not aligned (all themes)
![Screen Shot 2022-06-03 at 11 40 10 AM](https://user-images.githubusercontent.com/2471874/171917710-a39d0355-4311-4130-9079-5dbef3bc84cc.png)

**Comment by mikerodonnell89** [comment]
- [ ] Horizon icon tab bar is missing separators also causing broken focus outline on menu item
fiori:
![Screen Shot 2022-06-03 at 12 21 21 PM](https://user-images.githubusercontent.com/2471874/171923597-0982b577-7211-4f84-a0b5-755cfd876a28.png)

horizon:
![Screen Shot 2022-06-03 at 12 21 42 PM](https://user-images.githubusercontent.com/2471874/171923611-15f6dbbf-36a5-4147-88eb-56b94a7ddb64.png)

**Comment by mikerodonnell89** [comment]
- [ ] card with list - incorrect focus outline. I'll work on this one
![Screen Shot 2022-06-03 at 2 57 53 PM](https://user-images.githubusercontent.com/2471874/171952606-c309a956-a0dd-4c04-9e52-59a8007f70c8.png)

**Comment by N1XUS** [comment]
> * [ ]  shellbar - popover not aligned (all themes)
>   ![Screen Shot 2022-06-03 at 11 40 10 AM](https://user-images.githubusercontent.com/2471874/171917710-a39d0355-4311-4130-9079-5dbef3bc84cc.png)

@mikerodonnell89 it is actually aligned. Menu trigger has own paddings.
@droshev @InnaAtanasova should we refactor those trigger controls to exclude margins so that popovers would be aligned to the text and not the container?

<img width="296" alt="image" src="https://user-images.githubusercontent.com/6586561/172115236-f1bc585a-7023-4e5b-84a6-a52adcf44566.png">

**Comment by platon-rov** [comment]
* [ ] Avatar Group, no paddings on dropdown's input

<img width="147" alt="image" src="https://user-images.githubusercontent.com/20265336/172124757-689cf63b-9847-444d-967c-4ec6af6b9595.png">

**Comment by platon-rov** [comment]
* [ ] Form Group, group header looks ugly - it has different color than background and doesn't have paddings.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/20265336/172125399-eb36b120-1e98-44de-bc41-74cc061de164.png">

**Comment by mikerodonnell89** [comment]
> * [ ]  Avatar Group, no paddings on dropdown's input
> 
> <img alt="image" width="147" src="https://user-images.githubusercontent.com/20265336/172124757-689cf63b-9847-444d-967c-4ec6af6b9595.png">
> 
> * [ ]  Quick View, no paddings on inputs
> 
> <img alt="image" width="137" src="https://user-images.githubusercontent.com/20265336/172126487-1c9eb6e8-0d72-435a-95a0-1f5e48084373.png">

These shouldn't even have the fd-input class in my opinion

**Comment by platon-rov** [comment]
* [ ] Multi Input, outline margins

<img width="175" alt="image" src="https://user-images.githubusercontent.com/20265336/172330524-26b68f15-fae3-48af-b2a8-6acf2cc7c536.png">

**Comment by mikerodonnell89** [comment]
> @mikerodonnell89 it is actually aligned. Menu trigger has own paddings. @droshev @InnaAtanasova should we refactor those trigger controls to exclude margins so that popovers would be aligned to the text and not the container?
> 
> <img alt="image" width="296" src="https://user-images.githubusercontent.com/6586561/172115236-f1bc585a-7023-4e5b-84a6-a52adcf44566.png">

I think yes for sure

**Comment by mikerodonnell89** [comment]
> * [ ]  Multi Input, outline margins
> 
> <img alt="image" width="175" src="https://user-images.githubusercontent.com/20265336/172330524-26b68f15-fae3-48af-b2a8-6acf2cc7c536.png">

So I agree these look a little weird, but they share the same margins as the focus outlines for the other list items and the same border-radius as the parent popover body element. Screenshot below has forced focus on the elements showing that they all do have the same margins
<img width="1212" alt="Screen Shot 2022-06-07 at 2 36 34 PM" src="https://user-images.githubusercontent.com/2471874/172478690-90e0e19a-a60c-413c-ba70-dd2b7d7cf1b3.png">

**Comment by platon-rov** [comment]
* [ ] Object Marker, wrong focus state. In wiki said to use Link's focus designs.

<img width="172" alt="image" src="https://user-images.githubusercontent.com/20265336/173364377-d0c7bbef-0c25-4c0b-a677-2338509c0917.png">
