### ISSUE TITLE
Search not aligned with Fiori3

### ISSUE THREAD

**Issue by bindhu19** [SAP/fundamental-styles#353]
Hi Team,

The search input in fundamental style is not aligned with the Fiori 3.
Please refer the screenshot.
Do we have a similar kind of search in fundamental-styles? or is it planned?

![image](https://user-images.githubusercontent.com/55971076/65938119-b6a74980-e43f-11e9-9ee4-8a95aa5388d3.png)

**Comment by droshev** [comment]
we are bringing it with https://github.com/SAP/fundamental-styles/issues/1634
