### ISSUE TITLE
Compile fails on SASS latest version

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/fundamental-styles#3532]
**Describe the bug**
Latest version of node-sass(1.52.2) breaks compilation. Needs investigation

**Comment by droshev** [comment]
The topics we need to evaluate:
- evaluate the +/- of `npm`, `yarn`, `pnpm`,.. maybe other package managers
- migrate to `node` v.16 and evaluate the impact for `styles` and `ngx`
