### ISSUE TITLE
Table : Column header font size not matching Fiori UX 

### ISSUE THREAD

**Issue by AdityaKumarSharma** [SAP/fundamental-styles#354]
As per UX : Column Header must be @sapMFontMediumSize/14px
As per below link and provided table css Column Header is 12px

**Describe the bug**

> Is this issue related to a specific component?
This issue is related to Table Component 
https://sap.github.io/fundamental-styles/components/table.html

**Expected behavior**
As per UX the column header text must be of same font size as of cell text i.e. 14px . Follow below link
https://wiki.wdf.sap.corp/wiki/display/visualcore/ResponsiveTable+%28Fiori+3%29+-+Specification

**Screenshots**
As per UX :
![image](https://user-images.githubusercontent.com/33654140/65942603-41da0c80-e44b-11e9-8a3a-1017c8a85791.png)

As per Current style : 
![image](https://user-images.githubusercontent.com/33654140/65942666-6635e900-e44b-11e9-9c0e-b9a3402cdfce.png)

**Comment by droshev** [comment]
we migrated those components. Feel free to open a new issue if you still have some issues.
