### ISSUE TITLE
Table : Border color is not as per Fiori UX

### ISSUE THREAD

**Issue by AdityaKumarSharma** [SAP/fundamental-styles#356]
Table Border must be @sapUIListBorderColor / #e5e5e5 currently it is (#eeeeef ) not as per standards

**Describe the bug**
> Is this issue related to a specific component?
Table Component

**Expected behavior**
Table border color must be @sapUIListBorderColor : #e5e5e5 as per below link
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2144577672#SemanticControlParameters(Fiori3)-SemanticBorderColors

**Comment by droshev** [comment]
the component has been refactored
