### ISSUE TITLE
Bug: Compact Combobox is broken due to new min-height

### ISSUE THREAD

**Issue by JenniferStamm** [SAP/fundamental-styles#3707]
**Describe the bug**
As seen in the screenshot below, the compact Combobox is no longer compact but the same height as the other Comboboxes.

> Is this issue related to a specific component?

I've observed it in Combobox.

> What version of the Fundamental Library Styles are you using?

Observed in [v0.24.1-rc.7](https://github.com/SAP/fundamental-styles/tree/v0.24.1-rc.7)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

No, the issue is not present in v0.24.1-rc.1, so we upgraded to that version instead.

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular

**To Reproduce**
The bug is visible when viewing the current docs of compact combobox:
https://fundamental-styles.netlify.app/?path=/docs/components-forms-input-group--focus#input-with-actions

**Expected behavior**
Combobox height should be compact, same as used for the embedded input element.

**Screenshots**
<img width="720" alt="image" src="https://user-images.githubusercontent.com/7091280/176711881-133b9a87-e33d-44c8-b021-ed4604c13114.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 103.0.5060.53 

**Additional context**
Taking a wild guess, I would assume it was introduced with PR #3699

**Comment by JenniferStamm** [comment]
Similar issue on [Multi Input](https://fundamental-styles.netlify.app/?path=/docs/patterns-multi-input--as-form-item#cozy-and-compact):
<img width="439" alt="image" src="https://user-images.githubusercontent.com/7091280/186866096-d9786e58-b596-4285-bca6-acf91ad98b72.png">
vs. 
<img width="484" alt="image" src="https://user-images.githubusercontent.com/7091280/186866278-a7709290-edb1-4849-9870-3be408c5a15d.png">

**Comment by droshev** [comment]
It seems fixed with the latest fundamental-styles
