### ISSUE TITLE
Horizon input group text alignment issues when there is an addon button

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-styles#3723]
Note the text on the left is not vertically aligned
<img width="1313" alt="Screen Shot 2022-07-11 at 2 22 55 PM" src="https://user-images.githubusercontent.com/2471874/178352147-a48a8fc5-0855-404f-a8b1-ad64f9b18bbf.png">

**Comment by mikerodonnell89** [comment]
- [ ] Horizon - Input group text alignment issues when there is an addon button
<img width="1313" alt="Screen Shot 2022-07-11 at 2 22 55 PM" src="https://user-images.githubusercontent.com/2471874/178352147-a48a8fc5-0855-404f-a8b1-ad64f9b18bbf.png">

**Comment by droshev** [comment]
it is also in F3
