### ISSUE TITLE
Form Input Group messages and read-only state ?

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental-styles#3732]
Could it be that messages and read-only state are available in [Form Input](https://sap.github.io/fundamental-styles/?path=/docs/components-forms-input--primary&globals=theme:sap_horizon) only and not in [Form Input Group](https://sap.github.io/fundamental-styles/?path=/docs/components-forms-input-group--focus&globals=theme:sap_horizon) ?

Both controls are used the same way and read-only and error message for invalid input for example can be used in Form Input Group as well.

Are they really missing or only example not provided? I added readonly attribute for input group input field but no effect.

**Comment by InnaAtanasova** [comment]
Hi @bsrdjan ,
you can add readonly state to Input Group like this:
```
<div class="fd-form-item">
    <label class="fd-form-label" for="aqwsde132">Read-Only</label>
    <div class="fd-input-group is-readonly">
        <input class="fd-input fd-input--compact fd-input-group__input" readonly type="text" id="aqwsde132" name="" value="1000000">
        <span class="fd-input-group__addon fd-input-group__addon--compact fd-input-group__addon--button">
            <button class="fd-input-group__button fd-button fd-button--transparent fd-button--compact">
                Button
            </button>
        </span>
    </div>
</div>
```

This will result in:
<img width="839" alt="Screenshot 2022-12-08 at 2 20 53 PM" src="https://user-images.githubusercontent.com/39598672/206547906-ba4b9bcb-e672-4caa-bd64-b9ae7b96b176.png">

I added this to the documentation example.
As for state messages, you need to wrap the input group in popover control class and the message in popover body, like this:


```
<div class="fd-form-item">
    <label class="fd-form-label" for="aqwsde127">Error compact</label>
    <div class="fd-popover">
        <div class="fd-popover__control" aria-expanded="true" aria-haspopup="true">
            <div class="fd-input-group is-error">
                <input class="fd-input fd-input--compact fd-input-group__input" type="text" placeholder="Placeholder" id="aqwsde127" name="" value="1000000">
                <span class="fd-input-group__addon fd-input-group__addon--button fd-input-group__addon--compact">
                    <button class="fd-input-group__button fd-button fd-button--transparent fd-button--compact">
                        Button
                    </button>
                </span>
            </div>
        </div>
        <div class="fd-popover__body fd-popover__body--input-message-group fd-popover__body--no-arrow" aria-hidden="false" id="popoverB2">
            <div class="fd-form-message fd-form-message--error">Error message</div>
        </div>
    </div>
</div>
```
