### ISSUE TITLE
Focus outline not rendered on Safari

### ISSUE THREAD

**Issue by reinholdk** [SAP/fundamental-styles#374]
**Describe the bug**
Focus outline is not rendered on Safari

> Is this issue related to a specific component?
Multiple components: Breadcrumb, Link, Switch, ...

> What version of the Fundamental Styles are you using?
0.2.0

**To Reproduce**
Prerequisite: enable Tab key navigation: _Safari -> Preferences -> Advanced -> Press Tab to highlight each item on a webpage_

Press the Tab key to navigate to a control, e.g. a link

**Expected behavior**
Focus outline shall be rendered

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 12.1.2

**Comment by reinholdk** [comment]
Using an outline offset, e.g: `outline-offset: -2px` seems to make the outline appear. Shall I create a PR?

**Comment by salarenko** [comment]
Focus is now rendered on Breadcrumb element.
![image](https://user-images.githubusercontent.com/17496353/74833449-c275a880-5319-11ea-9494-249f39233ce6.png)
