### ISSUE TITLE
Accessibility Plugin ?

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental-styles#3750]
Would it make sense to add Storybook accessibility plugin and have more detailed insight into accessibility compliance? 
https://storybook.js.org/addons/@storybook/addon-a11y

Now there is A11Y badge (in different colours?) and I could not find out how to interpret it
<img width="48" alt="Screenshot 2022-07-22 at 22 57 31" src="https://user-images.githubusercontent.com/1697847/180567517-0b73e682-147d-4e8e-9a78-970fe9ec90a9.png">

**Comment by droshev** [comment]
Actually we have this already
