### ISSUE TITLE
Fiori Horizon Date-picker

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental-styles#3756]
We are using Fundamental Styles for Fiori Horizon date-picker and the [scope described on storybook](https://sap.github.io/fundamental-styles/?path=/docs/patterns-date-picker--default-and-compact-sizes&globals=theme:sap_horizon) works fine.

In storybook I could not find styles for following parts of [Fiori Horizon date-picker design specification - mixed calendar]:

- Month selection
- Year selection
- Range selection
- Mixed calendar

Is there a roadmap when these parts of specification will be added? Thanks in advance!

**Comment by droshev** [comment]
will be done with https://github.com/SAP/fundamental-styles/issues/3868
