### ISSUE TITLE
contextual-menu: menu list width truncated

### ISSUE THREAD

**Issue by reinholdk** [SAP/fundamental-styles#376]
**Describe the bug**
The menu list width gets truncated to almost the width of the triggering button.

> Is this issue related to a specific component?
contextual-menu

> What version of the Fundamental Styles are you using?
0.3.0

**To Reproduce**
1. Go to https://sap.github.io/fundamental-styles/patterns/contextual-menu.html
2. Click on one of the buttons

**Expected behavior**
Menu list shall not be truncated.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, firefox

**Comment by salarenko** [comment]
Should be fixed with #473
