### ISSUE TITLE
Dynamic Page and content inside - margin review

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#3781]
Let's review the implementation of the margins/responsive margins in dynamic page. We got some reports they are not following 100% the specs (e.g. Dynamic Page with tabs and a table inside one of the tabs)

**Comment by platon-rov** [comment]
Yea, I see that Table has negative margins but I don't see where the specs for that.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/20265336/183643848-777df184-3661-4595-8517-e337aef64ae4.png">

Asked designers about it, waiting for a response.
