### ISSUE TITLE
pagination label ie, fd-pagination__per-page-label is not displayed.

### ISSUE THREAD

**Issue by Harshithaharsh** [SAP/fundamental-styles#3795]
pagination label ie, fd-pagination__per-page-label is not displayed.
![image](https://user-images.githubusercontent.com/28975951/184073962-b38cbcdc-a586-4c59-820c-dccce25a5093.png)
**Expected behavior:** 
![image](https://user-images.githubusercontent.com/28975951/184074063-e021476a-c5b7-4f34-b5d4-35f6d7296ffd.png)

**Comment by droshev** [comment]
@Harshithaharsh where did you take this component. Our pagination look a bit different https://fundamental-ngx.netlify.app/#/core/pagination

**Comment by Harshithaharsh** [comment]
Hi @droshev . This is the instance you can just log in through below credentials and check SFPaginator https://qacand.hcm.ondemand.com/xi/ui/uicore/pages/testFD.xhtml?component=SFPaginator&supportedFioriVersion=4&contentDensity=compact
Login details: companyID - RCMGoldenApp4
username: cgrant
password: pwd.

**Comment by Harshithaharsh** [comment]
Hi @droshev , Any updated?

**Comment by Harshithaharsh** [comment]
The issue is not related to fundamental styles so closing the issue.
