### ISSUE TITLE
Calendar day format has one letter for the day instead of three (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-styles#3799]
According to the [specs for the Calendar in Horizon](https://wiki.one.int.sap/wiki/display/visualcore/Calendar+%28Horizon%29+-+Legend), the days should be in this format (Sun, Mon... instead of S,M...)

**Comment by InnaAtanasova** [comment]
When using fund-styles the user has a full control over the content. They can use `M` or `Mon` or `MON`. Here's how the calendar would look like if the user provided 3 letters.
<img width="594" alt="Screen Shot 2022-08-18 at 3 19 43 PM" src="https://user-images.githubusercontent.com/39598672/185476825-4b040015-3522-4305-926a-ef9b7bb6ffc0.png">

In fund-ngx we have the exact same format as in the specs:
<img width="298" alt="Screen Shot 2022-08-18 at 3 22 48 PM" src="https://user-images.githubusercontent.com/39598672/185477351-fbbb8123-3f55-4683-8bca-56312f8c7ba6.png">
