### ISSUE TITLE
Design for Component Carousel needed

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#38]
### Component name
> Carousel

@LeoT7508 @jeannewalters Could you provide a design for Carousel per Fiori 3 specification?

**Comment by MattL75** [comment]
Any progress on this? I designed an API architecture for it already, it's just missing some visual.

**Comment by LeoT7508** [comment]
@droshev @MattL75 

I can't make any progress on any of these new design tickets until you provide some more information. We have nothing to go off of right now. Also, like I mentioned before isn't it more important for us to finish/update what we have in the library now vs. starting new components that teams aren't using?
