### ISSUE TITLE
Carousel: Navigation button size is incorrect (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-styles#3801]
According to the [Morning Horizon Carousel Specs](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698913168), the navigation button size should be 2.125 rem with 0.25 rem padding on top and at the bottom.

**Comment by InnaAtanasova** [comment]
<img width="1375" alt="Screen Shot 2022-08-18 at 1 53 42 PM" src="https://user-images.githubusercontent.com/39598672/185462102-d9dc8cfe-c188-49cf-8d8c-93f4dc2a0c8a.png">

Hi @obc514 that's correct, the size of the button is 2.125rem which translates to 34px. As you can see from the screenshot the button in Carousel is 34px and has 4px (0.25rem) padding around it. Is there anything I am missing?

**Comment by obc514** [comment]
@InnaAtanasova I stand corrected. I will close this issue.
