### ISSUE TITLE
combobox: row height is greater than the 2.5 rem specified (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-styles#3802]
Row height is greater than the 2.5 rem [specified ](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698913232)(Morning Horizon)

**Comment by InnaAtanasova** [comment]
Hi @obc514 what do you mean by row? The link you provided is for ComboBox and there I can't see anything mentioned about 2.5rem

The "touch" height of the input control is 40px (2.5rem) and the input itself is 36px (2.25rem)
<img width="1439" alt="Screen Shot 2022-08-18 at 1 34 19 PM" src="https://user-images.githubusercontent.com/39598672/185458759-c999ef3b-f738-45bd-9b23-44ec5cbe2a74.png">

Here's how it's per specs:
<img width="762" alt="Screen Shot 2022-08-18 at 1 36 03 PM" src="https://user-images.githubusercontent.com/39598672/185459358-41f64b21-63ed-49dd-8530-96d1b2c0d32f.png">

The bottom margin is 0 when the body (list) is open.

As for the body, it's constructed using the List component and the List item height is 2.75rem

**Comment by obc514** [comment]
@InnaAtanasova I think what is misleading is that the hover state on items that aren't selected exceeds the item height. I had a look at these [specs](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698913522) and it looks like you are following the same approach but what is misleading is that in the [UI5 cozy implementation](https://sapui5nightly.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.ComboBox/sample/sap.m.sample.ComboBox), the hover state or highlighted row doesn't exceed 40px. That's why the fundamental implementations stand out a bit.

**Comment by InnaAtanasova** [comment]
> UI5 cozy implementation

@platon-rov could you check, please?
