### ISSUE TITLE
Feed List Item does not correspond to specs (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-styles#3803]
Feed List Item does not correspond to [specs ](https://wiki.one.int.sap/wiki/display/visualcore/Feed+%28Horizon%29+-+FeedListItem)(Morning Horizon)

**Comment by InnaAtanasova** [comment]
Hi @obc514 , thanks for opening this issue. Could you provide a few examples of Feed List Item not corresponding to the specs. Thank you!

**Comment by obc514** [comment]
Feed list item from specs
<img width="425" alt="image" src="https://user-images.githubusercontent.com/111069252/185491399-27ab671a-6c19-4fc4-bc65-c75dfab92345.png">
Feed list from Styles
<img width="626" alt="image" src="https://user-images.githubusercontent.com/111069252/185491631-f308d22e-5410-4aba-8590-daf115f904aa.png">
