### ISSUE TITLE
Splitter pagination button margin visual issue

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-styles#3814]
Found while defect hunting fundamental-ngx. Splitter, pagination example - no margin between these two buttons, most apparent in high contrast horizon modes.

![Screen Shot 2022-08-15 at 4 35 38 PM](https://user-images.githubusercontent.com/2471874/184732390-a2ce4f1d-2215-4b36-97c7-3a197aca47ae.png)

**Comment by InnaAtanasova** [comment]
There's nothing in the specs that specify the spacing between the buttons. 
UI5 also doesn't have spacing:

![Screenshot 2022-12-01 at 3 29 10 PM](https://user-images.githubusercontent.com/39598672/205153552-9116b4a1-cf19-435e-86d3-bffa9401ee1a.png)
