### ISSUE TITLE
0.24.4 - Toolbar of type Transparent has non-transparent background in Horizon themes

### ISSUE THREAD

**Issue by winterkind** [SAP/fundamental-styles#3815]
**Describe the bug**
In the Horizon theme, a Toolbar component of type Transparent has a non-transparent background.

**To Reproduce**
1. Go to https://sap.github.io/fundamental-styles/iframe.html?globals=theme:sap_horizon&viewMode=docs&id=components-toolbar--alignment#types
2. Check the toolbar of type Transparent - it is not transparent

**Expected behavior**
A toolbar of type Transparent should have a transparent background, like it has in the Quartz themes.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome and Firefox

**Comment by droshev** [comment]
@winterkind it may sound funny, but the design for toolbar type Transparent in Horizon is not transparent.
