### ISSUE TITLE
Side Navigation - CX design implementation

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#3841]
Update the current Side Nav design with the new design updates from CX.
- [x] Update the component, document any breaking changes
- [x] Create a separate package, which will be used for more CX specific components
- [x] include Side Nav as part of this package
- [x] update storybook so the user can see the CX package as another select item(like BTP)

**Comment by bsrdjan** [comment]
Could you please share the link of current Side Nav design? Perhaps it fits our project as is.

**Comment by droshev** [comment]
> Could you please share the link of current Side Nav design? Perhaps it fits our project as is.

https://fundamental-styles.netlify.app/?path=/docs/components-cx-side-navigation--cozy-wide-icons
