### ISSUE TITLE
Can't see sap-icon on mobile devices

### ISSUE THREAD

**Issue by ilanitfh** [SAP/fundamental-styles#3854]
Hi. We’re trying to use the Fundamental Styles icons in our ReactJS project wrapping in Cordova. This is our code:
<div className="fddocs-container">
    <div className="fddocs-container--icon">
        <span className="sap-icon sap-icon--search" style={{fontSize: "20px"}} />
        <div>.sap-icon--search</div>
    </div>
</div>
we added the following include:
import 'fundamental-styles/dist/icon.css';
We can see the icon in the browser but can’t see it on iOS and Android mobile devices.
On iOS devices we can see the wrong icon and on Android we can’t see the icon at all. Can you please advise? Thanks

**Comment by droshev** [comment]
not sure what we can do for that. the icon font file should be accessible on the application side and it is out of our control
