### ISSUE TITLE
Design for Component Wizard needed

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#39]
@LeoT7508 @jeannewalters Could you provide a design for Wizard per Fiori 3 specification?

**Comment by droshev** [comment]
The idea is to start implementing it in few weeks.

**Comment by LeoT7508** [comment]
Design sheet can be found here:
https://zpl.io/aw66LNM

**Comment by LeoT7508** [comment]
@droshev 

You are going to give me access to edit these tickets and  permissions for this project on Github so I can update status etc.
