### ISSUE TITLE
Minor alignment issue on Tables and Lists 

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental-styles#393]
**Describe the bug**
Minor alignment issue on `table` and `list` when used within a `panel` with `panel-body` set to `[bleed]='true'`

> Is this issue related to a specific component?
table and list 

> What version of the Fundamental Styles are you using?
fundamental-ngx 0.9.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
cloud portal

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
angular 

**Expected behavior**
Table cell content and list item text should align with the panel header text. 

**Screenshots**
<img width="352" alt="Screen Shot 2019-10-25 at 9 42 41 AM" src="https://user-images.githubusercontent.com/15215400/67582038-a4eb5600-f70e-11e9-9f88-9b163a235edf.png">
<img width="363" alt="Screen Shot 2019-10-25 at 9 58 20 AM" src="https://user-images.githubusercontent.com/15215400/67582039-a4eb5600-f70e-11e9-8cc5-9e4a01908b85.png">

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser: chrome
 - Version: latest

**Comment by droshev** [comment]
old component
