### ISSUE TITLE
fd-overlay--modal uses .is-hidden instead of aria-hidden="true"

### ISSUE THREAD

**Issue by MichaelSp** [SAP/fundamental-styles#399]
According to [the doc](https://sap.github.io/fundamental-styles/layouts/shell-layout.html) this is how you should use the overlay:

```html
<div class="fd-shell__overlay fd-overlay fd-overlay--modal" aria-hidden="true">
```

but according to [the code](https://github.com/SAP/fundamental-styles/pull/291/files#diff-97af6451760e899cee9ca23e6a32b23d) (which cannot lie) it works like this

```html
<div class="fd-shell__overlay fd-overlay fd-overlay--modal is-hidden">
```

Who is right?

**Comment by salarenko** [comment]
Overlay display should be controlled with CSS class.
In upcoming version Fundamental Styles Modal is going to be replaced with Dialog component with integrated overlay triggered by adding `is-active` class.
