### ISSUE TITLE
Design for Component Toolbar needed

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#40]
@LeoT7508 @jeannewalters Could you provide a design for Toolbar per Fiori 3 specification?

**Comment by LeoT7508** [comment]
@droshev 

What Toolbar are u referring to? Do you have an example? We need some reference to design from.

**Comment by droshev** [comment]
@LeoT7508 
Example: `Footer Toolbar`, `Solid Toolbar`, `Title Toolbar`
