### ISSUE TITLE
Inverted Object Status - issue with shadow

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-styles#4027]
The icon (SAP-Icons Font) and the text (72 Font) size should be 12px. According to the [Visual Core](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698914826), the shadow on the text should be: sapContent_ContrastTextShadow. Please check all the characteristics in the specs to ensure consistency.

**Comment by droshev** [comment]
the [issue](https://github.com/SAP/fundamental-ngx/issues/8968) in ngx - make sure to bring the changes in ngx
