### ISSUE TITLE
Styled Tooltip for Button (and other components)

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#4042]
![Screenshot 2022-11-23 at 2 05 36 PM](https://user-images.githubusercontent.com/39598672/203627882-1ecfaaf8-a9dd-48bd-8328-fcb8b487d736.png)

The new design for File Uploader asks for styled Tooltip to buttons. This task is to:
- [ ] discuss if we should add this feature
- [ ] if we agree to implement it, plan it for one of the next sprints

**Comment by droshev** [comment]
Let's close it for now as we have a workaround
