### ISSUE TITLE
Contextual menu in the demo app is cut off

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-styles#408]
**Describe the bug**
On the https://sap.github.io/fundamental-styles/patterns/contextual-menu.html, when testing contextual menu, they are cut off. please see the screenshot.

**To Reproduce**
Go to the https://sap.github.io/fundamental-styles/patterns/contextual-menu.html
**Desktop (please complete the following information):**
 - OS: 
 

**Smartphone (please complete the following information):**

<img width="820" alt="Screen Shot 2019-10-31 at 2 40 03 PM" src="https://user-images.githubusercontent.com/17149942/67988261-acb66900-fbec-11e9-8666-9143fcd2578b.png">

**Comment by droshev** [comment]
The issue has been fixed in version `0.4.0`
