### ISSUE TITLE
JUCE fundamental components

### ISSUE THREAD

**Issue by renlite** [SAP/fundamental-styles#4082]
On "Fundamental Conf 22" I saw that you are supporting the C++ JUCE FW.
Where can I find the components or more information about the wrapped components?

**Comment by droshev** [comment]
@renlite i am not sure whether I understand what you are looking for. Can you share more details?

**Comment by renlite** [comment]
Conf22:
![image](https://user-images.githubusercontent.com/64831420/206672609-e3b2001a-3003-4732-9f5e-475cc54d6881.png)

**Comment by droshev** [comment]
@renlite Can you point to which presentation contained that? I guess there was a mistake or something.

**Comment by renlite** [comment]
https://www.youtube.com/watch?v=AP-rKiKozVM

**Comment by droshev** [comment]
Actually, Irla was referring as a library that is being used in some applications. We don't have fundamental components for it.
