### ISSUE TITLE
When on smaller device the main menu is not responsive (Bug)

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-styles#409]
**Describe the bug**

When I open documentation on smaller device and click on the hamburger menu -> components I am unable to scroll down the components all components. 

<img width="505" alt="Screen Shot 2019-11-01 at 10 01 35 AM" src="https://user-images.githubusercontent.com/17149942/68041887-d6c06780-fc8e-11e9-9532-008ce7f16ca0.png">

**Comment by droshev** [comment]
it was fixed
