### ISSUE TITLE
bug(docs): fragile js

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-styles#4166]
#### Example

The JS code we have in docs for interactivity is fragile, here is the one of many examples

https://user-images.githubusercontent.com/20265336/211361842-da157e45-2ffd-4b9b-b0b7-6119551671ed.mov

When input focused with keyboard - form message shows, it's okay, but then when it's focused with mouse - behavior is odd.

### Description 
There is no sense to have interactivity in docs for HTML-CSS-only library because of

1. We don't expose JS code to have this interactivity, and we don't have to as we're HTML-CSS-only library!
2. **Chromatic cannot catch all the states**

Solutions

1. Easy. Remove interactivity and show all the states statically
2. Hard. [Add `play` function to at least catch all the states with Chromatic.](https://www.chromatic.com/docs/hoverfocus)

**Comment by g-cheishvili** [comment]
Hard is actually "harder", because then we will have to also align with storyshots?

**Comment by platon-rov** [comment]
> Hard is actually "harder", because then we will have to also align with storyshots?

Exactly, removing is easy, adding is hard. And I don't think we should add `play` it's too hard and and showing states statically is the better option for us.
