### ISSUE TITLE
button: compact button height is not matching with Fiori3 standards

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#417]
**Describe the bug**
fundamental-ngx/core compact button height is not as per Fiori3 standards.

> Is this issue related to a specific component?
       Button component

> What version of the Fundamental Styles are you using?
       0.3.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**Expected behavior**

- compact button height should be 26px including border.

**Screenshots**
In fundamental-ngx

<img width="363" alt="Screen Shot 2019-11-07 at 2 21 09 PM" src="https://user-images.githubusercontent.com/53487468/68374004-ff060580-0169-11ea-80b0-fb29ed85719c.png">

In Fiori3

<img width="579" alt="Screen Shot 2019-11-07 at 2 21 42 PM" src="https://user-images.githubusercontent.com/53487468/68374011-04fbe680-016a-11ea-82bb-4fa4c5c89844.png">

**Comment by trilodge** [comment]
same holds true for inputs.

Based on _settings.scss -> $fd-forms-height--compact: $fd-spacing--base * 7 !default; // 28px 

New modifier would be 6.5 to achieve 26px.

**Comment by droshev** [comment]
@sKudum how about the buttons here https://fundamental-styles.netlify.com/components/button.html

**Comment by droshev** [comment]
@stefanoScalzo could you check @sKudum point?
