### ISSUE TITLE
Component 'Status Indicator Label with Semantic Colors' has inconsistent color

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-styles#418]
This is a UX bug. Please refer to the Fundamental Styles page for the component 'Status Indicators':
https://sap.github.io/fundamental-styles/components/status-indicators.html

(1) For the status indicator components 'Badge' and 'Label' the default color grey is mentioned in the text. But in fact the 'Information' blue is shown, e.g. for the option 'Draft'.
--> Either adjust the text or - ideally - provide the component with both colors.

(2) The component 'Status Indicator Label with Semantic Colors' uses grey instead, no blue. But according to the Fiori 3 Visual Style Guide, the semantic color pallet has five colors:
...
--> Please provide the component 'Status Indicator Label with Semantic Colors' with all five semantic colors to allow consistency.

**Comment by droshev** [comment]
Status Indicator has been deprecated - its successors are  InfoLabel and ObjectStatusCoponent
