### ISSUE TITLE
Could we Support SAP Belize theming, since it in SAP Fiori design guide line

### ISSUE THREAD

**Issue by Vita-Meow** [SAP/fundamental-styles#4239]
**Is your feature request related to a problem? Please describe.**

> Is this issue related to a specific component?

> What browser are you working in?

> What version of Fundamental Library Styles are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by droshev** [comment]
Belize is a theme that was created long before Fundamental Library has been created. You can still apply the Belize theming parameters and they will work, but the components won't be 100% according to the specs
