### ISSUE TITLE
Message strip icon

### ISSUE THREAD

**Issue by ZsDeak-SAP** [SAP/fundamental-styles#4240]
**Describe the bug**
If on the consumer side we want a bigger message strip, and so we define a height for the element width `fd-message-strip--warning fd-message-strip` on it for example, then the icon is not positioned with the text. 

> Is this issue related to a specific component?
yes, message-strip

> What version of the Fundamental Library Styles are you using?
latest/master

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**To Reproduce**
`<p class="fd-message-strip--warning fd-message-strip">`
`p { height: 70px;}`

**Expected behavior**
Icon is aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/115458873/217585854-d3faa576-d7d9-40e5-83b1-048ea9ad290b.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Additional context**
I think [top](https://github.com/SAP/fundamental-styles/blob/main/packages/styles/src/message-strip.scss#L20) is not needed at all, but I might miss some use-cases, for me it works without it.

**Comment by droshev** [comment]
@ZsDeak-SAP the visual specification sets the icon in absolute position from the top/left corner:
<img width="353" alt="Screenshot 2023-02-11 at 2 19 45 PM" src="https://user-images.githubusercontent.com/4380815/218277144-a68133cd-6d8c-4bcf-9ab0-9c827cb94d57.png">

And what you see is expected
