### ISSUE TITLE
fd-form-item in horizontal mode not aligned

### ISSUE THREAD

**Issue by ChristianKienle** [SAP/fundamental-styles#425]
<img width="273" alt="Screenshot 2019-11-14 at 17 23 32" src="https://user-images.githubusercontent.com/153225/68875713-91c31900-0703-11ea-844b-53821cbdefb4.png">

(Can also be seen in the official docs)

**Comment by ChristianKienle** [comment]
I talked to @InnaAtanasova in Slack. While doing so it became apparent that this bug report is ambiguous. It is not clear which alignment this bug report talks about.

The image below is the same as above but now has an alignment guide added to it which shows what I mean:

![dd](https://user-images.githubusercontent.com/153225/68924149-57e42800-0780-11ea-8090-311e9b4276c5.png)

The other alignment that is a bit off is this one:

![dd](https://user-images.githubusercontent.com/153225/68924241-9974d300-0780-11ea-8e2a-2469ee4ce6ae.png)

So the alignment is off in both directions – but originally I was only talking about the first alignment issue.

**Comment by droshev** [comment]
is this still valid?
