### ISSUE TITLE
search suggestion list rendering broken starting with v0.39.0-rc.26

### ISSUE THREAD

**Issue by littleamigo** [SAP/fundamental-styles#4255]
In DXP we added suggestion to the search field recently and it worked very well for a few weeks with a [fix](https://github.com/SAP/fundamental-ngx/issues/9199) provided with v0.39.0-rc.13. Since a few days we see a significant regression as the suggestion list is rendered far off the search control. I was able to nail it down to v0.39.0-rc.26 and discussed/pre-analyzed it shortly with @N1XUS. He asked me to open this ticket to follow up.

I tried but failed to provide a StackBlitz example because it uses v0.38.x and my attempt to upgrade to v0.39.x failed.

I just tried again with latest versions, same problem:
“@fundamental-ngx/core”: “0.39.0-rc.38",
“@fundamental-ngx/moment-adapter”: “0.39.0-rc.38",
“@fundamental-ngx/platform”: “0.39.0-rc.38",
“fundamental-styles”: “0.27.0-rc.8",

I appreciate your understanding that I cannot add a screenshot here as it would comprise too much SAP specific and personal data. Please contact @N1XUS and ask to share what he already got from me via Slack if you need it in case you cannot reproduce it on your own.

**Comment by droshev** [comment]
@IB002 Can you check whether the issue is still reprodicible?

**Comment by IB002** [comment]
Not reproducible in newer versions 

Screenshots:

<img width="2331" alt="Screenshot 2023-07-20 at 10 23 54 AM" src="https://github.com/SAP/fundamental-styles/assets/132930816/4926de36-4a03-497c-ab64-d18e22b4aa27">

**Comment by littleamigo** [comment]
Good to hear it's been resolved in newer versions. What are these newer versions? I need the exact minimum released version to adopt!

**Comment by IB002** [comment]
The minimum release that you should adopt is v0.40.1.

**Comment by littleamigo** [comment]
I've tried with v0.41.0 and cannot confirm the fix. It looks still broken:
![image](https://github.com/SAP/fundamental-styles/assets/33327256/fa5c239e-a291-40da-9e5d-3e5773f0bf9f)
