### ISSUE TITLE
 Empty table cells break the order of the cells in the table

### ISSUE THREAD

**Issue by mario-fazli** [SAP/fundamental-styles#4256]
**Describe the bug**
**Version:** latest
When having empty headers in table with ```class="fd-table__cell"``` it brakes the header order. For example:

**HTML:**
```html
<table class="fd-table">
   <thead class="fd-table__header">
      <tr class="fd-table__row">
         <th class="fd-table__cell"></th>
         <th style="text-align:left" class="fd-table__cell">Header2</th>
         <th class="fd-table__cell"></th>
         <th class="fd-table__cell">Header4</th>
         <th style="text-align:left" class="fd-table__cell"></th>
      </tr>
   </thead>
   <tbody class="fd-table__body">
      <tr class="fd-table__row fd-table__row--hoverable">
         <td class="fd-table__cell">Text</td>
         <td style="text-align:left" class="fd-table__cell">Text2</td>
         <td class="fd-table__cell">Text3</td>
         <td class="fd-table__cell">Text4</td>
         <td style="text-align:left" class="fd-table__cell">Text5</td>
      </tr>
   </tbody>
</table>
```

**Actual result:**
<img width="752" alt="image" src="https://user-images.githubusercontent.com/93724981/218673356-87d16ebd-bb56-44f2-bf56-65922c02a052.png">

**Expected result:**
| | Header2 |  | Header4  |  |
|----|:----|----|----|:----|
| Text  | Text2 | Text3  | Text4 | Text5 |

**To Reproduce**
Add ```class="fd-table__cell"``` to an empty header in a table

**Expected behavior**
I expect the html to be visualised with the empty headers, so: Header2 is above Text2 and Header4 is above Text4

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 110.0.5481.96

**Comment by droshev** [comment]
@IB002 Can you check whether the issue is reproducible?

**Comment by IB002** [comment]
The issue can't be reproduced on current active versions of chrome

**Code used**
<table class="fd-table">
   <thead class="fd-table__header">
      <tr class="fd-table__row">
         <th class="fd-table__cell"></th>
         <th style="text-align:left" class="fd-table__cell">Header2</th>
         <th class="fd-table__cell"></th>
         <th class="fd-table__cell">Header4</th>
         <th style="text-align:left" class="fd-table__cell"></th>
      </tr>
   </thead>
   <tbody class="fd-table__body">
      <tr class="fd-table__row fd-table__row--hoverable">
         <td class="fd-table__cell">Text</td>
         <td style="text-align:left" class="fd-table__cell">Text2</td>
         <td class="fd-table__cell">Text3</td>
         <td class="fd-table__cell">Text4</td>
         <td style="text-align:left" class="fd-table__cell">Text5</td>
      </tr>
   </tbody>
</table>

**Outcome**
<img width="663" alt="Screenshot 2023-07-20 at 8 56 33 AM" src="https://github.com/SAP/fundamental-styles/assets/132930816/b632449f-00b8-4f03-85c6-2112420c6e45">

**Desktop**

- OS: macOS
- Browser: Chrome
- Version: 114.0.5735.198
