### ISSUE TITLE
feat(styles): navigation button

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-styles#4258]
**Is your feature request related to a problem? Please describe.**

Implement navigation button which automatically mirrors navigation icon horizontally in RTL.

<img width="159" alt="image" src="https://user-images.githubusercontent.com/20265336/219361864-64c6176f-99ce-43cb-9e72-33d8341ef237.png">

> Is this issue related to a specific component?

Button.

**Comment by g-cheishvili** [comment]
I am not sure that it is ok to mirror icons like that, those are essentially images, but who knows, would be nice to hear what team thinks about this

**Comment by droshev** [comment]
I don't think this should be done in styles
