### ISSUE TITLE
bug(docs): iframeHeight not being respected

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-styles#4259]
**Describe the bug**

`iframeHeight` setting not being respected.

<img width="510" alt="SCR-20230216-iuf" src="https://user-images.githubusercontent.com/20265336/219366241-ddd1e471-1e2c-4194-82c6-fe7fce84bfef.png">

**Comment by IB002** [comment]
Due to new update in storybook iframeHeigh is no longer supported.
