### ISSUE TITLE
bug(list): avatar with icon incorrectly rendered inside byline list

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-styles#4301]
**Describe the bug**
Currently, it avatar with icon being used inside byline list, it's styling are being rewritten by the list styles:
Avatar configuration:
icon - account;
color accent - 6;
circle: true;
size: s
How it currently looks:
![image](https://user-images.githubusercontent.com/6586561/222700107-914f435e-c7cd-47d3-90a8-dc493c4f7ca4.png)

How it should be looking:
![image](https://user-images.githubusercontent.com/6586561/222700452-81fe4cb9-ac21-4bfe-bf5b-dc91b41bfc63.png)

> Is this issue related to a specific component?
Byline list.
> What version of the Fundamental Library Styles are you using?
latest.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by droshev** [comment]
closing as it is not needed atm. Let;s reopen if needed again
