### ISSUE TITLE
IE11 visual smoke test

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#432]
The goal is to conduct a visual smoke test in IE11

**Comment by salarenko** [comment]
Issues reported as an outcome of IE11 and Edge visual smoke tests:

- #520
- #523
- #524
- #525
- #526
- #527
- #528
- #529
- #530
- #531
- #532
- #533
- #534
- #535

Full report:
[Smoke tests - IE 11, Edge.pdf](https://github.com/SAP/fundamental-styles/files/3972952/Smoke.tests.-.IE.11.Edge.pdf)
