### ISSUE TITLE
Cozy & compact density modes

### ISSUE THREAD

**Issue by zbug** [SAP/fundamental-styles#433]
Background: 
Working on an Angular app using latest fundamental styles release and knowing about https://sap.github.io/fundamental-styles/foundation/spacing.html

Request: 
As a developer I would like to use an actual content density mode. Please see https://ux.wdf.sap.corp/fiori-design-web/cozy-compact/ as reference.

I ran into the situation styling a table control, which ended up in: 
![image](https://user-images.githubusercontent.com/1159758/69051551-fbde0580-0a04-11ea-807f-8f94ede43369.png)

However, I wanted to achieve the compact density mode as shown below: 
![image](https://user-images.githubusercontent.com/1159758/69051382-6fcbde00-0a04-11ea-97a7-8c2887b5d062.png)

But the only known way to achieve this look and feel, is by manually adding a respective styles class to all cells:
![image](https://user-images.githubusercontent.com/1159758/69051496-ce915780-0a04-11ea-800c-1aa9a50fa90b.png)

Ideally, this could be set on any level I want and would affect any nested controls: 
![image](https://user-images.githubusercontent.com/1159758/69051690-58d9bb80-0a05-11ea-968e-df944f33d880.png)

**Comment by droshev** [comment]
The table has been re-implemented. Feel free to open a new issue if you encounter any problems.
