### ISSUE TITLE
Multi-click tabs are broken

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/fundamental-styles#4336]
**Describe the bug**:
Define more than one tab as multi-click item.
Based on this [example](https://sap.github.io/fundamental-styles/?path=/docs/components-icon-tab-bar--text-only#navigation-icon-tab-bar--shell-navigation-).

**Result**:
![Bildschirm­foto 2023-03-13 um 20 16 50](https://user-images.githubusercontent.com/14272184/224811965-a2454ce0-e160-4867-83f2-aae54cd0f8d7.png)

**Comment by droshev** [comment]
@JohannesDoberer we have examples with more than one tabs with arrows in this [example](https://sap.github.io/fundamental-styles/?path=/docs/components-icon-tab-bar--text-only#navigation-icon-tab-bar--shell-navigation-)

**Comment by JohannesDoberer** [comment]
Hey @droshev,
that is true and _single click_ tabs works as expected 👍 .
The issue is with _multi click_ tabs.

**Comment by InnaAtanasova** [comment]
Hi @JohannesDoberer , I just tested with multiple tabs and all works well. Is it possible to upload your code example? 
<img width="1213" alt="Screenshot 2023-03-20 at 11 43 34 AM" src="https://user-images.githubusercontent.com/39598672/226395145-32a22a08-9476-46e3-b2d3-8536dcb42c5e.png">

**Comment by InnaAtanasova** [comment]
Hi @JohannesDoberer , I provided a fix for this. Here's the preview: https://deploy-preview-4352--fundamental-styles.netlify.app/?path=/docs/components-icon-tab-bar--text-only&globals=styles-theme:sap_fiori_3

Thanks for reporting the issue!

**Comment by InnaAtanasova** [comment]
The fix can now be used with the latest RC
