### ISSUE TITLE
[fd-panel] Support columns more than 6 on grid

### ISSUE THREAD

**Issue by hisabimbola** [SAP/fundamental-styles#436]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
Currently in fd-panel-grid, one can only specify a maximum columnSpan of 6. This is not always the case when working with grid. It should be possible to specify any amount of grid and the library positions the inner components as such
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
NGX: 0.6.0
Angular: 6.1.7

**Comment by droshev** [comment]
it has been refactored
