### ISSUE TITLE
Bug(platform:action-bar): Edit mode border line is not as per the invision for all the browsers

### ISSUE THREAD

**Issue by manu-kr** [SAP/fundamental-styles#440]
**Describe the bug**

In Action bar while clicked on rename, edit mode border line is not as per the invision for all the browsers.

Input text box border is as not as per the fiori(3) spec.
 
Please refer the below link for fiori spec.
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2048463312

> Is this issue related to a specific component?

Action bar

> What version of the Fundamental Styles are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular

**To Reproduce**
1. Go to 'https://devfarm.aws.ariba.com/appframework-master/component-examples/action-bar'
2. Scroll down to 'Action Bar with a Edit title option.'
3. Click o rename;

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by droshev** [comment]
we will deprecate this component soon.
