### ISSUE TITLE
Icon color is not correct in MessageBox Header

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/fundamental-styles#4464]
**Describe the bug**
"--sapNeutralElementColor" should be "#788fa6" in horizon normal mode(variable definition link: https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_horizon/css_variables.css). But now it indicates to "--sapPageHeader_TextColor", it's "#1d2d3e".
Please see current behavior from following screenshots:
<img width="1262" alt="Screenshot 2023-04-21 at 09 48 32" src="https://user-images.githubusercontent.com/78520316/233530348-b5293a3d-d296-4f25-8a22-f30d95216175.png">

![Screenshot 2023-04-21 at 10 54 54](https://user-images.githubusercontent.com/78520316/233530355-216dcce6-0796-4b8c-bbdd-de0bbb9d67db.png)

**Expected behavior**
Message box header icon color should be "788fa6" in horizon normal mode, as the screenshot shows.
![Screenshot 2023-04-21 at 10 30 10](https://user-images.githubusercontent.com/78520316/233530567-8545d60f-4b7d-40c4-8bf2-9e35c32627d9.png)

Please help check it, thanks!
Josephine Su

**Comment by droshev** [comment]
@sfsf-xweb-sh i checked on our [website](https://sap.github.io/fundamental-styles/?path=/docs/components-message-box--structure) and the color is correct.
![Screenshot 2023-04-25 at 3 19 57 PM](https://user-images.githubusercontent.com/4380815/234380728-bf93e23c-af56-49f8-94ac-1b10134bfa25.png)

**Comment by droshev** [comment]
I think on [fundamental styles](https://fundamental-styles.netlify.app/?path=/docs/sap-fiori-components-message-box--docs) the colors are right
