### ISSUE TITLE
Icon Tab Bar: Text color on hover

### ISSUE THREAD

**Issue by JenniferStamm** [SAP/fundamental-styles#4499]
**Describe the bug**
I believe that the text color of unselected tabs should change on hover (in Quartz Light theme). It's implemented in the [UI5 examples](https://ui5.sap.com/#/entity/sap.m.IconTabBar/sample/sap.m.sample.IconTabBarNoIcons).

> Is this issue related to a specific component?

Icon Tab Bar

> What version of the Fundamental Library Styles are you using?

v0.28.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

No, it's not pressing. I don't think this is a recent bug but rather something that's never been implemented.

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular

**To Reproduce**
1. Go to [the docs](https://fundamental-styles.netlify.app/?path=/docs/sap-fiori-components-icon-tab-bar--docs&globals=styles-theme:sap_fiori_3)
2. hover on an unselected tab
3. Compare to [UI5 samples](https://ui5.sap.com/#/entity/sap.m.IconTabBar/sample/sap.m.sample.IconTabBarNoIcons)

**Expected behavior**
A color change on hover.

**Comment by InnaAtanasova** [comment]
Hi @JenniferStamm thanks for opening this issue. In the design specs for Icon Tab Bar in Quartz there isn't specified hover state. Only Horizon has it. I am not aware of why UI5 examples have one, but our source of truth is the design specs and until they are not updated by the designers we can't consider this as a bug. Meanwhile, I notified the control owner about this issue. Thank you!

**Comment by JenniferStamm** [comment]
@InnaAtanasova did you get any response from the control owner yet?
