### ISSUE TITLE
Design for Component Cards needed

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#45]
@LeoT7508 @jeannewalters Could you provide a design for Cards per Fiori 3 specification?

**Comment by LeoT7508** [comment]
@droshev

What Timeline are u referring to? Do you have an example? We need some reference to design from.

**Comment by droshev** [comment]
@LeoT7508 
`List Card`, `Object Card`, `Table Card`, `Analytical Card`, `DateTime Card`
