### ISSUE TITLE
Icons not centered vertically

### ISSUE THREAD

**Issue by nbblum** [SAP/fundamental-styles#4532]
The .sap-icon--arrow-right and arrow-left and some other icons are not vertically centered which results to problems when trying to align them with other ui elements
![image](https://github.com/SAP/fundamental-styles/assets/85098790/e59048a2-d9fb-4b52-8ff0-f11be8acfcc9)

here is a basic example:
https://plnkr.co/edit/kAUolEPWMg1lRU4S?open=lib%2Fscript.js&preview
![image](https://github.com/SAP/fundamental-styles/assets/85098790/bdcdc57a-869b-401a-8d28-14174c0aadff)

**Comment by nbblum** [comment]
Created a second one in the theming base content repo. I'm not sure which is the correc repo. 
https://github.com/SAP/theming-base-content/issues/16

**Comment by nbblum** [comment]
@droshev thanks for your reply I think we can close this issue then

**Comment by droshev** [comment]
@nbblum can you contact me in slack?

**Comment by nbblum** [comment]
With the lastest version (theming-base-content@11.5.0) the arrows are now aligned
