### ISSUE TITLE
[Sourcing] The expand arrow button alignment inside table cell is getting distorted when the text of the table cell is getting large and the truncation happens

### ISSUE THREAD

**Issue by Ankit0025-cmd** [SAP/fundamental-styles#4539]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The alignment of the expand arrow button inside the table cell should not get distorted when the length of the text increases. Right now we have a workaround for this issue.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/platform": "0.40.2-rc.22",
"@fundamental-ngx/core": "0.40.2-rc.22",
"@angular/cdk": "15.1.1",
"@angular/compiler-cli": "15.1.1",
#### If this is a bug, please provide steps for reproducing it.
Increase the length of text inside the table cell such that the truncation happens.

#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-7wu5rx-9jmvng?file=package.json
<img width="1536" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/60579769/99e7a20a-e131-4587-b3f6-d261e882a56f">

**Comment by Ankit0025-cmd** [comment]
Hi @mikerodonnell89 ,
I have upgraded the version to 0.29.0-rc.35, and still the alignment is not same for the icons in side the table cell for all the cells.
<img width="1536" alt="Screenshot 2023-06-01 at 9 15 02 AM" src="https://github.com/SAP/fundamental-styles/assets/60579769/aa190924-4e07-498e-98a9-59a15f52062a">

**Comment by I543348** [comment]
@mikerodonnell89  can you please reopen based on above confirmation ?
Thanks

**Comment by mikerodonnell89** [comment]
The fix needs to come from a new version of fundamental-styles which fundamental-ngx depends on
