### ISSUE TITLE
Fundamental Styles Storybook Not Loading: Failed to Fetch Module Error

### ISSUE THREAD

**Issue by gitgmihd** [SAP/fundamental-styles#4585]
**Describe the bug**

The currently deployed Fundamental Styles Storybook is not functioning correctly.

**To Reproduce**

1. Go to https://sap.github.io/fundamental-styles/
2. Encounter the error message: "Failed to fetch dynamically imported module: https://sap.github.io/fundamental-styles/assets/config-daff9ae6.js" which prevents viewing the Stories.

**Expected behavior**
The Fundamental Styles Storybook should be accessible without any errors.

**Screenshots**

![image](https://github.com/SAP/fundamental-styles/assets/128725347/140848cd-39c8-481b-a88f-73662b14435e)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser chrome
 - Version 114.0.5735.110

**Additional context**
The issue is reproducible on an Android smartphone as well.

**Comment by droshev** [comment]
@gitgmihd we are aware of the issue and while we are figuring it out, you can use this link as a backup https://fundamental-styles.netlify.app/

**Comment by gitgmihd** [comment]
Thanks for the backup link and your support in resolving the issue. Much appreciated!

**Comment by droshev** [comment]
The issue has been addressed
