### ISSUE TITLE
Breadcrumb doesn't match Fiori 3 specs

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#459]
Spacing between each title is different.

![Screen Shot 2019-11-22 at 4 14 06 PM](https://user-images.githubusercontent.com/54589269/69460901-387e6980-0d43-11ea-9f45-75aa20d3bd08.png)

**Comment by droshev** [comment]
The issue comes from the spaces between the html elements.

**Comment by estelaxu3** [comment]
The update looks good, we can close it now.
