### ISSUE TITLE
sapField_Background color mismatch

### ISSUE THREAD

**Issue by allen138** [SAP/fundamental-styles#4596]
**Describe the bug**
Hi team,

We found that there is a discrepancy between the color defined for sapField_Background. In fundamental-styles it is defined as #fff whereas in sap-theming it is defined as #eff1f2.
[fundamental-styles/v0.29.1/sap_horizon/_css_variables.scss#L452](https://github.com/SAP/fundamental-styles/blob/v0.29.1/packages/styles/src/theming/sap_horizon/_css_variables.scss#L452)
[theming-base-content/11.4.2/sap_horizon/css_variables.css#L455](https://github.com/SAP/theming-base-content/blob/11.4.2/content/Base/baseLib/sap_horizon/css_variables.css#L455)

Thanks,
Allen

**What version of the Fundamental Library Styles are you using?**
0.29.1

**Expected behavior**
CSS variables should be consistent between fundamental-styles and theming-base-content.

**Comment by allen138** [comment]
Thanks @droshev for the information and a quick reply. We are looking into alternatives as it is not as straight forward as proposed in the 1-3 options above. At any given time SFSF could have the css vars coming from “classic” sapui5 framework, ui5-webcomponents or fundamental styles. We need all three frameworks/libraries to be in sync to provide a consistent and cohesive experience for our users. I would think that the single source of truth would come from the theming-base-content. However, in this situation fundamental-styles is “ahead” of the base theme lib even though fundamental styles has a strict peer dependency.

**Comment by droshev** [comment]
@allen138 Thanks for the update. Let us discuss internally and we will come to you. I believe that you not only would need to align with colors, but the design should not break the components either.
