### ISSUE TITLE
[checkbox] select/checking a checkbox does not work in firefox browser

### ISSUE THREAD

**Issue by allen138** [SAP/fundamental-styles#4605]
**Describe the bug**
Using firefox browser and v0.29.0 (or greater), you cannot check a checkbox. 

> Is this issue related to a specific component?
Yes, checkbox

> What version of the Fundamental Library Styles are you using?
0.29.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
SF

**To Reproduce**
1. Using Firefox browser, go to https://fundamental-styles.netlify.app/?path=/docs/sap-fiori-components-forms-checkbox--docs
2. Scroll down to 'default' section and notice the 'Selected/Checked State' is not checked.
3. Try and check the checkbox. Notice you cannot check the box.
4. (no issues in chrome)

**Expected behavior**
You should be able to set initial state of a checkbox to checked, and you should be able to check a checkbox.

**Desktop (please complete the following information):**
 - OS: windows and ios have same issue
 - Browser firefox
 - Version: latest (114.0.1 (64-bit))

**Comment by InnaAtanasova** [comment]
Hi @allen138 , thanks a lot for bringing this to our attention. I am currently working on the fix and it will be very soon available. Thank you again for your contribution! It's very much appreciated!

**Comment by InnaAtanasova** [comment]
Hi @allen138 the fix has been merged in main and available with the latest RC version.

**Comment by allen138** [comment]
Thank you for the quick turn around!
