### ISSUE TITLE
Required checkbox vertical alignment issue

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-styles#4606]
When no text is provided for the checkbox label, the required asterisk is positioned lower
<img width="175" alt="Screenshot 2023-06-15 at 10 23 20 AM" src="https://github.com/SAP/fundamental-styles/assets/2471874/c4bacefb-294b-4590-8a3a-846b7abfea26">

**Comment by InnaAtanasova** [comment]
Is it really a bug? Isn't the asterisk an attribute to the label? I've never seen a checkbox with an asterisk and no label.

**Comment by droshev** [comment]
That is more like a Form validation, rather than checkbox, no?

**Comment by InnaAtanasova** [comment]
I close this issue. Please re-open if more information is provided
