### ISSUE TITLE
Github Project Website https://sap.github.io/fundamental-styles/  throws an error

### ISSUE THREAD

**Issue by elankath** [SAP/fundamental-styles#4609]
**Describe the bug**
The link https://sap.github.io/fundamental-styles/ throws an error as shown below
```
TypeError: Failed to fetch dynamically imported module: https://sap.github.io/fundamental-styles/assets/config-783244e2.js
```

> Is this issue related to a specific component?
No

> What version of the Fundamental Library Styles are you using?
Link opened from github project page

**To Reproduce**
1. Go to 'https://github.com/SAP/fundamental-styles'
2. Click on the link in the About section: [sap.github.io/fundamental-styles](https://sap.github.io/fundamental-styles)

**Expected behavior**
No errors. Doc renders correctly 

**Desktop (please complete the following information):**
ALL

**Smartphone (please complete the following information):**
ALL

**Additional context**
N/A

**Comment by droshev** [comment]
duplicated with #4585
