### ISSUE TITLE
Design for Component Dynamic Page needed

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#47]
@LeoT7508 @jeannewalters Could you provide a design for Dynamic Page per Fiori 3 specification?

**Comment by LeoT7508** [comment]
@droshev

What Component Dynamic Page are u referring to? Do you have an example? We need some reference to design from.

**Comment by droshev** [comment]
@LeoT7508 

`Page Type: Object Page`

**Comment by LeoT7508** [comment]
@droshev 

I suggest we add this to the backlog for now until we talk as a team per @saad-mo

**Comment by droshev** [comment]
@LeoT7508 do you think you can start working on the design of those tickets created in this repo?

**Comment by LeoT7508** [comment]
@droshev 

@saad-mo Suggested we hold off on this.
