### ISSUE TITLE
Alert doesn't work in IE

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#476]
The close icon is not aligned.

**Comment by estelaxu3** [comment]
![image](https://user-images.githubusercontent.com/54589269/70248806-7b7c0c00-1749-11ea-927a-6008245d9afa.png)

The close icon should move down by 1 or 2 pixel in order to be in the middle horizontally.

**Comment by JKMarkowski** [comment]
fixed by: https://github.com/SAP/fundamental-styles/pull/470
