### ISSUE TITLE
Missing paddings for buttons that contain icon+counter in Shellbar

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#478]
In the Shellbar for buttons there is no paddings. It looks good when button consists only of an icon, but when you have icon + counter, on hover you can see the icon sticks to the side of button

<img width="1205" alt="paddings" src="https://user-images.githubusercontent.com/39598672/69878239-5cd1cd00-1292-11ea-87e6-cb724e5e7fb1.png">

> Is this issue related to a specific component?
Button in Shellbar

**Comment by mikerodonnell89** [comment]
part of #204

**Comment by droshev** [comment]
has been fixed
