### ISSUE TITLE
Question - Board container

### ISSUE THREAD

**Issue by sabatale** [SAP/fundamental-styles#4788]
### Component name
Board

### Detailed description
Is there any component we missed or some example that would ressemble a board?

This would basically be the same as what is available in Roadmap Explorer:
[https://roadmaps.sap.com/board?range=CURRENT-LAST&PRODUCT=73554900100800000266#Q3%202023](https://roadmaps.sap.com/board?range=CURRENT-LAST&PRODUCT=73554900100800000266#Q3%202023)

### Use case
Boards are pretty much everywhere, including within SAP products.

### Visual style
![image](https://github.com/SAP/fundamental-styles/assets/50220345/890a9b65-994a-47f5-a20b-366ea982c639)

**Comment by droshev** [comment]
@sabatale not at the moment
