### ISSUE TITLE
Custom column header

### ISSUE THREAD

**Issue by uzmo** [SAP/fundamental-styles#4827]
**Describe the solution you'd like**
Support cross columns header in Table Component to show headers in multiple levels(2 or more).
https://sap.github.io/fundamental-styles/?path=/docs/sap-fiori-components-table--docs

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="829" alt="2023-09-12_15-00-05" src="https://github.com/SAP/fundamental-styles/assets/6258527/3f48e97f-4211-44a9-86da-40bb4fd7590d">

**Comment by droshev** [comment]
@uzmo are you aware of an existing sap design guidelines for that?
