### ISSUE TITLE
Form Inputs/input states broken in IE

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#483]
Text has spacing issue in form inputs and input state.

**Comment by rengare** [comment]
@estelaxu3 can you provide a screenshot ? Probably it is fixed by #442

**Comment by estelaxu3** [comment]
![image](https://user-images.githubusercontent.com/54589269/70334307-34f2e400-1813-11ea-9d58-bc1e7c71254f.png)

**Comment by fkolar** [comment]
I have already open up another issue to this. The error messages we have under the field shift down the field bellow. 

and having large form with different types of validation, the fields are going to be jumping up and down as we keep showing or hinding errors

**Comment by InnaAtanasova** [comment]
> I have already open up another issue to this. The error messages we have under the field shift down the field bellow.
> 
> and having large form with different types of validation, the fields are going to be jumping up and down as we keep showing or hinding errors. This is not specific to IE though

Hi Frank, we are placing the messages inside a popover, so it won't be an inline element and won't shift the content below the input. 
https://deploy-preview-472--fundamental-styles.netlify.com/components/form.html
