### ISSUE TITLE
Date Range Picker

### ISSUE THREAD

**Issue by Designerishere** [SAP/fundamental-styles#4839]
**Date Range Picker**
This component is needed in the Fundamental NGX library. It provides the user with the possibility to select date ranges. It's supposed to be a new component. The component also exists in the UI5 web components. The design specifications are in place. It would be great if NGX could offer the same component.

**Comment by droshev** [comment]
we have it - https://fundamental-ngx.netlify.app/#/core/date-picker (Example: Range Date Picker)
