### ISSUE TITLE
Design Review Findings

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#4912]
Components with issues:
- [x] Calendar - Mike https://github.com/SAP/fundamental-styles/pull/4930
- [ ] Card - Mike https://github.com/SAP/fundamental-styles/pull/4933
- [ ] Carousel - Mike https://github.com/SAP/fundamental-styles/pull/4935
- [ ] Dialog - Mike https://github.com/SAP/fundamental-styles/pull/4937
- [x] Generic Tag - Giorgi https://github.com/SAP/fundamental-styles/pull/4968
- [ ] Link - N1XUS 
- [ ] Message Popover - N1XUS
- [ ] Message Strip - Mike https://github.com/SAP/fundamental-styles/pull/4948
- [ ] Object List - Giorgi
- [x] Object Marker - text color checked and confirmed  ![image](https://github.com/SAP/fundamental-styles/assets/6586561/4188a93a-ef5a-4c3e-a1b1-b06451d76cc3)

- [x] Object Status- Giorgi https://github.com/SAP/fundamental-styles/pull/4968
- [ ] Panel - Mike https://github.com/SAP/fundamental-styles/pull/4949
- [ ] Popover - Mike https://github.com/SAP/fundamental-styles/pull/4950
- [ ] Progress Indicator- Giorgi
- [x] Select - N1XUS https://github.com/SAP/fundamental-styles/pull/4932
- [ ] Splitter - Mike

**Comment by g-cheishvili** [comment]
Progress indicator popover note:
> This popover comes from fiori specifications, the Horizon does not have any mentioning of the truncation. On UI5, they just truncate, without any popover. In general they should not share the same HTML structure, but we're forced to make them the same

Object list note:
> The spacing between the attributes is 0.5 rem already. When they say "inner padding" they mean the spacing between the attribute and the status.
Visually they might not appear distanced from each other with 0.5rem, because there is also a `line-height` specification, which states that it should have 1.5 line height and naturally the height of the text is increased
