### ISSUE TITLE
Form Radio consistency issue

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-styles#495]
**Describe the bug**

While trying find some common things among Form Inputs fields I see there are some controls that are implemented completly differently than rest of the input fields which make it dificult to build some generic solution without having IF/then/ELSE> 

E.g. When working with input field it is straight forward

```html
<div class="fd-form-item">
    <label class="fd-form-label" for="OatmD552">
        Normal Input:
    </label>
    <input type="text" class="fd-input" id="OatmD552" placeholder="Field placeholder text">
    <span class="fd-form-message">
        Pellentesque metus lacus commodo eget justo ut rutrum varius nunc
    </span>
</div>
```
- I wrap it with form item, it has label that identify this fields. 

But for the RadioGroup its completly different.:

```html
<fieldset class="fd-fieldset">
    <legend class="fd-fieldset__legend">Radio buttons</legend>
    <div class="fd-form-item">
        <label class="fd-form-label" for="pDidh761">
            <input type="radio" class="fd-radio" id="pDidh761" name="radio" checked>
            Field label
        </label>
    </div>
    <div class="fd-form-item">
        <label class="fd-form-label" for="pDidh7612">
            <input type="radio" class="fd-radio" id="pDidh7612" name="radio">
            Field label
        </label>
    </div>
```

- We dont use the same concept like in case of input or other field. It should be more:

form-item
   => Label
   => Radio-Group

- Conceptualy, radio group should represent 1 single form field such as `Order.status` (new, ordering, oredered) and radio group has several items. 
- We have built it from inside out. Each radio item is actual form-item

Is there any reson for implementing it like this? 
Select has also options, does it mean we should make it similary like this radio button?  When I compare other implementation out there like:
   - https://material.angular.io/components/radio/examples
   -  https://clarity.design/documentation/radio
   - even primeng

All of the have this consistent. Would it be possible to also make it more aligned with other form fields in this case? 

Since we used this fieldset and havent dont normalization, Safari has default setting to set the border for the radio group

<img width="1116" alt="Screen Shot 2019-12-05 at 10 50 25 PM" src="https://user-images.githubusercontent.com/17149942/70276932-aa2dcd00-17b1-11ea-9ac0-6b235c4927ea.png">

**Comment by fkolar** [comment]
What if we structure it like this, this way it would semantically simlar to input:



```html
<div fd-form-set>
    <div fd-form-item>
        <label fd-form-label for="input-1">Default Input:</label>      
        <fd-form-group>
          <div fd-form-item [isCheck]="true">
              <label fd-form-label for="radio-1">
                  <input fd-form-control type="radio" id="radio-1" name="radio-name-1" value="" checked>
                  Option One
              </label>
          </div>
          <div fd-form-item [isCheck]="true">
              <label fd-form-label for="radio-2">
                  <input fd-form-control type="radio" id="radio-2" name="radio-name-1" value="">
                  Option Two
              </label>
          </div>
          <div fd-form-item [isCheck]="true">
              <label fd-form-label for="radio-3">
                  <input fd-form-control type="radio" id="radio-3" name="radio-name-1" value="">
                  Option Three
              </label>
          </div>
      </fd-form-group>
    </div>
</div>
```

**Comment by droshev** [comment]
the radio has been refactored already
