### ISSUE TITLE
Inconsistent Styles for Checkbox and Radio (Safari/Chrome)

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-styles#515]
##BUG

**Describe the bug**

On Fundamentals-styles v0.3.0 that is currently deployed to the github pates, I see different visual behavior, Please see screenshots

<img width="1155" alt="Screen Shot 2019-12-15 at 8 23 07 PM" src="https://user-images.githubusercontent.com/17149942/70867728-be738600-1f78-11ea-9d95-b8402e2ec9ab.png">
<img width="1071" alt="Screen Shot 2019-12-15 at 8 22 51 PM" src="https://user-images.githubusercontent.com/17149942/70867730-c0d5e000-1f78-11ea-84c0-c7481374e961.png">

**Comment by JKMarkowski** [comment]
Hello @fkolar,

We are in the middle of big refactor of forms and forms related component. It will be fixed on `0.4.0` release soon.

**Comment by fkolar** [comment]
@JKMarkowski, cool. Just want to keep this for the records as in order version there is a issue and want to make sure that in 0.4.0 is fixed.

**Comment by bcullman** [comment]
It is unclear which browser each screen shot is from. Please capture screen shots that include the browser shell/chrome as well.
