### ISSUE TITLE
IE11 Active css selector blocked yb child elements

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-styles#520]
We found out that in IE11 the children are blocking `:active` 
Example can be found on `product-switch`. Directly Tapping down on product switch will cause the `::active`, but when user tries to do it by tapping on children elements, the active is not applied.
That's how it works:
![productswitch](https://user-images.githubusercontent.com/26483208/70922068-c2111680-2025-11ea-955c-1cb163e65a4d.gif)

When css modifier `pointer-event: none` is applied, the `::active` is working properly, but it can provide some unexpected behaviours from child elements.
![productswitchpointerevents](https://user-images.githubusercontent.com/26483208/70922171-f08ef180-2025-11ea-8141-d3e20cbe6f07.gif)

> Is this issue related to a specific component?
It is related to 
* `Product Switch`
* Components using Menu
* Component using List

> This issue only occurs on IE11

**Comment by droshev** [comment]
Let's close this
