### ISSUE TITLE
Cards - Quality and Features Enhancements

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#5282]
FIORITECHP1-30116

**Comment by InnaAtanasova** [comment]
@droshev for this ticket you need to decide what we should bring to Fundamentals. 
The latest design for Card header is implemented already.
Here's what we can add from the new features in Cards Anatomy
- [ ] Media on Cards
- [ ] Media as Banner
- [ ] Interaction states 
- [ ] Focus
- [ ] Transparent Card
