### ISSUE TITLE
Inline select options list shrinks, no options visible

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-styles#532]
**Describe the bug**
Error is related to Select / Inline component.

Inline select option list shrinks and no options are visible.

Error occurs on IE11.
Fundamental styles version: v0.4.0-rc.21

**To Reproduce**
Go to _"../components/select.html"_, Inline section

**Screenshots**
Chrome
![image](https://user-images.githubusercontent.com/17496353/70988141-92afe780-20c1-11ea-9938-afa1d41b9310.png)

IE11
![image](https://user-images.githubusercontent.com/17496353/70987862-00a7df00-20c1-11ea-9466-3b6eb8e11d49.png)

**Comment by JKMarkowski** [comment]
It has been addressed in `0.8.1`
