### ISSUE TITLE
[Shellbar] Color Code for Navigation/Mega Menu Button Incorrect (Quartz Light Theme)

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-styles#5404]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
According to the Visual Core for the Shellbar in the Quartz Light theme, the text color of the mega menu button shall be
color: --sapShell_TextColor (Normal State) which results in #fff. 
Currently it has a different, light blue color.

#### Can you handle that on the application side
Probably, but this should be corrected in the standard component(s).

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
v0.49.2

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
![image](https://github.com/SAP/fundamental-ngx/assets/52921101/fbdebd44-e132-4052-94f4-f1729702e9bd)

**Comment by InnaAtanasova** [comment]
Hi @D034394 thank you for reporting the issue. It's coming from Fundamental-styles so I will transfer it there and once it's fixed it will automatically consume the changes with the latest version of fd-styles.
