### ISSUE TITLE
product switch ellipses and dots

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-styles#541]
**Describe the bug**
 product switch item without subtitles has the white block on hover.
Product switch has dots.
Product switch button is not the proper color in shellbar
Product switch ellipses not working properly
![Screen Shot 2020-01-29 at 5 58 48 PM](https://user-images.githubusercontent.com/50607147/73460992-684f7c00-4347-11ea-8691-5f68f00afcc9.png)

> Is this issue related to a specific component?
product switch
> What version of the Fundamental Library Styles are you using?
latest

**Comment by salarenko** [comment]
Cannot reproduce. Please provide some additional informations/screenshots.
