### ISSUE TITLE
Max width for button

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-styles#562]
**Describe the bug**
There should be a max-width on the button or else it may go out of the container with overflow.
> Is this issue related to a specific component?
Button
> What version of the Fundamental Library Styles are you using?
Latest
> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular

**To Reproduce**
1. Go to '...' Button component
2. Make text super long

**Expected behavior**
There should be ellipses but there isn't

**Screenshots**
![Screen Shot 2020-01-07 at 10 37 42 AM](https://user-images.githubusercontent.com/50607147/71907483-22353d00-313a-11ea-9840-80fc77750ba6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ios
 - Browser [e.g. chrome, safari] : chrome

**Comment by sKudum** [comment]
Could you please elaborate the issue? Are we expecting truncation and Ellipsis ?  fixed width?
