### ISSUE TITLE
Resize the table column widths

### ISSUE THREAD

**Issue by Jagoooo** [SAP/fundamental-styles#564]
We need to be able to resize the table column widths within our product, for displaying required information. This is rather urgent now as we are struggling to fit all the data needed in our tables.

**Comment by salarenko** [comment]
Hey @Jagoooo could you provide more information about your problem/feature-requests (ex. screenshot). What library are you using (Angular/Vue/React)?

**Comment by Jagoooo** [comment]
In Content Driven services we use both Angular and React.

We have a lot of tables across Merchandising, Customer Recovery,  Segmentation and the reporting applications. 

We currently can not fit all the required information into the table. 'Description' can have quite a few characters in it. We have limited our naming to 50 characters. But we want the ability to drag the ability column widths. So users can prioritise what the see and we can add more content into our tables.

**Comment by Jagoooo** [comment]
Hi, is this going to be done? It is currently limiting the amount of content that we can put into tables. I am happy to have a call and discuss further if need be? Thanks

Jago

**Comment by droshev** [comment]
this will be handled in fundamental-ngx [#3746](https://github.com/SAP/fundamental-ngx/issues/3746)
