### ISSUE TITLE
date picker/calendar minor styling issue

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#5648]
bug

there is a minor miss-alignment in the calendar in the month selector as reported [here](https://github.com/SAP/fundamental-ngx/pull/12341#pullrequestreview-2313161043)

**Comment by InnaAtanasova** [comment]
this is not a fund-styles issue. See my comment here: https://github.com/SAP/fundamental-ngx/pull/12341#issuecomment-2397330425
