### ISSUE TITLE
Alert documentation links

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#582]
the `alert` doc page has 2 links listed as guidelines: `Application Guidelines` and `Alert Overlay Demo Page` which either point to an example with no `alert` or the `alert` is broken
<img width="846" alt="Screen Shot 2020-01-08 at 6 09 33 AM" src="https://user-images.githubusercontent.com/4380815/71952095-befce680-31dd-11ea-8145-210cc43f9f2b.png">

**Comment by salarenko** [comment]
@droshev Could you check once again? I've checked it and I think these links navigate to correct examples.
