### ISSUE TITLE
Multi-input list not wrapping  for very long text 

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/fundamental-styles#596]
**Describe the bug**

Multi-Input component list is not gracefully handling very long text.

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/9139037/72709700-794ffe80-3b8b-11ea-88c6-bd8b889d0321.png">

> Is this issue related to a specific component?

https://sap.github.io/fundamental-styles/patterns/multi-input.html

> What version of the Fundamental Library Styles are you using?

0.4.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JKMarkowski** [comment]
Hi @sunnyyadav100, currently we are working on adapting dropdowns (multi-input, combobox, select) To fiori3 specifications. It's supposed to be pushed in v0.6.0 in next 2 weeks.
