### ISSUE TITLE
Firefox 72.0.1 bugs

### ISSUE THREAD

**Issue by gimler** [SAP/fundamental-styles#597]
ubuntu 18.04.03 and windows 10
firefox 72.0.1
* https://sap.github.io/fundamental-styles/components/form.html the textarea did not work for me i can't make a new line with enter key ;(
* https://sap.github.io/fundamental-styles/components/table.html#table-with-checkbox checkbox not visible

it seems that fundamental has some problems with firefox 72.0.1 (edited)

**Comment by droshev** [comment]
@gimler Thanks for logging the issue. Do you think you can upload some screenshot? This will help us a lot.
