### ISSUE TITLE
Toggle has wrong allignments when specific fields are chosen

### ISSUE THREAD

**Issue by rengare** [SAP/fundamental-styles#608]
**Describe the bug**
When toggle has size 'xs' and the semantic property is selected then toggle is displayed wrong, see attachment for more details

> Is this issue related to a specific component?
Toggle
> What version of the Fundamental Library Styles are you using?
v0.5.0

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**To Reproduce**

1. Go to playground
2. Choose 'xs' size
3. Choose semantic option

**Expected behavior**
Toggle should be aligned properly

**Screenshots**
![image](https://user-images.githubusercontent.com/10849982/73120489-eb02c080-3f6e-11ea-82c3-5920d7cd55a3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 72

**Comment by JKMarkowski** [comment]
So for toggle, we don't have sizes anymore. See https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#removed
