### ISSUE TITLE
Range Slider - Component Request

### ISSUE THREAD

**Issue by HolgerMaassen** [SAP/fundamental-styles#623]
Hi ...
... for CDS we need a new component - a **Range Slider** 

I checked but I could not find any similar or closed issues / components.

On Fiori 3.0 you can find - I would say all needed information to transform the Fiori3.0's range slider in to a Fundamental's range slider.
Resources for the Range Slider can be found here:

Overview: 
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2033852394

Styleguide: 
https://experience.sap.com/fiori-design-web/slider/

Implementation: https://sapui5.hana.ondemand.com/explored.html#/entity/sap.m.Slider/samples

SAPUI5 API reference: https://sapui5.hana.ondemand.com/sdk/#docs/api/symbols/sap.m.Slider.html

**Component name**
Proposed name: Range Slider

**Detailed description**
What we want is...
A  Range Slider   from 0 to 100  meaning 0% to 100%    with tickmarks and steps of "10%"    in addition we show for the two values input fields which only accept inputs between 0 and 100  and steps of 10   when the user is using the input fields the visual slider adapt accordingly 

The user should be able to change the slider setting in 2 ways:
By using drag and drop to adjust the grip
By clicking or tapping on the bar. The grip then moves to this new position.
The grip can be moved with or without increments based on the predefined steps.
Slider with Text input Fields
The slider will be used with text fields. The input fields are always visible and shows the value of the grip. The position of the Input fields are always above the regarding grip

But as said before - we want and need  the same interaction as the Fiori3.0's range slider has it.

Use case
The user should be able to define a range with in the giving total range

Visual style
As visual example I add a screenshot of our current wireframes:

![DynamicAffinities-200129-hma_1of3_20%-100%](https://user-images.githubusercontent.com/60512754/73549057-26573080-4442-11ea-90db-3418b8237c6a.jpg)

![DynamicAffinities-200129-hma_2of3_0%](https://user-images.githubusercontent.com/60512754/73549069-2bb47b00-4442-11ea-9fb6-a3f8b433b703.jpg)

![DynamicAffinities-200129-hma_3of3_100%](https://user-images.githubusercontent.com/60512754/73549094-3838d380-4442-11ea-817d-476d2199a41a.jpg)

**Comment by droshev** [comment]
implemented
