### ISSUE TITLE
Fade function and SASS files

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#625]
There are 3 places where we have `fade` function which requires a less loader. We should replace it with `fade-out` sass function. The problem is that `fade-out` function accepts a color and doesn't work with var(--someColor). The new release of sap-theming would solve this problem.

**Comment by droshev** [comment]
The current components have fading is `tabs`, `product-switch` ( and `_drag-and-drop.scss`)

**Comment by JKMarkowski** [comment]
Tab
- Fade Method for box shadow: `0 0 0.25rem 0 fade(var(--sapContent_ShadowColor), 15), inset 0 -0.0625rem 0 0 var(--sapObjectHeader_BorderColor);`
![image](https://user-images.githubusercontent.com/26483208/98369106-b745e280-2038-11eb-8d45-96b0eb2366d3.png)
