### ISSUE TITLE
Token needs RTL values

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-styles#626]
**Describe the bug**

Token is missing RTL values.  Using the token in RTL mode looks like this: 

<img width="390" alt="Screen Shot 2020-02-03 at 3 16 33 PM" src="https://user-images.githubusercontent.com/2471874/73695895-48e28700-4698-11ea-9194-fe3a160692e1.png">

**Comment by JKMarkowski** [comment]
it's actually fixed, by https://github.com/SAP/fundamental-styles/pull/627
