### ISSUE TITLE
Form-message fit-content and IE11 issue

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#632]
Form-message uses `fit-content` for its width. Fit-content is not working in IE11. We need to handle the width another way

**Comment by JKMarkowski** [comment]
@InnaAtanasova is it solved by https://github.com/SAP/fundamental-styles/pull/654 ?

**Comment by stefanoScalzo** [comment]
Is this solved already? if not I could fix it? @InnaAtanasova

**Comment by InnaAtanasova** [comment]
It's fixed in #654
