### ISSUE TITLE
Different Sizes of the Loading Spinner

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-styles#636]
Hi there,
the loading spinner seems to be available in one size only.
https://sap.github.io/fundamental-styles/components/loading-spinner.html
Is it possible to change the size somehow, similar to the busy indicators (https://sap.github.io/fundamental-styles/components/busy-indicator.html)? If not, is it planned to make resizing available?
Thanks,
Kai

**Comment by zanonnicola** [comment]
I was playing with the components the other day and faced the same issue.
Ended up doing this:

```css
.fd-spinner .fd-spinner--large {
  transform: scale(1.5);
}
```

A bit of a hack but it works.

**Comment by droshev** [comment]
@D034394 The loading spinner has been deprecated in Fiori 3 so we will start phasing it out too.
