### ISSUE TITLE
Long link text not truncated

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-styles#665]
A Long Link text should be truncated with overflow symbol. For this truncation, current styles of link does not cover necessary styles. Need to implement that. 
Currently External css styles are getting used.

**Is your feature request related to a problem? Please describe.**
A long Link text is not truncated.

> Is this issue related to a specific component?
Link Component.

> What browser are you working in?
Chrome, Firefox, edge, Safari
> What version of Fundamental Library Styles are you using?
0.5.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
--Angular

**Describe the solution you'd like**
-- A Long Link text should be truncated with overflow symbol. For this truncation, current styles of link does not cover necessary styles. Need to implement that. 
Currently External css styles are getting used.

**Describe alternatives you've considered**
-- Currently External css styles are getting used.

**Additional context**

**Comment by DeepakSap14** [comment]
@InnaAtanasova , @droshev please give Access to Fundamental-styles. Currently i am not able to raise PR. I am already part of SAP org.

**Comment by droshev** [comment]
> @InnaAtanasova , @droshev please give Access to Fundamental-styles. Currently i am not able to raise PR. I am already part of SAP org.

done

**Comment by droshev** [comment]
@DeepakSap14 you should be able to open a PR

**Comment by DeepakSap14** [comment]
This is merged as part of PR https://github.com/SAP/fundamental-ngx/pull/1903
