### ISSUE TITLE
Button is not centered

### ISSUE THREAD

**Issue by rengare** [SAP/fundamental-styles#674]
**Describe the bug**
![image](https://user-images.githubusercontent.com/17496353/74544660-cbe0c880-4f47-11ea-930d-6edcd1cfcaf6.png)

> Is this issue related to a specific component?

> What version of the Fundamental Library Styles are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

**Desktop (please complete the following information):**
 - OS: windows
 - Browser IE 11

**Comment by droshev** [comment]
the component will be removed soon
