### ISSUE TITLE
popover arrow different color

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-styles#680]
**Describe the bug**
Popover arrow is darker grey than the rest of the border
> Is this issue related to a specific component?
Popover
> What version of the Fundamental Library Styles are you using?
latest
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
none
> What front-end framework are you implementing in, e.g., Angular, React, etc.?
all
**Screenshots**
![Screen Shot 2020-02-20 at 10 38 37 AM](https://user-images.githubusercontent.com/50607147/74950679-75eba500-53cd-11ea-8e77-e1fd7644c207.png)

**Comment by droshev** [comment]
this is due to missing the same color from the theming params
