### ISSUE TITLE
Test the Documentation Site and Components on iPad

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#685]
The goal of this ticket is to test the Fundamental Styles Website on iPad:
- [ ] validate all the pages are accessible and usable
- [ ] validate the components rendering

**Comment by droshev** [comment]
@estelaxu3 what is the status of this issue? Were you able to test it?

**Comment by estelaxu3** [comment]
The issues are documented in:
#740 
#739 
#732
