### ISSUE TITLE
Bug: is-disabled class

### ISSUE THREAD

**Issue by SaiShan** [SAP/fundamental-styles#69]
The is-disabled class does not render the disabled state for a `<span>`.

See the screenshot.

<img width="928" alt="broken" src="https://user-images.githubusercontent.com/25252963/59301177-05499180-8c5f-11e9-932a-9138b0492144.png">

Related issue: #68.

**Comment by salarenko** [comment]
Issue has been fixed
![image](https://user-images.githubusercontent.com/17496353/73940119-2a27fe80-48eb-11ea-9bd6-043892d4b30e.png)
