### ISSUE TITLE
Migrate and rename Identifier to Avatar

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#720]
The current component Identifier has a different name as Fiori 3 component - Avatar.
The tasks:
- deprecate Identifier
- introduce Avatar (component for displaying images, such as user profile, user initials, placeholder images, icons or business related images like product images)

<img width="73" alt="Screen Shot 2020-03-01 at 9 37 18 AM" src="https://user-images.githubusercontent.com/4380815/75627681-4d6b6400-5ba0-11ea-8bb8-29c0c4da7705.png">
<img width="362" alt="Screen Shot 2020-03-01 at 9 37 14 AM" src="https://user-images.githubusercontent.com/4380815/75627682-4e03fa80-5ba0-11ea-8668-4f2ee35a42a2.png">
<img width="367" alt="Screen Shot 2020-03-01 at 9 37 11 AM" src="https://user-images.githubusercontent.com/4380815/75627683-4f352780-5ba0-11ea-96c7-85468853bc0a.png">

**Comment by trilodge** [comment]
Maybe this would be a good starting point migrating from background-images to real images with alt="" and using proper markup for such kind of things.
