### ISSUE TITLE
New Component - Responsive Table

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#722]
Introduce a new Responsive Table component(set of line items and is fully responsive) and deprecate the old table version.
Initial estimate 20 days
It is optimized for viewing one line item at a time with no scrolling or only vertical scrolling, irrespective of the display width.
![table3](https://user-images.githubusercontent.com/4380815/75627774-498c1180-5ba1-11ea-8312-9b5ee87308d8.png)
![table2](https://user-images.githubusercontent.com/4380815/75627775-4a24a800-5ba1-11ea-9236-688d1ae38adb.png)
![table1](https://user-images.githubusercontent.com/4380815/75627776-4abd3e80-5ba1-11ea-9c72-369b52ae0d09.png)

The issue will be done in 2 sprints.
First part:
- Design; brainstorming; tasks breakdown

**Comment by mikerodonnell89** [comment]
Depends on https://github.com/SAP/fundamental-styles/issues/840

**Comment by mikerodonnell89** [comment]
1 dev, 2 sprints?

**Comment by estelaxu3** [comment]
<img width="751" alt="Screen Shot 2020-05-13 at 11 19 36 AM" src="https://user-images.githubusercontent.com/54589269/82675598-0e830280-9c13-11ea-8f01-97f59f1c6f99.png">
<img width="744" alt="Screen Shot 2020-05-13 at 11 19 43 AM" src="https://user-images.githubusercontent.com/54589269/82675611-10e55c80-9c13-11ea-8d00-df6070ae495a.png">
<img width="752" alt="Screen Shot 2020-05-13 at 11 19 49 AM" src="https://user-images.githubusercontent.com/54589269/82675612-117df300-9c13-11ea-8b3d-200d8f5295bd.png">
<img width="749" alt="Screen Shot 2020-05-13 at 11 19 57 AM" src="https://user-images.githubusercontent.com/54589269/82675616-12168980-9c13-11ea-9e2a-2cd512f8a57a.png">
