### ISSUE TITLE
iPad Visual Testing: Home page render issue

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#732]
1. There is a giant space on the screen when scroll down on the Getting Started page.
![IMG_0026](https://user-images.githubusercontent.com/54589269/75715456-6d338280-5c9b-11ea-8407-866364d36dc8.PNG)

2. The side navigation doesn't scroll after component Identifier.
![IMG_0025](https://user-images.githubusercontent.com/54589269/75715458-6dcc1900-5c9b-11ea-97ef-f588dcb4233c.PNG)

3. The hamburger menu has some visual error.
![IMG_0024](https://user-images.githubusercontent.com/54589269/75715459-6e64af80-5c9b-11ea-9766-c9224cdfc817.PNG)

**Comment by stefanoScalzo** [comment]
@droshev this is technically gonna be fixed in my grids

**Comment by stefanoScalzo** [comment]
The giant space is not visible on other iPad simulators. @droshev
