### ISSUE TITLE
iPad Visual Testing: Form Select popover 

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#740]
The popover in Form select has visual errors: the font size is different 
![IMG_0027](https://user-images.githubusercontent.com/54589269/75717633-7f172480-5c9f-11ea-950a-696343936eed.PNG)

**Comment by stefanoScalzo** [comment]
Cannnot replicate this on any ipad or xcode simulator. Seen it in person but it seems like it is for only extremely old ipads. @droshev
