### ISSUE TITLE
Wizard component

### ISSUE THREAD

**Issue by andresfelipe66** [SAP/fundamental-styles#747]
#### Is this a bug, enhancement, or feature request?
Feature Request

#### Briefly describe your proposal.
We are trying to implement other Wizards available on the Web (Bootstrap), but I'm trying to validate if it's possible to have something related to Fiori.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Current Version

#### Is there anything else we should know?
I'd like to have something similar to openui5 Wizard. https://openui5.hana.ondemand.com/api/sap.m.Wizard#overview

We are implementing a solution with different Wizards (Process step by step) (In our architecture we are using Ui5 web components and Fiori fundamental-ngx). And, off course we like to have the SAP Fiori User Experience.

**Comment by droshev** [comment]
@estelaxu3 can you validate the status of the design?

**Comment by salarenko** [comment]
By now "Wizard Functionality" can be achieved using `Tabs` component in process mode. Its slightly different visual experience, but I think it covers the desired functionality.

[NGX Core](https://sap.github.io/fundamental-ngx/#/core/tabs#processMode)
[Fundamental Styles](https://sap.github.io/fundamental-styles/components/tabs.html)

**Comment by widra** [comment]
Is it possible to implement the 'real' wizard function from ui5?

**Comment by droshev** [comment]
@andresfelipe66 @widra please follow the Wizard epic #1366
