### ISSUE TITLE
Error trying to import fundamental-styles from the fundamental-ngx distribution folder

### ISSUE THREAD

**Issue by andreean** [SAP/fundamental-styles#758]
My import command was this:

`@import "node_modules/@fundamental-ngx/core/node_modules/fundamental-styles/dist/form-item.css";`

See attached the error:
<img width="1602" alt="Screen Shot 2020-03-04 at 10 23 45 AM" src="https://user-images.githubusercontent.com/5807422/75909484-3172f700-5e1a-11ea-9f39-1d28e1e93c47.png">

Would it be possible to include the fundamental-styles in a vendor folder not a distribution folder? Someone suggested this solution on Stackoverflow and it fixed the issue for them:

https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type

Thank you for having a look :)

**Comment by droshev** [comment]
Can u just add fundamental-styles as dev dependancy and use the css directly?
