### ISSUE TITLE
Fiori 3 Design Review: Side Navigation should exclude Condensed Mode

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#788]
There should not have condensed mode in Side Navigation with Group Header cannot have Condensed Mode. 

https://sap.github.io/fundamental-styles/components/side-navigation.html

**Comment by droshev** [comment]
I think the solution of this issue is just to update the documentation and write what is the recommended way.

**Comment by estelaxu3** [comment]
I think it is a good idea. We can keep the condensed mode for now and I can propose this to visual core designers.
