### ISSUE TITLE
Fiori 3 Design Review: Side Navigation utility area separator 

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#790]
Removing the delta between expanded and condensed modes for these paddings was the one of the latest updates in the spec which can be find here:
https://wiki.wdf.sap.corp/wiki/display/visualcore/Change+Log

Side navigation: https://sap.github.io/fundamental-styles/components/side-navigation.html

**Comment by droshev** [comment]
```
Left/right paddings of the Utility Area separator line in expanded state updated to match the Utility Area separator line left-right paddings in the condensed state. 
```
Top/bottom paddings: 0.25 rem
Left/right paddings: 0.5 rem
