### ISSUE TITLE
Fiori 3 Design Review: List arrow size and color

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#791]
There is a distinction that exists between the navigation indication arrow and the arrow in the Side Navigation, comes from the fact that the first is not interactive while the latter is. Therefore, the size and color arrow in List navigation should realign with here:

Wiki: https://wiki.wdf.sap.corp/wiki/display/visualcore/List+%28Fiori+3%29+-+Navigation+Indication

<img width="759" alt="Screen Shot 2020-03-19 at 9 14 47 PM" src="https://user-images.githubusercontent.com/54589269/77128544-d864af00-6a26-11ea-8055-a4abca8e8fc1.png">

https://sap.github.io/fundamental-styles/components/list.html

**Comment by JKMarkowski** [comment]
For side navigation I took information from 
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2075534845
They are a little bit different.
