### ISSUE TITLE
Shellbar menu is using the wrong down arrow icon

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-styles#802]
![Screen Shot 2020-03-25 at 2 49 46 PM](https://user-images.githubusercontent.com/2471874/77584233-15f28d80-6ea8-11ea-8a39-0a2e8ae283eb.png)

should be 

![Screen Shot 2020-03-25 at 2 49 58 PM](https://user-images.githubusercontent.com/2471874/77584251-1f7bf580-6ea8-11ea-8e40-130464c5db1d.png)

**Comment by droshev** [comment]
fixed
