### ISSUE TITLE
Bug: Wrong aria-labels

### ISSUE THREAD

**Issue by SaiShan** [SAP/fundamental-styles#81]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

- [ ] If the user tabs into the ‘Right Aligned Text Addon’ element in the Input group component, he only can hear ‘Field placeholder text edit’ instead of ‘Right Aligned Text Addon edit’.

- [ ] The Localization Editor has labels which the Screen Reader reads as ‘enter label popup edit’ instead of ‘Localization Editor Label Edit’.

- [ ] The Multi Input reads as ‘image label as popup select fruit edit type in text’ Instead it should read as ‘Select fruit edit type in text’.

- [ ] The `...` menu reads as 'blank' instead of 'context menu' in the tree component.

**Comment by droshev** [comment]
most of the components have been refactored
