### ISSUE TITLE
Search input has additional 'X' button

### ISSUE THREAD

**Issue by rengare** [SAP/fundamental-styles#824]
**Describe the bug**
![image](https://user-images.githubusercontent.com/10849982/78009530-77e84280-7341-11ea-8d59-934476a67d0b.png)

> Is this issue related to a specific component?
Input group

> What version of the Fundamental Library Styles are you using?
Master

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Styles

**Expected behavior**
There should be only one 'X' button

![image](https://user-images.githubusercontent.com/10849982/78009757-c5fd4600-7341-11ea-979f-a80dd91ac598.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser IE
 - Version 11

**Comment by droshev** [comment]
In fact Fiori 3 has search field and there is X button. We need to bring this component
