### ISSUE TITLE
feat: DisplayOnly Mode checkbox styles

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-styles#837]
Display Only checkbox needs to be created in Core checkbox. Currently styles for Displayonly mode for checkbox is not created. This PR submits styles changes for Display only checkbox.

**Is your feature request related to a problem? Please describe.**

> Is this issue related to a specific component?
Checkbox

> What browser are you working in?
Chrome, Firefox, Microsoft edge, safari

> What version of Fundamental Library Styles are you using?
0.8.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**Describe the solution you'd like**
Display only checkbox should be created.

**Describe alternatives you've considered**

**Additional context**

**Comment by zaheral** [comment]
Hi @DeepakSap14 ,
I'm also interested on this issue. I saw that it is a while ago, since the last update. Do we have some news on this ticket?

**Comment by DeepakSap14** [comment]
Hi @Zaheral,
Currently this is not in priority for us. we had a PR but it is closed without merge because of clarifications pending.
if you wish you can work on it. you can see related comments on.
https://github.com/SAP/fundamental-styles/pull/838.

**Comment by droshev** [comment]
duplicated https://github.com/SAP/fundamental-styles/issues/1743
