### ISSUE TITLE
Feed Input component styles creation as per Fiori3 standards.

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#856]
Create Feed input component styles as per Fiori3 standards.

<img width="1169" alt="Screen Shot 2020-04-13 at 12 23 31 PM" src="https://user-images.githubusercontent.com/53487468/79099385-9d357180-7d81-11ea-9a28-597aa7c0f16c.png">

**Comment by manjunathanagaraj** [comment]
https://sap.github.io/fundamental-styles/?path=/docs/components-feed-input--standard - styles is done and GA. 
Therefore closing it.
