### ISSUE TITLE
Feed List item styles creation as per Fiori3 standards.

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#857]
Create Feed list item styles 

<img width="1230" alt="Screen Shot 2020-04-13 at 12 25 49 PM" src="https://user-images.githubusercontent.com/53487468/79099505-ed143880-7d81-11ea-967c-d60a6e36a0eb.png">

**Comment by manjunathanagaraj** [comment]
To be assigned to Evgeny Beregovoy
