### ISSUE TITLE
Simple gird does not work with 12 columns

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental-styles#859]
**Describe the bug**
The simple grid component does not work with 12 col layout. 
https://sap.github.io/fundamental-styles/layouts/grid.html

> Is this issue related to a specific component?
grid 

> What version of the Fundamental Library Styles are you using?
using fundamental-ngx v0.15.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
cloud portal

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
angular 

**To Reproduce**
1. Go to https://sap.github.io/fundamental-styles/layouts/grid.html
2. scroll down to 12 COLUMNS example
3. notice the last two columns wrap to second line 

**Expected behavior**
any combination of col--[num] that adds up to 12 should fit on one line 

**Screenshots**
<img width="1136" alt="Screen Shot 2020-04-13 at 11 59 39 AM" src="https://user-images.githubusercontent.com/15215400/79140874-4bd7b300-7d7e-11ea-9097-39467fc9090f.png">

**Additional context**
The `layout grid` components work well, however, we still need the simple `grid` component for use with divs and without any `panel` component.

**Comment by saad-mo** [comment]
looks like the latest version (0.8.0) does not publish the `--fd-width-gutter` variable anymore in `page.css`. since this var does not exist, it's breaking the grid component width calculation 

In version 0.6.0 `page.css` included `--fd-width-gutter` variable.

**Comment by saad-mo** [comment]
@InnaAtanasova @mikerodonnell89  - guys this is a big breaking change unaccounted for in the latest release of fundamental-ngx (0.16.0)

**Comment by droshev** [comment]
solved
