### ISSUE TITLE
checkbox & radio: required class (with asterisk) is missing

### ISSUE THREAD

**Issue by maheshiv** [SAP/fundamental-styles#883]
**Describe the bug**

 _Form label required class not working with checkbox label_

> Is this issue related to a specific component?
Form: Checkbox & Radio
> What version of the Fundamental Library Styles are you using?
0.7
> What front-end framework are you implementing in, e.g., Angular, React, etc.?
AureliaJS

**To Reproduce**
1. Go to Forms component
2. Add `fd-form-label--required` class on checkbox label (`fd-checkbox__label`)
3. Asterisk(*) not aligned with checkbox label

**Expected behavior**
_Checkbox & Radio button should include required class with out any alignment issue_
**Screenshots**
![image](https://user-images.githubusercontent.com/1209471/79947775-2f2f2f80-8490-11ea-95ff-eaad7117079a.png)

**Comment by stefanoScalzo** [comment]
For the radio checkbox, do u want to have required on the whole fieldset or per item?
