### ISSUE TITLE
Fiori 3 Table

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-styles#914]
Table component: 
- [x] Base Table Component - Header, Body, Footer + sizes + states(hover, active, selected) - Done in https://github.com/SAP/fundamental-styles/pull/1042
- [x] Table with checkboxes + sizes - Done in https://github.com/SAP/fundamental-styles/pull/1042
- [x] Highlight Row (fiori3 site) - Elements on left + text - Done in https://github.com/SAP/fundamental-styles/pull/1042
- [x] Navigation Indication (fiori3 site) - Icon on right - Mike Done in https://github.com/SAP/fundamental-styles/pull/1042
- [ ] Analytical Table (fiori3 site) - Group Table
- [x] Responsive Table (fiori3 site) - Pop-in positioning + Merged Cells Done in https://github.com/SAP/fundamental-styles/pull/1042

**Comment by JKMarkowski** [comment]
Questions:
* What about the active state, how should behave active state:
first:
![table1](https://user-images.githubusercontent.com/26483208/82558082-39b31680-9b6d-11ea-9a5f-1f9a968fb1c5.gif)
second:
![table2](https://user-images.githubusercontent.com/26483208/82558094-3fa8f780-9b6d-11ea-82f9-4e87d974982d.gif)
