### ISSUE TITLE
fundamental Switch state doesn't refresh

### ISSUE THREAD

**Issue by cham2017** [SAP/fundamental-styles#918]
// With code below, when clicking the button, Switch's checked state should be refreshed but in fact it's not.

import { Switch } from "fundamental-react";

const SwitchTest = () => {
  const [value, setValue] = useState(true);
  const handleClick = () => {
    setValue(!value);
  }
  return <div><div><Button onClick={handleClick}>test</Button></div > <SwitchWraper checked={value} /></div>;
};

const SwitchWraper = (props: any) => {
  return <Switch {...props}></Switch>
}

export const FundamentalSwitchIssue = () => {
  return <SwitchTest />;
}

**Comment by salarenko** [comment]
Hi @cham2017, it looks like this issue is rather React component implementation than its visuals. I recommend creating an issue [here](https://github.com/SAP/fundamental-react/issues)
