### ISSUE TITLE
Old values for 'fd-shell__header' and 'fd-shell__app' 

### ISSUE THREAD

**Issue by marynaKhromova** [SAP/fundamental-styles#976]
**Describe the bug**
The bug appears when [Application Shell Layout](https://sap.github.io/fundamental-styles/layouts/shell-layout.html) is used together with [Shellbar component](https://sap.github.io/fundamental-styles/components/shellbar.html).

`fd-shell__header` and `fd-shell__app` have old values as `48px` (height: 48px, margin-top: 48px), and at the same time  `fd-shellbar`  has a new height `44px`.

As a result there is a 4px gap between the shellbar and the main content below.

> Is this issue related to a specific component?
[Application Shell Layout](https://sap.github.io/fundamental-styles/layouts/shell-layout.html)
[Shellbar component](https://sap.github.io/fundamental-styles/components/shellbar.html)

> What version of the Fundamental Library Styles are you using?
0.8.1

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**Expected behavior**
All values should be either 44px or 48px

**Screenshots**
<img width="1014" alt="gap" src="https://user-images.githubusercontent.com/46446373/81167839-37aa5e80-8f96-11ea-826a-348a1b4286f2.png">

**Comment by droshev** [comment]
this seems to be outdates. Feel free to open a new issue if this exist
