### ISSUE TITLE
Layout for Sidebar is broken on mobile

### ISSUE THREAD

**Issue by marynaKhromova** [SAP/fundamental-styles#979]
**Describe the bug**
There are some styles for `fd-app` and `fd-app__navigation--vertical` that apply only for `@media (min-width: 600px)`. But without them on the mobile resolution, the layout looks broken.

> Is this issue related to a specific component?
[Application Shell - Application with Sidebar](https://sap.github.io/fundamental-styles/layouts/shell-layout.html)

> What version of the Fundamental Library Styles are you using?
0.8.1

**Expected behavior**
Sidebar is displayed to the left of main content (The same behavior like for the desktop breakpoint)

**Screenshots**
Styles for `fd-app`
<img width="1113" alt="fd-app" src="https://user-images.githubusercontent.com/46446373/81165915-1d22b600-8f93-11ea-89bd-d4997210c2d6.png">

Styles for `fd-app__navigation--vertical`
<img width="1343" alt="fd-app__navigation--vertical styles" src="https://user-images.githubusercontent.com/46446373/81165992-3c214800-8f93-11ea-81b8-bd77667fce04.png">

The broken layout on mobile
<img width="954" alt="broken layout" src="https://user-images.githubusercontent.com/46446373/81166025-4cd1be00-8f93-11ea-983b-e199d695e05e.png">

**Comment by droshev** [comment]
Most probably it is fixed. would you re-open it or create a new issue if you face more issues with side nav?
