### ISSUE TITLE
Contrast ratio for attention button is 3.03 causing accessibility issues

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#984]
**Describe the bug**
Background and foreground colors do not have a sufficient contrast ratio for the attention button which is causing accessibility issues to read the content for low vision people.

<img width="214" alt="Screen Shot 2020-05-07 at 3 29 29 PM" src="https://user-images.githubusercontent.com/53487468/81282136-6436a700-9078-11ea-9020-9767353f3e90.png">

**Comment by droshev** [comment]
we aren't owners of the colors, so I am closing the issue
